import type { CustomerCategory } from "./types";

export const CUSTOMER_CATEGORIES: CustomerCategory[] = [
  {
    key: "VIDEO",
    title: "Video",
    description: "Create, edit, and enhance videos.",
    order: 10,
    enabled: true,
    icon: "video",
    navGroup: "CREATE",
  },
  {
    key: "IMAGE",
    title: "Image",
    description: "Edit, enhance, and prepare photos.",
    order: 20,
    enabled: true,
    icon: "image",
    navGroup: "CREATE",
  },
  {
    key: "PHOTO_STUDIO",
    title: "Photo Studio",
    description: "ID, passport, and professional portraits.",
    order: 30,
    enabled: true,
    icon: "camera",
    navGroup: "CREATE",
  },
  {
    key: "DESIGN",
    title: "Design Studio",
    description: "Flyers, posters, cards, and brand graphics.",
    order: 40,
    enabled: true,
    icon: "pen-tool",
    navGroup: "CREATE",
  },
  {
    key: "AUDIO",
    title: "Audio",
    description: "Music, voice, and speech tools.",
    order: 50,
    enabled: true,
    icon: "audio",
    navGroup: "CREATE",
  },
  {
    key: "MY_WORK",
    title: "My Work",
    description: "Projects, assets, and finished files.",
    order: 60,
    enabled: true,
    icon: "folder",
    navGroup: "MY_WORK",
  },
  {
    key: "ACCOUNT",
    title: "Account",
    description: "Settings and help.",
    order: 70,
    enabled: true,
    icon: "user",
    navGroup: "ACCOUNT",
  },
];
