import type { CustomerService } from "./types";

function svc(
  partial: Omit<CustomerService, "enabled" | "metadata" | "keywords"> & {
    enabled?: boolean;
    keywords?: string[];
    metadata?: Record<string, unknown>;
  },
): CustomerService {
  return {
    ...partial,
    enabled: partial.status !== "DISABLED" && (partial.enabled ?? true),
    keywords: partial.keywords ?? [partial.title, partial.category],
    metadata: partial.metadata ?? {},
  };
}

/**
 * Canonical customer services. AVAILABLE maps to existing Studio workspaces.
 * COMING_SOON is catalogued but not presented as a working product.
 */
export const CUSTOMER_SERVICES: CustomerService[] = [
  svc({
    key: "create-video",
    title: "Create Video",
    description: "Turn your photos into professional videos.",
    category: "VIDEO",
    icon: "clapperboard",
    route: "/create/video",
    status: "AVAILABLE",
    order: 10,
    workspace: "service-create-video",
    keywords: ["video", "create", "film", "reel"],
  }),
  svc({
    key: "product-marketing-video",
    title: "Product Marketing Video",
    description: "Turn a product into a marketing video.",
    category: "VIDEO",
    icon: "megaphone",
    route: "/create/video/product",
    status: "AVAILABLE",
    order: 20,
    workspace: "service-create-video",
    keywords: ["product", "marketing", "video", "campaign"],
  }),
  svc({
    key: "social-media-video",
    title: "Social Media Video",
    description: "Short-form video for social platforms.",
    category: "VIDEO",
    icon: "share",
    route: "/create/video/social",
    status: "COMING_SOON",
    order: 30,
  }),
  svc({
    key: "video-editing",
    title: "Video Editing",
    description: "Edit and refine existing video.",
    category: "VIDEO",
    icon: "scissors",
    route: "/create/video/edit",
    status: "COMING_SOON",
    order: 40,
  }),
  svc({
    key: "video-enhancement",
    title: "Video Enhancement",
    description: "Improve quality, color, and clarity.",
    category: "VIDEO",
    icon: "sparkles",
    route: "/create/video/enhance",
    status: "COMING_SOON",
    order: 50,
  }),

  svc({
    key: "edit-photo",
    title: "Edit Photo",
    description: "Enhance, edit and prepare your photos.",
    category: "IMAGE",
    icon: "image",
    route: "/create/image/edit",
    status: "AVAILABLE",
    order: 10,
    workspace: "service-edit-photo",
    keywords: ["photo", "edit", "image"],
  }),
  svc({
    key: "enhance-photo",
    title: "Enhance Photo",
    description: "Sharpen, light, and improve product photos.",
    category: "IMAGE",
    icon: "wand",
    route: "/create/image/enhance",
    status: "AVAILABLE",
    order: 20,
    workspace: "image-organization",
  }),
  svc({
    key: "remove-background",
    title: "Remove Background",
    description: "Isolate the product from its background.",
    category: "IMAGE",
    icon: "eraser",
    route: "/create/image/background",
    status: "AVAILABLE",
    order: 30,
    workspace: "service-edit-photo",
  }),
  svc({
    key: "resize-crop",
    title: "Resize / Crop",
    description: "Resize and crop images for any format.",
    category: "IMAGE",
    icon: "crop",
    route: "/create/image/crop",
    status: "COMING_SOON",
    order: 40,
  }),
  svc({
    key: "product-photo",
    title: "Product Photo",
    description: "Prepare product photography for marketing.",
    category: "IMAGE",
    icon: "package",
    route: "/create/image/product",
    status: "AVAILABLE",
    order: 50,
    workspace: "service-create-video",
  }),

  svc({
    key: "passport-photo",
    title: "Passport Photo",
    description: "Create a clean passport-ready photo.",
    category: "PHOTO_STUDIO",
    icon: "id-card",
    route: "/create/photo/passport",
    status: "AVAILABLE",
    order: 10,
    workspace: "service-passport",
    keywords: ["passport", "photo", "id"],
  }),
  svc({
    key: "id-photo",
    title: "ID Photo",
    description: "Identity-document portraits.",
    category: "PHOTO_STUDIO",
    icon: "badge",
    route: "/create/photo/id",
    status: "COMING_SOON",
    order: 20,
  }),
  svc({
    key: "professional-photo",
    title: "Professional Photo",
    description: "Studio-style professional portraits.",
    category: "PHOTO_STUDIO",
    icon: "camera",
    route: "/create/photo/professional",
    status: "COMING_SOON",
    order: 30,
  }),
  svc({
    key: "take-photo",
    title: "Take Photo",
    description: "Capture a photo in the studio.",
    category: "PHOTO_STUDIO",
    icon: "aperture",
    route: "/create/photo/capture",
    status: "COMING_SOON",
    order: 40,
  }),
  svc({
    key: "photo-enhancement",
    title: "Photo Enhancement",
    description: "Retouch and enhance portraits.",
    category: "PHOTO_STUDIO",
    icon: "sun",
    route: "/create/photo/enhance",
    status: "COMING_SOON",
    order: 50,
  }),

  svc({
    key: "design-studio",
    title: "Design Studio",
    description: "Create flyers, posters, banners and more.",
    category: "DESIGN",
    icon: "pen-tool",
    route: "/create/design",
    status: "COMING_SOON",
    order: 1,
    keywords: ["design", "flyer", "poster", "banner", "graphics"],
  }),
  svc({
    key: "flyer",
    title: "Flyer",
    description: "Design a promotional flyer.",
    category: "DESIGN",
    icon: "file-text",
    route: "/create/design/flyer",
    status: "COMING_SOON",
    order: 10,
  }),
  svc({
    key: "poster",
    title: "Poster",
    description: "Design a poster.",
    category: "DESIGN",
    icon: "layout",
    route: "/create/design/poster",
    status: "COMING_SOON",
    order: 20,
  }),
  svc({
    key: "banner",
    title: "Banner",
    description: "Web and print banners.",
    category: "DESIGN",
    icon: "panel",
    route: "/create/design/banner",
    status: "COMING_SOON",
    order: 30,
  }),
  svc({
    key: "business-card",
    title: "Business Card",
    description: "Professional business cards.",
    category: "DESIGN",
    icon: "contact",
    route: "/create/design/business-card",
    status: "COMING_SOON",
    order: 40,
  }),
  svc({
    key: "invitation",
    title: "Invitation",
    description: "Event invitations.",
    category: "DESIGN",
    icon: "mail",
    route: "/create/design/invitation",
    status: "COMING_SOON",
    order: 50,
  }),
  svc({
    key: "save-the-date",
    title: "Save the Date",
    description: "Save-the-date designs.",
    category: "DESIGN",
    icon: "calendar",
    route: "/create/design/save-the-date",
    status: "COMING_SOON",
    order: 60,
  }),
  svc({
    key: "wedding-design",
    title: "Wedding Design",
    description: "Wedding stationery and graphics.",
    category: "DESIGN",
    icon: "heart",
    route: "/create/design/wedding",
    status: "COMING_SOON",
    order: 70,
  }),
  svc({
    key: "birthday-design",
    title: "Birthday Design",
    description: "Birthday cards and graphics.",
    category: "DESIGN",
    icon: "gift",
    route: "/create/design/birthday",
    status: "COMING_SOON",
    order: 80,
  }),
  svc({
    key: "certificate",
    title: "Certificate",
    description: "Certificates and awards.",
    category: "DESIGN",
    icon: "award",
    route: "/create/design/certificate",
    status: "COMING_SOON",
    order: 90,
  }),
  svc({
    key: "menu",
    title: "Menu",
    description: "Restaurant and event menus.",
    category: "DESIGN",
    icon: "list",
    route: "/create/design/menu",
    status: "COMING_SOON",
    order: 100,
  }),
  svc({
    key: "product-label",
    title: "Product Label",
    description: "Packaging and product labels.",
    category: "DESIGN",
    icon: "tag",
    route: "/create/design/label",
    status: "COMING_SOON",
    order: 110,
  }),
  svc({
    key: "social-media-design",
    title: "Social Media Design",
    description: "Posts, covers, and social graphics.",
    category: "DESIGN",
    icon: "share",
    route: "/create/design/social",
    status: "COMING_SOON",
    order: 120,
  }),
  svc({
    key: "advertisement",
    title: "Advertisement",
    description: "Print and digital ads.",
    category: "DESIGN",
    icon: "megaphone",
    route: "/create/design/ad",
    status: "COMING_SOON",
    order: 130,
  }),
  svc({
    key: "billboard",
    title: "Billboard",
    description: "Large-format outdoor design.",
    category: "DESIGN",
    icon: "billboard",
    route: "/create/design/billboard",
    status: "COMING_SOON",
    order: 140,
  }),

  svc({
    key: "music",
    title: "Music",
    description: "Generate or edit music beds.",
    category: "AUDIO",
    icon: "music",
    route: "/create/audio/music",
    status: "COMING_SOON",
    order: 10,
  }),
  svc({
    key: "voice-over",
    title: "Voice-over",
    description: "Record or generate voice-over.",
    category: "AUDIO",
    icon: "mic",
    route: "/create/audio/voice-over",
    status: "COMING_SOON",
    order: 20,
  }),
  svc({
    key: "text-to-speech",
    title: "Text-to-Speech",
    description: "Convert copy into speech.",
    category: "AUDIO",
    icon: "speech",
    route: "/create/audio/tts",
    status: "COMING_SOON",
    order: 30,
  }),
  svc({
    key: "speech-to-text",
    title: "Speech-to-Text",
    description: "Transcribe speech to text.",
    category: "AUDIO",
    icon: "captions",
    route: "/create/audio/stt",
    status: "COMING_SOON",
    order: 40,
  }),
  svc({
    key: "audio-editing",
    title: "Audio Editing",
    description: "Edit existing audio.",
    category: "AUDIO",
    icon: "waveform",
    route: "/create/audio/edit",
    status: "COMING_SOON",
    order: 50,
  }),

  svc({
    key: "projects",
    title: "Projects",
    description: "Open and manage your projects.",
    category: "MY_WORK",
    icon: "folder",
    route: "/work/projects",
    status: "AVAILABLE",
    order: 10,
    workspace: "open-project",
    keywords: ["projects", "files", "work"],
  }),
  svc({
    key: "assets",
    title: "Assets",
    description: "Browse your media library.",
    category: "MY_WORK",
    icon: "library",
    route: "/work/assets",
    status: "AVAILABLE",
    order: 20,
    workspace: "asset-library",
  }),
  svc({
    key: "images",
    title: "Images",
    description: "Your generated and imported images.",
    category: "MY_WORK",
    icon: "image",
    route: "/work/images",
    status: "AVAILABLE",
    order: 30,
    workspace: "generated-images",
  }),
  svc({
    key: "videos",
    title: "Videos",
    description: "Your video productions.",
    category: "MY_WORK",
    icon: "video",
    route: "/work/videos",
    status: "AVAILABLE",
    order: 40,
    workspace: "generated-videos",
  }),
  svc({
    key: "designs",
    title: "Designs",
    description: "Saved design files.",
    category: "MY_WORK",
    icon: "layout",
    route: "/work/designs",
    status: "COMING_SOON",
    order: 50,
  }),
  svc({
    key: "audio-library",
    title: "Audio",
    description: "Your audio files.",
    category: "MY_WORK",
    icon: "audio",
    route: "/work/audio",
    status: "AVAILABLE",
    order: 60,
    workspace: "generated-audio",
  }),

  svc({
    key: "settings",
    title: "Settings",
    description: "Customer account and studio preferences.",
    category: "ACCOUNT",
    icon: "settings",
    route: "/account/settings",
    status: "AVAILABLE",
    order: 10,
    workspace: "settings",
  }),
  svc({
    key: "help",
    title: "Help",
    description: "Guides and support.",
    category: "ACCOUNT",
    icon: "help",
    route: "/account/help",
    status: "AVAILABLE",
    order: 20,
    workspace: "help",
  }),
];
