import type { CustomerService, CustomerUseCase } from "./types";

function svc(
  partial: Omit<CustomerService, "enabled" | "metadata" | "keywords"> & {
    enabled?: boolean;
    keywords?: string[];
    metadata?: Record<string, unknown>;
    useCase?: CustomerUseCase;
    subcategory?: string;
  },
): CustomerService {
  return {
    ...partial,
    enabled: partial.status !== "DISABLED" && (partial.enabled ?? true),
    keywords: partial.keywords ?? [partial.title, partial.category],
    metadata: partial.metadata ?? {},
  };
}

/**
 * Canonical customer services. AVAILABLE maps to existing Studio workspaces.
 * COMING_SOON is catalogued but not presented as a working product.
 * Category hub rows use metadata.homeVisible = false so Home shows real services.
 */
export const CUSTOMER_SERVICES: CustomerService[] = [
  // —— VIDEO ——
  svc({
    key: "image-to-video",
    title: "Image to Video",
    description: "Animate photos into short videos.",
    category: "VIDEO",
    icon: "clapperboard",
    route: "/create/video/image-to-video",
    status: "COMING_SOON",
    order: 10,
    keywords: ["image", "photo", "animate", "video"],
  }),
  svc({
    key: "video-editing",
    title: "Video Editing",
    description: "Trim, arrange, and refine existing video.",
    category: "VIDEO",
    icon: "scissors",
    route: "/create/video/edit",
    status: "COMING_SOON",
    order: 20,
  }),
  svc({
    key: "text-to-video",
    title: "Text to Video",
    description: "Turn a written idea into video scenes.",
    category: "VIDEO",
    icon: "file-text",
    route: "/create/video/text",
    status: "COMING_SOON",
    order: 30,
    keywords: ["text", "prompt", "script", "video"],
  }),
  svc({
    key: "create-video",
    title: "Create Video",
    description: "Turn your photos into professional videos.",
    category: "VIDEO",
    icon: "clapperboard",
    route: "/create/video",
    status: "AVAILABLE",
    order: 40,
    workspace: "service-create-video",
    keywords: ["video", "create", "film", "reel"],
  }),
  svc({
    key: "product-marketing-video",
    title: "Product Marketing Video",
    description: "Turn a product into a marketing video.",
    category: "VIDEO",
    icon: "megaphone",
    route: "/create/video/product",
    status: "AVAILABLE",
    order: 50,
    workspace: "service-create-video",
    useCase: "MARKETING",
    keywords: ["product", "marketing", "video", "campaign"],
  }),
  svc({
    key: "social-media-video",
    title: "Social Media Video",
    description: "Short-form video for social platforms.",
    category: "VIDEO",
    icon: "share",
    route: "/create/video/social",
    status: "COMING_SOON",
    order: 60,
    useCase: "SOCIAL_MEDIA",
  }),
  svc({
    key: "promotional-video",
    title: "Promotional Video",
    description: "Campaign and promo video clips.",
    category: "VIDEO",
    icon: "megaphone",
    route: "/create/video/promo",
    status: "COMING_SOON",
    order: 70,
    useCase: "MARKETING",
  }),
  svc({
    key: "product-video",
    title: "Product Video",
    description: "Showcase products in motion.",
    category: "VIDEO",
    icon: "package",
    route: "/create/video/product-clip",
    status: "COMING_SOON",
    order: 80,
    useCase: "PRODUCT",
  }),
  svc({
    key: "ai-video-creation",
    title: "AI Video Creation",
    description: "Generate video with AI-assisted creative planning.",
    category: "VIDEO",
    icon: "sparkles",
    route: "/create/video/ai",
    status: "COMING_SOON",
    order: 90,
  }),
  svc({
    key: "image-based-product-video",
    title: "Image-based Product Video",
    description: "Build product videos from still product photos.",
    category: "VIDEO",
    icon: "package",
    route: "/create/video/image-product",
    status: "COMING_SOON",
    order: 100,
    useCase: "PRODUCT",
    keywords: ["product", "images", "photos", "video"],
  }),
  svc({
    key: "video-enhancement",
    title: "Video Enhancement",
    description: "Improve quality, color, and clarity.",
    category: "VIDEO",
    icon: "sparkles",
    route: "/create/video/enhance",
    status: "COMING_SOON",
    order: 110,
  }),

  // —— IMAGE ——
  svc({
    key: "edit-photo",
    title: "Edit Photo",
    description: "Enhance, edit and prepare your photos.",
    category: "IMAGE",
    icon: "image",
    route: "/create/image/edit",
    status: "AVAILABLE",
    order: 10,
    workspace: "service-edit-photo",
    keywords: ["photo", "edit", "image"],
  }),
  svc({
    key: "enhance-photo",
    title: "Enhance Photo",
    description: "Sharpen, light, and improve product photos.",
    category: "IMAGE",
    icon: "wand",
    route: "/create/image/enhance",
    status: "AVAILABLE",
    order: 20,
    workspace: "image-organization",
  }),
  svc({
    key: "remove-background",
    title: "Remove Background",
    description: "Isolate the subject from its background.",
    category: "IMAGE",
    icon: "eraser",
    route: "/create/image/background",
    status: "AVAILABLE",
    order: 30,
    workspace: "service-edit-photo",
  }),
  svc({
    key: "resize-crop",
    title: "Resize / Crop",
    description: "Resize and crop images for any format.",
    category: "IMAGE",
    icon: "crop",
    route: "/create/image/crop",
    status: "COMING_SOON",
    order: 40,
  }),
  svc({
    key: "product-photo",
    title: "Product Photo",
    description: "Prepare product photography for marketing.",
    category: "IMAGE",
    icon: "package",
    route: "/create/image/product",
    status: "AVAILABLE",
    order: 50,
    workspace: "service-create-video",
    useCase: "PRODUCT",
  }),
  svc({
    key: "image-photo-enhancement",
    title: "Photo Enhancement",
    description: "Improve clarity, color, and detail.",
    category: "IMAGE",
    icon: "sun",
    route: "/create/image/photo-enhance",
    status: "COMING_SOON",
    order: 60,
  }),
  svc({
    key: "professional-photo-editing",
    title: "Professional Photo Editing",
    description: "Advanced retouching and finishing.",
    category: "IMAGE",
    icon: "wand",
    route: "/create/image/pro-edit",
    status: "COMING_SOON",
    order: 70,
  }),
  svc({
    key: "image-optimization",
    title: "Image Optimization",
    description: "Optimize images for web and export.",
    category: "IMAGE",
    icon: "crop",
    route: "/create/image/optimize",
    status: "COMING_SOON",
    order: 80,
  }),
  svc({
    key: "product-image-preparation",
    title: "Product Image Preparation",
    description: "Prep product images for catalogs and ads.",
    category: "IMAGE",
    icon: "package",
    route: "/create/image/product-prep",
    status: "COMING_SOON",
    order: 90,
    useCase: "PRODUCT",
  }),

  // —— PHOTO STUDIO ——
  svc({
    key: "passport-photo",
    title: "Passport Photo",
    description: "Create a clean passport-ready photo.",
    category: "PHOTO_STUDIO",
    icon: "id-card",
    route: "/create/photo/passport",
    status: "AVAILABLE",
    order: 10,
    workspace: "service-passport",
    useCase: "IDENTITY",
    keywords: ["passport", "photo", "id"],
  }),
  svc({
    key: "id-photo",
    title: "ID Photo",
    description: "Identity-document portraits.",
    category: "PHOTO_STUDIO",
    icon: "badge",
    route: "/create/photo/id",
    status: "COMING_SOON",
    order: 20,
    useCase: "IDENTITY",
  }),
  svc({
    key: "professional-photo",
    title: "Professional Photo",
    description: "Studio-style professional portraits.",
    category: "PHOTO_STUDIO",
    icon: "camera",
    route: "/create/photo/professional",
    status: "COMING_SOON",
    order: 30,
  }),
  svc({
    key: "portrait-photo",
    title: "Portrait Photo",
    description: "Portrait framing and finishing.",
    category: "PHOTO_STUDIO",
    icon: "camera",
    route: "/create/photo/portrait",
    status: "COMING_SOON",
    order: 40,
  }),
  svc({
    key: "take-photo",
    title: "Take Photo / Camera",
    description: "Capture a photo with camera and enhance it.",
    category: "PHOTO_STUDIO",
    icon: "aperture",
    route: "/create/photo/capture",
    status: "COMING_SOON",
    order: 50,
    keywords: ["camera", "capture", "take photo"],
  }),
  svc({
    key: "photo-enhancement",
    title: "Photo Enhancement",
    description: "Retouch and enhance studio portraits.",
    category: "PHOTO_STUDIO",
    icon: "sun",
    route: "/create/photo/enhance",
    status: "COMING_SOON",
    order: 60,
  }),
  svc({
    key: "studio-photo-preparation",
    title: "Studio Photo Preparation",
    description: "Prepare studio shots for print and export.",
    category: "PHOTO_STUDIO",
    icon: "camera",
    route: "/create/photo/studio-prep",
    status: "COMING_SOON",
    order: 70,
  }),

  // —— DESIGN STUDIO ——
  svc({
    key: "design-studio",
    title: "Design Studio",
    description: "Create flyers, posters, banners and more.",
    category: "DESIGN",
    icon: "pen-tool",
    route: "/create/design",
    status: "COMING_SOON",
    order: 1,
    keywords: ["design", "flyer", "poster", "banner", "graphics"],
    metadata: { homeVisible: false },
  }),
  svc({
    key: "flyer",
    title: "Flyer",
    description: "Design a promotional flyer.",
    category: "DESIGN",
    icon: "file-text",
    route: "/create/design/flyer",
    status: "COMING_SOON",
    order: 10,
    useCase: "MARKETING",
  }),
  svc({
    key: "poster",
    title: "Poster",
    description: "Design a poster.",
    category: "DESIGN",
    icon: "layout",
    route: "/create/design/poster",
    status: "COMING_SOON",
    order: 20,
  }),
  svc({
    key: "banner",
    title: "Banner",
    description: "Web and print banners.",
    category: "DESIGN",
    icon: "panel",
    route: "/create/design/banner",
    status: "COMING_SOON",
    order: 30,
  }),
  svc({
    key: "billboard",
    title: "Billboard",
    description: "Large-format outdoor design.",
    category: "DESIGN",
    icon: "billboard",
    route: "/create/design/billboard",
    status: "COMING_SOON",
    order: 35,
  }),
  svc({
    key: "business-card",
    title: "Business Card",
    description: "Professional business cards.",
    category: "DESIGN",
    icon: "contact",
    route: "/create/design/business-card",
    status: "COMING_SOON",
    order: 40,
  }),
  svc({
    key: "service-card",
    title: "Service Card",
    description: "Service offering cards and flyers.",
    category: "DESIGN",
    icon: "contact",
    route: "/create/design/service-card",
    status: "COMING_SOON",
    order: 45,
  }),
  svc({
    key: "postcard",
    title: "Postcard",
    description: "Print-ready postcards.",
    category: "DESIGN",
    icon: "mail",
    route: "/create/design/postcard",
    status: "COMING_SOON",
    order: 48,
  }),
  svc({
    key: "invitation",
    title: "Invitation",
    description: "Event invitations.",
    category: "DESIGN",
    icon: "mail",
    route: "/create/design/invitation",
    status: "COMING_SOON",
    order: 50,
  }),
  svc({
    key: "save-the-date",
    title: "Save the Date",
    description: "Save-the-date designs.",
    category: "DESIGN",
    icon: "calendar",
    route: "/create/design/save-the-date",
    status: "COMING_SOON",
    order: 60,
  }),
  svc({
    key: "wedding-design",
    title: "Wedding Design",
    description: "Wedding stationery and graphics.",
    category: "DESIGN",
    icon: "heart",
    route: "/create/design/wedding",
    status: "COMING_SOON",
    order: 70,
  }),
  svc({
    key: "birthday-design",
    title: "Birthday Design",
    description: "Birthday cards and graphics.",
    category: "DESIGN",
    icon: "gift",
    route: "/create/design/birthday",
    status: "COMING_SOON",
    order: 80,
  }),
  svc({
    key: "certificate",
    title: "Certificate",
    description: "Certificates and awards.",
    category: "DESIGN",
    icon: "award",
    route: "/create/design/certificate",
    status: "COMING_SOON",
    order: 90,
  }),
  svc({
    key: "menu",
    title: "Menu",
    description: "Restaurant and event menus.",
    category: "DESIGN",
    icon: "list",
    route: "/create/design/menu",
    status: "COMING_SOON",
    order: 100,
  }),
  svc({
    key: "product-label",
    title: "Product Label",
    description: "Packaging and product labels.",
    category: "DESIGN",
    icon: "tag",
    route: "/create/design/label",
    status: "COMING_SOON",
    order: 110,
    useCase: "PRODUCT",
  }),
  svc({
    key: "social-media-design",
    title: "Social Media Design",
    description: "Posts, covers, and social graphics.",
    category: "DESIGN",
    icon: "share",
    route: "/create/design/social",
    status: "COMING_SOON",
    order: 120,
    useCase: "SOCIAL_MEDIA",
  }),
  svc({
    key: "advertisement",
    title: "Advertisement",
    description: "Print and digital ads.",
    category: "DESIGN",
    icon: "megaphone",
    route: "/create/design/ad",
    status: "COMING_SOON",
    order: 130,
    useCase: "MARKETING",
  }),
  svc({
    key: "creative-graphic",
    title: "Creative Graphic",
    description: "General creative graphic layouts.",
    category: "DESIGN",
    icon: "layout",
    route: "/create/design/creative",
    status: "COMING_SOON",
    order: 140,
  }),
  svc({
    key: "brand-graphic",
    title: "Brand Graphic",
    description: "Brand-consistent marketing graphics.",
    category: "DESIGN",
    icon: "pen-tool",
    route: "/create/design/brand",
    status: "COMING_SOON",
    order: 150,
    useCase: "MARKETING",
  }),
  svc({
    key: "logo-design",
    title: "Logo Design",
    description: "Logo concepts and brand marks.",
    category: "DESIGN",
    icon: "award",
    route: "/create/design/logo",
    status: "COMING_SOON",
    order: 160,
  }),

  // —— AUDIO ——
  svc({
    key: "music",
    title: "Music",
    description: "Browse and work with music beds.",
    category: "AUDIO",
    icon: "music",
    route: "/create/audio/music",
    status: "COMING_SOON",
    order: 10,
  }),
  svc({
    key: "music-generation",
    title: "Music Generation",
    description: "Generate original music beds.",
    category: "AUDIO",
    icon: "music",
    route: "/create/audio/generate",
    status: "COMING_SOON",
    order: 20,
  }),
  svc({
    key: "audio-editing",
    title: "Audio Editing",
    description: "Edit and refine existing audio.",
    category: "AUDIO",
    icon: "waveform",
    route: "/create/audio/edit",
    status: "COMING_SOON",
    order: 30,
  }),
  svc({
    key: "sound-design",
    title: "Sound Design",
    description: "Effects and sound design tools.",
    category: "AUDIO",
    icon: "waveform",
    route: "/create/audio/sound-design",
    status: "COMING_SOON",
    order: 40,
  }),
  svc({
    key: "ai-sound",
    title: "AI Sound",
    description: "Generate soundscapes and audio accents.",
    category: "AUDIO",
    icon: "sparkles",
    route: "/create/audio/ai-sound",
    status: "COMING_SOON",
    order: 50,
  }),
  svc({
    key: "audio-intelligence",
    title: "Audio Intelligence",
    description: "Analyze and structure audio for creative work.",
    category: "AUDIO",
    icon: "waveform",
    route: "/create/audio/intelligence",
    status: "COMING_SOON",
    order: 60,
  }),
  svc({
    key: "beat-sync",
    title: "Beat Sync",
    description: "Align cuts and motion to musical beats.",
    category: "AUDIO",
    icon: "music",
    route: "/create/audio/beat-sync",
    status: "COMING_SOON",
    order: 70,
  }),

  // —— VOICE ——
  svc({
    key: "voice-over",
    title: "Voice-over",
    description: "Record or generate voice-over.",
    category: "VOICE",
    icon: "mic",
    route: "/create/voice/voice-over",
    status: "COMING_SOON",
    order: 10,
  }),
  svc({
    key: "text-to-speech",
    title: "Text-to-Speech",
    description: "Convert copy into speech.",
    category: "VOICE",
    icon: "speech",
    route: "/create/voice/tts",
    status: "COMING_SOON",
    order: 20,
  }),
  svc({
    key: "speech-to-text",
    title: "Speech-to-Text",
    description: "Transcribe speech to text.",
    category: "VOICE",
    icon: "captions",
    route: "/create/voice/stt",
    status: "COMING_SOON",
    order: 30,
  }),
  svc({
    key: "voice-narration",
    title: "Narration",
    description: "Narration for videos and stories.",
    category: "VOICE",
    icon: "mic",
    route: "/create/voice/narration",
    status: "COMING_SOON",
    order: 40,
  }),
  svc({
    key: "voice-tools",
    title: "Voice Tools",
    description: "Additional voice utilities and workflows.",
    category: "VOICE",
    icon: "mic",
    route: "/create/voice/tools",
    status: "COMING_SOON",
    order: 50,
  }),

  // —— MY WORK ——
  svc({
    key: "projects",
    title: "Projects",
    description: "Open and manage your projects.",
    category: "MY_WORK",
    icon: "folder",
    route: "/work/projects",
    status: "AVAILABLE",
    order: 10,
    workspace: "open-project",
    keywords: ["projects", "files", "work"],
  }),
  svc({
    key: "assets",
    title: "Assets",
    description: "Browse your media library.",
    category: "MY_WORK",
    icon: "library",
    route: "/work/assets",
    status: "AVAILABLE",
    order: 20,
    workspace: "asset-library",
  }),
  svc({
    key: "images",
    title: "Images",
    description: "Your generated and imported images.",
    category: "MY_WORK",
    icon: "image",
    route: "/work/images",
    status: "AVAILABLE",
    order: 30,
    workspace: "generated-images",
  }),
  svc({
    key: "videos",
    title: "Videos",
    description: "Your video productions.",
    category: "MY_WORK",
    icon: "video",
    route: "/work/videos",
    status: "AVAILABLE",
    order: 40,
    workspace: "generated-videos",
  }),
  svc({
    key: "designs",
    title: "Designs",
    description: "Saved design files.",
    category: "MY_WORK",
    icon: "layout",
    route: "/work/designs",
    status: "COMING_SOON",
    order: 50,
  }),
  svc({
    key: "audio-library",
    title: "Audio",
    description: "Your audio files.",
    category: "MY_WORK",
    icon: "audio",
    route: "/work/audio",
    status: "AVAILABLE",
    order: 60,
    workspace: "generated-audio",
  }),

  // —— ACCOUNT ——
  svc({
    key: "settings",
    title: "Settings",
    description: "Customer account and studio preferences.",
    category: "ACCOUNT",
    icon: "settings",
    route: "/account/settings",
    status: "AVAILABLE",
    order: 10,
    workspace: "settings",
  }),
  svc({
    key: "help",
    title: "Help",
    description: "Guides and support.",
    category: "ACCOUNT",
    icon: "help",
    route: "/account/help",
    status: "AVAILABLE",
    order: 20,
    workspace: "help",
  }),
];
