import type {
  AdminControlPlaneStore,
  AdminModelRecord,
  AdminProviderRecord,
  FeatureMappingRecord,
  TypedSetting,
} from "./types.js";

function now(): string {
  return new Date().toISOString();
}

export function createDefaultProviders(): AdminProviderRecord[] {
  const t = now();
  return [
    {
      id: "provider-ollama-local",
      name: "Ollama (Local)",
      type: "ollama",
      baseEndpoint: process.env.OLLAMA_HOST?.trim() || "http://127.0.0.1:11434",
      status: "active",
      enabled: true,
      healthStatus: "unchecked",
      metadata: { note: "Existing local Ollama integration — preserved" },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-fal",
      name: "fal.ai",
      type: "fal",
      baseEndpoint: "https://fal.run",
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: { note: "Credential configuration reserved for future stages" },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-replicate",
      name: "Replicate",
      type: "replicate",
      baseEndpoint: "https://api.replicate.com",
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-openai",
      name: "OpenAI",
      type: "openai",
      baseEndpoint: "https://api.openai.com",
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-google",
      name: "Google",
      type: "google",
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-anthropic",
      name: "Anthropic",
      type: "anthropic",
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-alibaba",
      name: "Alibaba Model Studio",
      type: "alibaba",
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-kwizera-local",
      name: "KWIZERA Local Runtime",
      type: "local",
      status: "active",
      enabled: true,
      healthStatus: "unchecked",
      metadata: { note: "Studio-local AiModelManager / deterministic renderers" },
      createdAt: t,
      updatedAt: t,
    },
  ];
}

export function createDefaultModels(): AdminModelRecord[] {
  const t = now();
  return [
    {
      id: "model-local-vision",
      name: "Local Vision (Ollama)",
      providerId: "provider-ollama-local",
      category: "VISION",
      capability: "vision-analysis",
      modelId: "local-vision",
      status: "active",
      priority: 100,
      inputType: "image",
      outputType: "json",
      currency: "USD",
      timeoutMs: 120_000,
      enabled: true,
      fallbackModelId: undefined,
      metadata: { source: "foundation-seed", notHardcodedInEngines: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "model-local-llm",
      name: "Local LLM (Ollama)",
      providerId: "provider-ollama-local",
      category: "LLM",
      capability: "chat",
      modelId: "local-llm",
      status: "active",
      priority: 100,
      inputType: "text",
      outputType: "text",
      currency: "USD",
      timeoutMs: 120_000,
      enabled: true,
      metadata: { source: "foundation-seed" },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "model-deterministic-video",
      name: "Deterministic Video Renderer",
      providerId: "provider-kwizera-local",
      category: "VIDEO",
      capability: "image-to-video",
      modelId: "kwizera-deterministic-renderer",
      status: "active",
      priority: 50,
      inputType: "image",
      outputType: "video",
      currency: "USD",
      timeoutMs: 600_000,
      enabled: true,
      metadata: { source: "foundation-seed", note: "Existing FFmpeg / production path" },
      createdAt: t,
      updatedAt: t,
    },
  ];
}

export function createDefaultFeatureMappings(): FeatureMappingRecord[] {
  const t = now();
  return [
    {
      id: "feat-vision-analysis",
      feature: "VISION_ANALYSIS",
      label: "Vision Analysis",
      description: "Product and media vision understanding",
      primaryModelId: "model-local-vision",
      fallbackModelId: "model-local-vision",
      providerId: "provider-ollama-local",
      enabled: true,
      priority: 100,
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-image-editing",
      feature: "IMAGE_EDITING",
      label: "Image Editing",
      description: "Context-aware image editing (provider TBD)",
      enabled: false,
      priority: 80,
      metadata: { pendingProvider: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-segmentation",
      feature: "SEGMENTATION",
      label: "Segmentation",
      description: "Mask / SAM-style segmentation (provider TBD)",
      enabled: false,
      priority: 80,
      metadata: { pendingProvider: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-upscale",
      feature: "IMAGE_UPSCALE",
      label: "Image Upscale",
      description: "Upscaling pipeline (provider TBD)",
      enabled: false,
      priority: 70,
      metadata: { pendingProvider: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-i2v",
      feature: "VIDEO_IMAGE_TO_VIDEO",
      label: "Image to Video",
      description: "Image-to-video generation",
      primaryModelId: "model-deterministic-video",
      fallbackModelId: "model-deterministic-video",
      providerId: "provider-kwizera-local",
      enabled: true,
      priority: 90,
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-music",
      feature: "MUSIC_GENERATION",
      label: "Music Generation",
      description: "Background music generation (provider TBD)",
      enabled: false,
      priority: 60,
      metadata: { pendingProvider: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-tts",
      feature: "TEXT_TO_SPEECH",
      label: "Text to Speech",
      description: "Voice / TTS (provider TBD)",
      enabled: false,
      priority: 60,
      metadata: { pendingProvider: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-stt",
      feature: "SPEECH_TO_TEXT",
      label: "Speech to Text",
      description: "STT transcription (provider TBD)",
      enabled: false,
      priority: 60,
      metadata: { pendingProvider: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-llm",
      feature: "LLM_CHAT",
      label: "LLM Chat",
      description: "Language model chat",
      primaryModelId: "model-local-llm",
      providerId: "provider-ollama-local",
      enabled: true,
      priority: 100,
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
  ];
}

export function createDefaultSettings(): TypedSetting[] {
  const t = now();
  return [
    {
      key: "general.appName",
      category: "general",
      label: "Application Name",
      description: "Display name for the studio",
      valueType: "string",
      value: "KWIZERA AI STUDIO",
      defaultValue: "KWIZERA AI STUDIO",
      updatedAt: t,
    },
    {
      key: "ai.defaultQuality",
      category: "ai",
      label: "Default Generation Quality",
      description: "Default quality preset for future generation jobs",
      valueType: "string",
      value: "standard",
      defaultValue: "standard",
      updatedAt: t,
    },
    {
      key: "limits.dailyAiBudget",
      category: "limits",
      label: "Daily AI Budget",
      description: "Maximum estimated AI spend per day (future billing)",
      valueType: "number",
      value: null,
      defaultValue: null,
      unit: "USD",
      min: 0,
      updatedAt: t,
    },
    {
      key: "limits.monthlyAiBudget",
      category: "limits",
      label: "Monthly AI Budget",
      description: "Maximum estimated AI spend per month (future billing)",
      valueType: "number",
      value: null,
      defaultValue: null,
      unit: "USD",
      min: 0,
      updatedAt: t,
    },
    {
      key: "limits.maxUserGenerationCost",
      category: "limits",
      label: "Max User Generation Cost",
      description: "Per-user generation cost ceiling (future)",
      valueType: "number",
      value: null,
      defaultValue: null,
      unit: "USD",
      min: 0,
      updatedAt: t,
    },
    {
      key: "limits.queueConcurrency",
      category: "performance",
      label: "Queue Concurrency",
      description: "Max concurrent generation jobs",
      valueType: "number",
      value: 2,
      defaultValue: 2,
      min: 1,
      max: 64,
      updatedAt: t,
    },
    {
      key: "video.defaultResolution",
      category: "video",
      label: "Default Video Resolution",
      description: "Default output resolution",
      valueType: "string",
      value: "1080p",
      defaultValue: "1080p",
      updatedAt: t,
    },
    {
      key: "security.adminAuthMode",
      category: "security",
      label: "Admin Auth Mode Hint",
      description: "Reflects KWIZERA_ADMIN_AUTH_MODE (runtime env is source of truth)",
      valueType: "string",
      value: process.env.KWIZERA_ADMIN_AUTH_MODE ?? "development-open",
      defaultValue: "development-open",
      updatedAt: t,
    },
    {
      key: "notifications.budgetAlertThreshold",
      category: "notifications",
      label: "Budget Alert Threshold",
      description: "Alert when estimated spend exceeds this fraction of budget",
      valueType: "number",
      value: 0.8,
      defaultValue: 0.8,
      min: 0,
      max: 1,
      updatedAt: t,
    },
    {
      key: "storage.retainExportsDays",
      category: "storage",
      label: "Retain Exports (Days)",
      description: "How long to retain export artifacts (policy only in Stage 1)",
      valueType: "number",
      value: 90,
      defaultValue: 90,
      min: 1,
      updatedAt: t,
    },
    {
      key: "audio.defaultVoiceEnabled",
      category: "audio",
      label: "Default Voice Enabled",
      description: "Whether TTS is enabled by default for new projects",
      valueType: "boolean",
      value: false,
      defaultValue: false,
      updatedAt: t,
    },
    {
      key: "rendering.preferGpu",
      category: "rendering",
      label: "Prefer GPU",
      description: "Prefer GPU for local rendering when available",
      valueType: "boolean",
      value: true,
      defaultValue: true,
      updatedAt: t,
    },
  ];
}

export function createEmptyStore(): AdminControlPlaneStore {
  const t = now();
  return {
    version: 1,
    providers: createDefaultProviders(),
    models: createDefaultModels(),
    featureMappings: createDefaultFeatureMappings(),
    settings: createDefaultSettings(),
    usage: [],
    updatedAt: t,
  };
}
