import type {
  AdminControlPlaneStore,
  AdminModelRecord,
  AdminProviderRecord,
  FeatureMappingRecord,
  TypedSetting,
} from "./types.js";

function now(): string {
  return new Date().toISOString();
}

export function createDefaultProviders(): AdminProviderRecord[] {
  const t = now();
  return [
    {
      id: "provider-ollama-local",
      name: "Ollama (Local)",
      type: "ollama",
      kind: "LOCAL" as const,
      baseEndpoint: process.env.OLLAMA_HOST?.trim() || "http://127.0.0.1:11434",
      status: "active",
      enabled: true,
      healthStatus: "unchecked",
      metadata: { note: "Existing local Ollama integration — preserved" },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-fal",
      name: "fal.ai",
      type: "fal",
      kind: "EXTERNAL_API" as const,
      baseEndpoint: "https://queue.fal.run",
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {
        note: "Phase 4 image-to-video (Wan-compatible). Enable + credential via Admin Providers.",
        phase: "phase4-online-i2v",
      },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-replicate",
      name: "Replicate",
      type: "replicate",
      kind: "EXTERNAL_API" as const,
      baseEndpoint: "https://api.replicate.com",
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-openai",
      name: "OpenAI",
      type: "openai",
      kind: "EXTERNAL_API" as const,
      baseEndpoint: "https://api.openai.com",
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-google",
      name: "Google",
      type: "google",
      kind: "EXTERNAL_API" as const,
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-anthropic",
      name: "Anthropic",
      type: "anthropic",
      kind: "EXTERNAL_API" as const,
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-alibaba",
      name: "Alibaba Model Studio",
      type: "alibaba",
      kind: "EXTERNAL_API" as const,
      status: "inactive",
      enabled: false,
      healthStatus: "unchecked",
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "provider-kwizera-local",
      name: "KWIZERA Local Runtime",
      type: "local",
      kind: "LOCAL" as const,
      status: "active",
      enabled: true,
      healthStatus: "unchecked",
      metadata: { note: "Studio-local AiModelManager / deterministic renderers" },
      createdAt: t,
      updatedAt: t,
    },
  ];
}

export function createDefaultModels(): AdminModelRecord[] {
  const t = now();
  return [
    {
      id: "model-local-vision",
      name: "Local Vision (Ollama)",
      providerId: "provider-ollama-local",
      category: "VISION",
      capability: "vision-analysis",
      modelId: "local-vision",
      status: "active",
      priority: 100,
      inputType: "image",
      outputType: "json",
      currency: "USD",
      timeoutMs: 120_000,
      enabled: true,
      fallbackModelId: undefined,
      metadata: { source: "foundation-seed", notHardcodedInEngines: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "model-local-llm",
      name: "Local LLM (Ollama)",
      providerId: "provider-ollama-local",
      category: "LLM",
      capability: "chat",
      modelId: "local-llm",
      status: "active",
      priority: 100,
      inputType: "text",
      outputType: "text",
      currency: "USD",
      timeoutMs: 120_000,
      enabled: true,
      metadata: { source: "foundation-seed" },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "model-deterministic-video",
      name: "Deterministic Video Renderer",
      providerId: "provider-kwizera-local",
      category: "VIDEO",
      capability: "image-to-video",
      modelId: "kwizera-deterministic-renderer",
      status: "active",
      priority: 50,
      inputType: "image",
      outputType: "video",
      currency: "USD",
      timeoutMs: 600_000,
      enabled: true,
      metadata: { source: "foundation-seed", note: "Existing FFmpeg / production path" },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "model-fal-wan-i2v",
      name: "fal.ai Wan 2.2 Image-to-Video",
      providerId: "provider-fal",
      category: "VIDEO",
      capability: "image-to-video",
      modelId: "fal-ai/wan/v2.2-a14b/image-to-video",
      status: "active",
      priority: 90,
      inputType: "image",
      outputType: "video",
      inputTypes: ["image", "text"],
      outputTypes: ["video"],
      currency: "USD",
      timeoutMs: 540_000,
      enabled: true,
      metadata: {
        source: "foundation-seed",
        phase: "phase4-online-i2v",
        note: "Admin-routed cinematic I2V via fal queue API (Wan 2.2 compatible)",
      },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "model-openai-gpt-4o-mini",
      name: "OpenAI GPT-4o mini",
      providerId: "provider-openai",
      category: "LLM",
      capability: "chat",
      modelId: "gpt-4o-mini",
      status: "active",
      priority: 80,
      inputType: "text",
      outputType: "text",
      inputTypes: ["text", "image"],
      outputTypes: ["text", "json"],
      currency: "USD",
      timeoutMs: 60_000,
      enabled: true,
      metadata: {
        source: "foundation-seed",
        phase: "phase2-online-vision",
        visionCapable: true,
        note: "Online chat + vision for Admin → credential → HTTPS (Phase 1 probe + Phase 2 VISION_ANALYSIS)",
      },
      createdAt: t,
      updatedAt: t,
    },
  ];
}

export function createDefaultFeatureMappings(): FeatureMappingRecord[] {
  const t = now();
  return [
    {
      id: "feat-vision-analysis",
      feature: "VISION_ANALYSIS",
      label: "Vision Analysis",
      description: "Product and media vision understanding via Admin-routed online vision (Phase 2)",
      primaryModelId: "model-openai-gpt-4o-mini",
      fallbackModelId: "model-local-vision",
      providerId: "provider-openai",
      enabled: true,
      priority: 100,
      metadata: {
        phase: "phase2-online-vision",
        phase2OnlineVision: true,
        note: "Primary: OpenAI vision when credentialed; fallback: local Ollama vision provider",
      },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-image-generation",
      feature: "IMAGE_GENERATION",
      label: "Image Generation",
      description: "Text-to-image / controlled generation (provider TBD — e.g. FLUX family later)",
      enabled: false,
      priority: 80,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-image-editing",
      feature: "IMAGE_EDITING",
      label: "Image Editing",
      description: "Context-aware image editing (provider TBD)",
      enabled: false,
      priority: 80,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-segmentation",
      feature: "SEGMENTATION",
      label: "Segmentation",
      description: "Mask / SAM-style segmentation (provider TBD). Alias capability: IMAGE_SEGMENTATION.",
      enabled: false,
      priority: 80,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-image-segmentation",
      feature: "IMAGE_SEGMENTATION",
      label: "Image Segmentation",
      description: "Product segmentation / masking catalog entry (provider TBD — SAM2 later)",
      enabled: false,
      priority: 80,
      metadata: { pendingProvider: true, comingSoon: true, aliasOf: "SEGMENTATION" },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-upscale",
      feature: "IMAGE_UPSCALE",
      label: "Image Upscale",
      description: "Upscaling pipeline (provider TBD — Real-ESRGAN later)",
      enabled: false,
      priority: 70,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-i2v",
      feature: "VIDEO_IMAGE_TO_VIDEO",
      label: "Image to Video",
      description:
        "Cinematic image-to-video for Product Marketing Video — Admin-routed online I2V (Phase 4). Exact Product Mode continues to use FFmpeg.",
      primaryModelId: "model-fal-wan-i2v",
      fallbackModelId: "model-deterministic-video",
      providerId: "provider-fal",
      enabled: true,
      priority: 90,
      metadata: {
        phase: "phase4-online-i2v",
        phase4OnlineI2v: true,
        note: "Primary: fal Wan I2V when credentialed; local deterministic is not a fake online substitute",
      },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-image-to-video",
      feature: "IMAGE_TO_VIDEO",
      label: "Image to Video (catalog)",
      description: "Catalog alias for VIDEO_IMAGE_TO_VIDEO",
      enabled: false,
      priority: 85,
      metadata: { aliasOf: "VIDEO_IMAGE_TO_VIDEO", phase4OnlineI2v: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-video-generation",
      feature: "VIDEO_GENERATION",
      label: "Video Generation",
      description: "General video generation catalog entry (provider TBD)",
      enabled: false,
      priority: 70,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-music",
      feature: "MUSIC_GENERATION",
      label: "Music Generation",
      description: "Background music generation (provider TBD)",
      enabled: false,
      priority: 60,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-tts",
      feature: "TEXT_TO_SPEECH",
      label: "Text to Speech",
      description: "Voice / TTS (provider TBD)",
      enabled: false,
      priority: 60,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-stt",
      feature: "SPEECH_TO_TEXT",
      label: "Speech to Text",
      description: "STT transcription (provider TBD)",
      enabled: false,
      priority: 60,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-audio-intelligence",
      feature: "AUDIO_INTELLIGENCE",
      label: "Audio Intelligence",
      description: "Audio understanding / analysis (provider TBD)",
      enabled: false,
      priority: 55,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-image-qa",
      feature: "IMAGE_QA",
      label: "Image QA",
      description: "Online visual QA for images (not connected yet)",
      enabled: false,
      priority: 55,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-video-qa",
      feature: "VIDEO_QA",
      label: "Video QA",
      description: "Online visual QA for video (not connected yet)",
      enabled: false,
      priority: 55,
      metadata: { pendingProvider: true, comingSoon: true },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-llm",
      feature: "LLM_CHAT",
      label: "LLM Chat",
      description: "Language model chat",
      primaryModelId: "model-local-llm",
      providerId: "provider-ollama-local",
      enabled: true,
      priority: 100,
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-llm-reasoning",
      feature: "LLM_REASONING",
      label: "LLM Reasoning",
      description: "Structured reasoning via mapped LLM",
      primaryModelId: "model-local-llm",
      providerId: "provider-ollama-local",
      enabled: true,
      priority: 90,
      metadata: {},
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-creative-reasoning",
      feature: "CREATIVE_REASONING",
      label: "Creative Reasoning",
      description: "Product Marketing Video Creative Director — Admin-routed online LLM (Phase 3)",
      primaryModelId: "model-openai-gpt-4o-mini",
      fallbackModelId: "model-local-llm",
      providerId: "provider-openai",
      enabled: true,
      priority: 95,
      metadata: {
        phase: "phase3-creative-director",
        phase3CreativeReasoning: true,
        note: "Primary: OpenAI when credentialed; local Ollama Creative Director remains cascade fallback",
      },
      createdAt: t,
      updatedAt: t,
    },
    {
      id: "feat-online-api-probe",
      feature: "ONLINE_API_PROBE",
      label: "Online API Probe",
      description: "Internal Phase 1 HTTPS probe via Admin-mapped OpenAI — not a customer feature",
      primaryModelId: "model-openai-gpt-4o-mini",
      providerId: "provider-openai",
      enabled: false,
      priority: 50,
      metadata: {
        phase: "phase1-online-runtime",
        pendingCredential: true,
        internalProbe: true,
        note: "Enable after configuring OpenAI credential; does not alter Product Marketing Video",
      },
      createdAt: t,
      updatedAt: t,
    },
  ];
}

export function createDefaultSettings(): TypedSetting[] {
  const t = now();
  return [
    {
      key: "general.appName",
      category: "general",
      label: "Application Name",
      description: "Display name for the studio",
      valueType: "string",
      value: "KWIZERA AI STUDIO",
      defaultValue: "KWIZERA AI STUDIO",
      updatedAt: t,
    },
    {
      key: "ai.defaultQuality",
      category: "ai",
      label: "Default Generation Quality",
      description: "Default quality preset for future generation jobs",
      valueType: "string",
      value: "standard",
      defaultValue: "standard",
      updatedAt: t,
    },
    {
      key: "limits.dailyAiBudget",
      category: "limits",
      label: "Daily AI Budget",
      description: "Maximum estimated AI spend per day (future billing)",
      valueType: "number",
      value: null,
      defaultValue: null,
      unit: "USD",
      min: 0,
      updatedAt: t,
    },
    {
      key: "limits.monthlyAiBudget",
      category: "limits",
      label: "Monthly AI Budget",
      description: "Maximum estimated AI spend per month (future billing)",
      valueType: "number",
      value: null,
      defaultValue: null,
      unit: "USD",
      min: 0,
      updatedAt: t,
    },
    {
      key: "limits.maxUserGenerationCost",
      category: "limits",
      label: "Max User Generation Cost",
      description: "Per-user generation cost ceiling (future)",
      valueType: "number",
      value: null,
      defaultValue: null,
      unit: "USD",
      min: 0,
      updatedAt: t,
    },
    {
      key: "limits.queueConcurrency",
      category: "performance",
      label: "Queue Concurrency",
      description: "Max concurrent generation jobs",
      valueType: "number",
      value: 2,
      defaultValue: 2,
      min: 1,
      max: 64,
      updatedAt: t,
    },
    {
      key: "video.defaultResolution",
      category: "video",
      label: "Default Video Resolution",
      description: "Default output resolution",
      valueType: "string",
      value: "1080p",
      defaultValue: "1080p",
      updatedAt: t,
    },
    {
      key: "security.adminAuthMode",
      category: "security",
      label: "Admin Auth Mode Hint",
      description: "Reflects KWIZERA_ADMIN_AUTH_MODE (runtime env is source of truth)",
      valueType: "string",
      value: process.env.KWIZERA_ADMIN_AUTH_MODE ?? "development-open",
      defaultValue: "development-open",
      updatedAt: t,
    },
    {
      key: "notifications.budgetAlertThreshold",
      category: "notifications",
      label: "Budget Alert Threshold",
      description: "Alert when estimated spend exceeds this fraction of budget",
      valueType: "number",
      value: 0.8,
      defaultValue: 0.8,
      min: 0,
      max: 1,
      updatedAt: t,
    },
    {
      key: "storage.retainExportsDays",
      category: "storage",
      label: "Retain Exports (Days)",
      description: "How long to retain export artifacts (policy only in Stage 1)",
      valueType: "number",
      value: 90,
      defaultValue: 90,
      min: 1,
      updatedAt: t,
    },
    {
      key: "audio.defaultVoiceEnabled",
      category: "audio",
      label: "Default Voice Enabled",
      description: "Whether TTS is enabled by default for new projects",
      valueType: "boolean",
      value: false,
      defaultValue: false,
      updatedAt: t,
    },
    {
      key: "ai.requestTimeoutMs",
      category: "ai",
      label: "AI Request Timeout",
      description: "Default timeout for AI provider requests (milliseconds)",
      valueType: "number",
      value: 120_000,
      defaultValue: 120_000,
      unit: "ms",
      min: 1_000,
      max: 1_800_000,
      updatedAt: t,
    },
    {
      key: "rendering.renderTimeoutMs",
      category: "rendering",
      label: "Render Timeout",
      description: "Default timeout for local rendering jobs (milliseconds)",
      valueType: "number",
      value: 600_000,
      defaultValue: 600_000,
      unit: "ms",
      min: 1_000,
      max: 3_600_000,
      updatedAt: t,
    },
    {
      key: "video.maxGenerationDurationSeconds",
      category: "video",
      label: "Max Generation Duration",
      description: "Maximum generated video duration in seconds (policy; not billed yet)",
      valueType: "number",
      value: 60,
      defaultValue: 60,
      unit: "s",
      min: 1,
      max: 600,
      updatedAt: t,
    },
    {
      key: "limits.maxCostPerGeneration",
      category: "limits",
      label: "Max Cost Per Generation",
      description: "Ceiling per generation when cost tracking is enabled (null = not configured)",
      valueType: "number",
      value: null,
      defaultValue: null,
      unit: "USD",
      min: 0,
      updatedAt: t,
    },
    {
      key: "rendering.preferGpu",
      category: "rendering",
      label: "Prefer GPU",
      description: "Prefer GPU for local rendering when available",
      valueType: "boolean",
      value: true,
      defaultValue: true,
      updatedAt: t,
    },
  ];
}

export function createEmptyStore(): AdminControlPlaneStore {
  const t = now();
  return {
    version: 2,
    providers: createDefaultProviders(),
    models: createDefaultModels(),
    featureMappings: createDefaultFeatureMappings(),
    settings: createDefaultSettings(),
    usage: [],
    updatedAt: t,
  };
}
