import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import type { CollaborationLock, CollaborationPresence, EnterpriseActivity, EnterpriseCollaborationStatus, EnterpriseMembership, EnterpriseNotification, EnterpriseOrganization, EnterprisePermission, EnterpriseRole, EnterpriseRoleId, EnterpriseTeam, EnterpriseUser, NotificationKind, SharedResource, SharedResourceKind } from "./types.js";

interface EnterpriseStore { users: EnterpriseUser[]; roles: EnterpriseRole[]; organizations: EnterpriseOrganization[]; teams: EnterpriseTeam[]; memberships: EnterpriseMembership[]; resources: SharedResource[]; locks: CollaborationLock[]; presence: CollaborationPresence[]; activities: EnterpriseActivity[]; notifications: EnterpriseNotification[]; }
const MAX_EVENTS = 2_000;
const BUILT_IN_ROLES: EnterpriseRole[] = [
  { id: "super-administrator", name: "Super Administrator", permissions: ["organization.manage", "team.manage", "member.manage", "role.manage", "project.share", "project.edit", "project.view", "resource.share", "workflow.run", "knowledge.share", "brand.manage", "audit.read", "notification.manage", "collaboration.lock"], builtIn: true },
  { id: "organization-administrator", name: "Organization Administrator", permissions: ["team.manage", "member.manage", "project.share", "project.edit", "project.view", "resource.share", "workflow.run", "knowledge.share", "brand.manage", "audit.read", "notification.manage", "collaboration.lock"], builtIn: true },
  { id: "project-manager", name: "Project Manager", permissions: ["project.share", "project.edit", "project.view", "resource.share", "workflow.run", "collaboration.lock"], builtIn: true },
  { id: "ai-trainer", name: "AI Trainer", permissions: ["project.view", "workflow.run", "knowledge.share"], builtIn: true },
  { id: "marketing-manager", name: "Marketing Manager", permissions: ["project.edit", "project.view", "resource.share", "workflow.run", "brand.manage"], builtIn: true },
  { id: "designer", name: "Designer", permissions: ["project.edit", "project.view", "resource.share", "collaboration.lock"], builtIn: true },
  { id: "video-editor", name: "Video Editor", permissions: ["project.edit", "project.view", "resource.share", "collaboration.lock"], builtIn: true },
  { id: "content-creator", name: "Content Creator", permissions: ["project.edit", "project.view", "workflow.run", "collaboration.lock"], builtIn: true },
  { id: "viewer", name: "Viewer", permissions: ["project.view"], builtIn: true },
];

/** Durable local organization control plane. It stores enterprise metadata and ACLs without replacing workspace project files. */
export class EnterpriseCollaborationManager {
  private root = ""; private statePath = ""; private initialized = false;
  private store: EnterpriseStore = { users: [], roles: structuredClone(BUILT_IN_ROLES), organizations: [], teams: [], memberships: [], resources: [], locks: [], presence: [], activities: [], notifications: [] };

  async initialize(storageRoot: string): Promise<void> { this.root = path.join(storageRoot, "enterprise-collaboration"); this.statePath = path.join(this.root, "state.json"); await fs.mkdir(this.root, { recursive: true }); this.store = await this.readStore(); this.recoverEphemeralState(); await this.bootstrapLocalOwner(); this.initialized = true; await this.persist(); }
  isInitialized(): boolean { return this.initialized; }
  listOrganizations(): EnterpriseOrganization[] { this.ensureReady(); return structuredClone(this.store.organizations); }
  listTeams(organizationId: string): EnterpriseTeam[] { this.ensureReady(); return this.store.teams.filter((team) => team.organizationId === organizationId).map((team) => structuredClone(team)); }
  listUsers(organizationId: string): EnterpriseUser[] { this.ensureReady(); const ids = new Set(this.store.memberships.filter((membership) => membership.organizationId === organizationId).map((membership) => membership.userId)); return this.store.users.filter((user) => ids.has(user.id)).map((user) => structuredClone(user)); }
  listActivities(organizationId: string): EnterpriseActivity[] { this.ensureReady(); return this.store.activities.filter((event) => event.organizationId === organizationId).map((event) => structuredClone(event)); }
  listNotifications(userId: string): EnterpriseNotification[] { this.ensureReady(); return this.store.notifications.filter((item) => item.userId === userId).map((item) => structuredClone(item)); }
  listPresence(projectId: string): CollaborationPresence[] { this.ensureReady(); this.recoverEphemeralState(); return this.store.presence.filter((item) => item.projectId === projectId).map((item) => structuredClone(item)); }
  getStatus(): EnterpriseCollaborationStatus { this.ensureReady(); this.recoverEphemeralState(); return { initialized: true, offlineFirst: true, users: this.store.users.filter((user) => user.status !== "removed").length, organizations: this.store.organizations.length, teams: this.store.teams.length, sharedResources: this.store.resources.length, activeLocks: this.store.locks.length, activePresence: this.store.presence.length, unreadNotifications: this.store.notifications.filter((item) => !item.readAt).length, auditEvents: this.store.activities.length }; }

  async createOrganization(actorId: string, input: { name: string; branding?: EnterpriseOrganization["branding"] }): Promise<EnterpriseOrganization> { this.ensureReady(); this.requireUser(actorId); if (!input.name.trim()) throw new Error("Organization name is required"); const now = new Date().toISOString(); const organization: EnterpriseOrganization = { id: randomUUID(), name: input.name.trim(), ownerId: actorId, departments: [], settings: { offlineFirst: true, externalSharingEnabled: false }, branding: { name: input.branding?.name?.trim() || input.name.trim(), logoPath: input.branding?.logoPath, accentColor: input.branding?.accentColor }, createdAt: now, updatedAt: now }; this.store.organizations.push(organization); this.store.memberships.push({ organizationId: organization.id, userId: actorId, roleId: "super-administrator", joinedAt: now }); await this.record(actorId, organization.id, "administration", "organization-created", organization.id, `Created organization ${organization.name}`); await this.persist(); return structuredClone(organization); }
  async addDepartment(actorId: string, organizationId: string, name: string): Promise<{ id: string; name: string }> { this.authorize(actorId, organizationId, "organization.manage"); if (!name.trim()) throw new Error("Department name is required"); const organization = this.requireOrganization(organizationId); if (organization.departments.some((department) => department.name.toLowerCase() === name.trim().toLowerCase())) throw new Error("Department already exists"); const department = { id: randomUUID(), name: name.trim() }; organization.departments.push(department); organization.updatedAt = new Date().toISOString(); await this.record(actorId, organizationId, "administration", "department-created", department.id, `Created department ${department.name}`); await this.persist(); return structuredClone(department); }
  async updateOrganization(actorId: string, organizationId: string, changes: { settings?: Record<string, boolean | string | number>; branding?: Partial<EnterpriseOrganization["branding"]> }): Promise<EnterpriseOrganization> { this.authorize(actorId, organizationId, "organization.manage"); const organization = this.requireOrganization(organizationId); if (changes.branding?.logoPath && (!changes.branding.logoPath.startsWith("/") || changes.branding.logoPath.includes(".."))) throw new Error("Organization logo path is invalid"); organization.settings = { ...organization.settings, ...changes.settings }; organization.branding = { ...organization.branding, ...changes.branding, name: changes.branding?.name?.trim() || organization.branding.name }; organization.updatedAt = new Date().toISOString(); await this.record(actorId, organizationId, "administration", "organization-updated", organizationId, "Updated organization settings or branding"); await this.persist(); return structuredClone(organization); }
  async createCustomRole(actorId: string, organizationId: string, input: { id: string; name: string; permissions: EnterprisePermission[] }): Promise<EnterpriseRole> { this.authorize(actorId, organizationId, "role.manage"); if (!/^[a-z0-9][a-z0-9.-]{2,100}$/i.test(input.id) || !input.name.trim() || !input.permissions.length || input.permissions.some((permission) => !BUILT_IN_ROLES.some((role) => role.permissions.includes(permission)))) throw new Error("Custom role is invalid"); if (this.store.roles.some((role) => role.id === input.id)) throw new Error("Role already exists"); const role: EnterpriseRole = { id: input.id, name: input.name.trim(), permissions: [...new Set(input.permissions)], builtIn: false, organizationId }; this.store.roles.push(role); await this.record(actorId, organizationId, "administration", "custom-role-created", role.id, `Created custom role ${role.name}`); await this.persist(); return structuredClone(role); }
  async createTeam(actorId: string, organizationId: string, name: string): Promise<EnterpriseTeam> { this.authorize(actorId, organizationId, "team.manage"); if (!name.trim()) throw new Error("Team name is required"); const now = new Date().toISOString(); const team: EnterpriseTeam = { id: randomUUID(), organizationId, name: name.trim(), memberIds: [], createdAt: now, updatedAt: now }; this.store.teams.push(team); await this.record(actorId, organizationId, "team", "team-created", team.id, `Created team ${team.name}`); await this.persist(); return structuredClone(team); }
  async inviteMember(actorId: string, organizationId: string, input: { displayName: string; email?: string; roleId: EnterpriseRoleId; departmentId?: string }): Promise<EnterpriseUser> { this.authorize(actorId, organizationId, "member.manage"); this.requireRole(input.roleId, organizationId); if (!input.displayName.trim()) throw new Error("Member display name is required"); if (input.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.email)) throw new Error("Member email is invalid"); const now = new Date().toISOString(); const user: EnterpriseUser = { id: randomUUID(), displayName: input.displayName.trim(), email: input.email?.toLowerCase(), status: "invited", createdAt: now, updatedAt: now }; this.store.users.push(user); this.store.memberships.push({ organizationId, userId: user.id, roleId: input.roleId, departmentId: input.departmentId, joinedAt: now }); await this.notify(user.id, "collaboration-request", "Organization invitation", `You were invited to join ${this.requireOrganization(organizationId).name}.`); await this.record(actorId, organizationId, "team", "member-invited", user.id, `Invited ${user.displayName}`); await this.persist(); return structuredClone(user); }
  async acceptInvitation(userId: string, organizationId: string): Promise<void> { const user = this.requireUser(userId); const membership = this.requireMembership(organizationId, userId); if (user.status !== "invited" || !membership) throw new Error("No pending organization invitation exists"); user.status = "active"; user.updatedAt = new Date().toISOString(); await this.record(userId, organizationId, "user", "invitation-accepted", userId, "Accepted organization invitation"); await this.persist(); }
  async removeMember(actorId: string, organizationId: string, userId: string): Promise<void> { this.authorize(actorId, organizationId, "member.manage"); const organization = this.requireOrganization(organizationId); if (organization.ownerId === userId) throw new Error("Transfer ownership before removing the organization owner"); this.requireMembership(organizationId, userId); this.store.memberships = this.store.memberships.filter((membership) => !(membership.organizationId === organizationId && membership.userId === userId)); this.store.teams.filter((team) => team.organizationId === organizationId).forEach((team) => { team.memberIds = team.memberIds.filter((memberId) => memberId !== userId); team.updatedAt = new Date().toISOString(); }); await this.record(actorId, organizationId, "team", "member-removed", userId, "Removed organization membership"); await this.persist(); }
  async assignRole(actorId: string, organizationId: string, userId: string, roleId: EnterpriseRoleId): Promise<void> { this.authorize(actorId, organizationId, "role.manage"); this.requireRole(roleId, organizationId); const membership = this.requireMembership(organizationId, userId); membership.roleId = roleId; await this.record(actorId, organizationId, "administration", "role-assigned", userId, `Assigned ${roleId}`); await this.persist(); }
  async addMemberToTeam(actorId: string, organizationId: string, teamId: string, userId: string): Promise<void> { this.authorize(actorId, organizationId, "team.manage"); this.requireMembership(organizationId, userId); const team = this.requireTeam(teamId, organizationId); if (!team.memberIds.includes(userId)) team.memberIds.push(userId); team.updatedAt = new Date().toISOString(); await this.record(actorId, organizationId, "team", "team-member-added", userId, `Added member to ${team.name}`); await this.persist(); }
  async transferOwnership(actorId: string, organizationId: string, nextOwnerId: string): Promise<void> { const organization = this.requireOrganization(organizationId); if (organization.ownerId !== actorId) throw new Error("Only the organization owner can transfer ownership"); this.requireMembership(organizationId, nextOwnerId); organization.ownerId = nextOwnerId; organization.updatedAt = new Date().toISOString(); await this.record(actorId, organizationId, "administration", "ownership-transferred", nextOwnerId, "Transferred organization ownership"); await this.persist(); }
  async shareResource(actorId: string, organizationId: string, input: { kind: SharedResourceKind; resourceId: string; teamIds?: string[]; userIds?: string[] }): Promise<SharedResource> { this.authorize(actorId, organizationId, input.kind === "project" ? "project.share" : "resource.share"); if (!input.resourceId.trim()) throw new Error("Shared resource id is required"); const now = new Date().toISOString(); const resource: SharedResource = { id: randomUUID(), organizationId, kind: input.kind, resourceId: input.resourceId, teamIds: [...new Set(input.teamIds ?? [])], userIds: [...new Set(input.userIds ?? [])], version: 1, updatedAt: now }; resource.teamIds.forEach((teamId) => this.requireTeam(teamId, organizationId)); resource.userIds.forEach((userId) => this.requireMembership(organizationId, userId)); this.store.resources.push(resource); await this.record(actorId, organizationId, "project", "resource-shared", resource.resourceId, `Shared ${resource.kind}`); await this.persist(); return structuredClone(resource); }
  async acquireProjectLock(actorId: string, organizationId: string, projectId: string, expectedVersion: number, ttlMs = 120_000): Promise<CollaborationLock> { this.authorize(actorId, organizationId, "collaboration.lock"); if (!Number.isInteger(expectedVersion) || expectedVersion < 1 || !Number.isInteger(ttlMs) || ttlMs < 10_000 || ttlMs > 600_000) throw new Error("Project lock request is invalid"); this.recoverEphemeralState(); const current = this.store.locks.find((lock) => lock.projectId === projectId); if (current && current.userId !== actorId) throw new Error("Project is locked by another member"); if (current && current.version !== expectedVersion) throw new Error("Project version conflict requires review"); const now = new Date(); const lock: CollaborationLock = { projectId, userId: actorId, version: expectedVersion, acquiredAt: now.toISOString(), expiresAt: new Date(now.getTime() + ttlMs).toISOString() }; this.store.locks = this.store.locks.filter((item) => item.projectId !== projectId); this.store.locks.push(lock); await this.record(actorId, organizationId, "project", "project-locked", projectId, `Locked project version ${expectedVersion}`); await this.persist(); return structuredClone(lock); }
  async releaseProjectLock(actorId: string, organizationId: string, projectId: string, nextVersion: number): Promise<void> { this.authorize(actorId, organizationId, "collaboration.lock"); const lock = this.store.locks.find((item) => item.projectId === projectId); if (!lock || lock.userId !== actorId) throw new Error("Only the lock holder can release this project"); if (!Number.isInteger(nextVersion) || nextVersion < lock.version) throw new Error("Project version is invalid"); this.store.locks = this.store.locks.filter((item) => item.projectId !== projectId); const resource = this.store.resources.find((item) => item.organizationId === organizationId && item.kind === "project" && item.resourceId === projectId); if (resource) { resource.version = nextVersion; resource.updatedAt = new Date().toISOString(); } await this.record(actorId, organizationId, "project", "project-unlocked", projectId, `Released project at version ${nextVersion}`); await this.persist(); }
  async updatePresence(actorId: string, organizationId: string, projectId: string): Promise<void> { this.authorize(actorId, organizationId, "project.view"); this.recoverEphemeralState(); this.store.presence = this.store.presence.filter((item) => !(item.projectId === projectId && item.userId === actorId)); this.store.presence.push({ projectId, userId: actorId, seenAt: new Date().toISOString() }); await this.persist(); }
  async createNotification(actorId: string, organizationId: string, userId: string, kind: NotificationKind, title: string, detail: string): Promise<EnterpriseNotification> { this.authorize(actorId, organizationId, "notification.manage"); this.requireMembership(organizationId, userId); const notification = await this.notify(userId, kind, title, detail); await this.record(actorId, organizationId, "administration", "notification-created", userId, title); await this.persist(); return structuredClone(notification); }
  async markNotificationRead(userId: string, notificationId: string): Promise<void> { const notification = this.store.notifications.find((item) => item.id === notificationId && item.userId === userId); if (!notification) throw new Error("Notification not found"); notification.readAt = new Date().toISOString(); await this.persist(); }
  hasPermission(userId: string, organizationId: string, permission: EnterprisePermission): boolean { this.ensureReady(); const membership = this.store.memberships.find((item) => item.organizationId === organizationId && item.userId === userId); const role = membership && this.store.roles.find((item) => item.id === membership.roleId); return Boolean(role?.permissions.includes(permission)); }

  private async bootstrapLocalOwner(): Promise<void> { if (this.store.organizations.length) return; const now = new Date().toISOString(); const owner: EnterpriseUser = { id: "local-owner", displayName: "Local Owner", status: "active", createdAt: now, updatedAt: now }; const organization: EnterpriseOrganization = { id: "local-organization", name: "Local Workspace", ownerId: owner.id, departments: [], settings: { offlineFirst: true, externalSharingEnabled: false }, branding: { name: "KWIZERA AI STUDIO" }, createdAt: now, updatedAt: now }; this.store.users.push(owner); this.store.organizations.push(organization); this.store.memberships.push({ organizationId: organization.id, userId: owner.id, roleId: "super-administrator", joinedAt: now }); await this.record(owner.id, organization.id, "administration", "local-workspace-bootstrap", organization.id, "Initialized single-user local organization"); }
  private authorize(userId: string, organizationId: string, permission: EnterprisePermission): void { this.ensureReady(); if (!this.hasPermission(userId, organizationId, permission)) throw new Error(`Permission denied: ${permission}`); }
  private requireUser(userId: string): EnterpriseUser { const user = this.store.users.find((item) => item.id === userId && item.status !== "removed"); if (!user) throw new Error("Enterprise user not found"); return user; }
  private requireOrganization(organizationId: string): EnterpriseOrganization { const organization = this.store.organizations.find((item) => item.id === organizationId); if (!organization) throw new Error("Organization not found"); return organization; }
  private requireTeam(teamId: string, organizationId: string): EnterpriseTeam { const team = this.store.teams.find((item) => item.id === teamId && item.organizationId === organizationId); if (!team) throw new Error("Team not found"); return team; }
  private requireMembership(organizationId: string, userId: string): EnterpriseMembership { this.requireUser(userId); const membership = this.store.memberships.find((item) => item.organizationId === organizationId && item.userId === userId); if (!membership) throw new Error("Organization membership not found"); return membership; }
  private requireRole(roleId: EnterpriseRoleId, organizationId?: string): EnterpriseRole { const role = this.store.roles.find((item) => item.id === roleId); if (!role || (organizationId && !role.builtIn && role.organizationId !== organizationId)) throw new Error("Role not found for this organization"); return role; }
  private async record(actorId: string, organizationId: string, category: EnterpriseActivity["category"], action: string, targetId: string | undefined, detail: string): Promise<void> { this.store.activities.unshift({ id: randomUUID(), at: new Date().toISOString(), actorId, organizationId, category, action, targetId, detail }); this.store.activities.splice(MAX_EVENTS); }
  private async notify(userId: string, kind: NotificationKind, title: string, detail: string): Promise<EnterpriseNotification> { const notification: EnterpriseNotification = { id: randomUUID(), userId, kind, title: title.trim(), detail: detail.trim(), createdAt: new Date().toISOString() }; if (!notification.title || !notification.detail) throw new Error("Notification title and detail are required"); this.store.notifications.unshift(notification); this.store.notifications.splice(MAX_EVENTS); return notification; }
  private recoverEphemeralState(): void { const now = Date.now(); this.store.locks = this.store.locks.filter((item) => new Date(item.expiresAt).getTime() > now); this.store.presence = this.store.presence.filter((item) => new Date(item.seenAt).getTime() > now - 120_000); }
  private async readStore(): Promise<EnterpriseStore> { try { const saved = JSON.parse(await fs.readFile(this.statePath, "utf8")) as Partial<EnterpriseStore>; return { users: saved.users ?? [], roles: saved.roles?.length ? saved.roles : structuredClone(BUILT_IN_ROLES), organizations: saved.organizations ?? [], teams: saved.teams ?? [], memberships: saved.memberships ?? [], resources: saved.resources ?? [], locks: saved.locks ?? [], presence: saved.presence ?? [], activities: saved.activities ?? [], notifications: saved.notifications ?? [] }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return structuredClone(this.store); throw error; } }
  private async persist(): Promise<void> { const temporary = `${this.statePath}.${randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(this.store, null, 2)}\n`, "utf8"); await fs.rename(temporary, this.statePath); }
  private ensureReady(): void { if (!this.initialized) throw new Error("Enterprise Collaboration Manager is not initialized"); }
}