import {
  VideoGenerationAccessPermission,
  VideoGenerationCategory,
  VideoGenerationModuleStatus,
  VideoGenerationSource,
  GenerationAssetType,
  GenerationBlueprintStage,
} from "./types.js";

export interface PreparedVideoGenerationModule {
  category: VideoGenerationCategory;
  moduleId: string;
  moduleName: string;
  subdirectory: string;
  dependencies: string[];
  defaultSource: VideoGenerationSource;
  accessPermissions: VideoGenerationAccessPermission[];
}

export const DEFAULT_MODULE_STATUS = VideoGenerationModuleStatus.Prepared;

/** Foundation slots for future AI Video Generation modules — prepared, not implemented */
export const PREPARED_VIDEO_GENERATION_MODULES: PreparedVideoGenerationModule[] = [
  {
    category: VideoGenerationCategory.StoryGeneration,
    moduleId: "story-generation-engine",
    moduleName: "Story Generation Engine",
    subdirectory: "story",
    dependencies: ["video-generation-engine", "knowledge-engine", "video-intelligence-engine"],
    defaultSource: VideoGenerationSource.Script,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write],
  },
  {
    category: VideoGenerationCategory.SceneGeneration,
    moduleId: "scene-generation-engine",
    moduleName: "Scene Generation Engine",
    subdirectory: "scenes",
    dependencies: ["video-generation-engine", "story-generation-engine", "video-intelligence-engine"],
    defaultSource: VideoGenerationSource.Storyboard,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write],
  },
  {
    category: VideoGenerationCategory.ShotGeneration,
    moduleId: "shot-generation-engine",
    moduleName: "Shot Generation Engine",
    subdirectory: "shots",
    dependencies: ["video-generation-engine", "scene-generation-engine"],
    defaultSource: VideoGenerationSource.System,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write],
  },
  {
    category: VideoGenerationCategory.CameraPlanning,
    moduleId: "camera-planning-generation-engine",
    moduleName: "Camera Planning Generation Engine",
    subdirectory: "camera-plans",
    dependencies: ["video-generation-engine", "video-intelligence-engine"],
    defaultSource: VideoGenerationSource.ProductionPlan,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write],
  },
  {
    category: VideoGenerationCategory.MotionPlanning,
    moduleId: "motion-planning-generation-engine",
    moduleName: "Motion Planning Generation Engine",
    subdirectory: "motion-plans",
    dependencies: ["video-generation-engine", "camera-planning-generation-engine"],
    defaultSource: VideoGenerationSource.ProductionPlan,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write],
  },
  {
    category: VideoGenerationCategory.AnimationPlanning,
    moduleId: "animation-planning-generation-engine",
    moduleName: "Animation Planning Generation Engine",
    subdirectory: "animation",
    dependencies: ["video-generation-engine", "motion-planning-generation-engine"],
    defaultSource: VideoGenerationSource.System,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write],
  },
  {
    category: VideoGenerationCategory.VisualEffectsPlanning,
    moduleId: "visual-effects-planning-generation-engine",
    moduleName: "Visual Effects Planning Generation Engine",
    subdirectory: "effects",
    dependencies: ["video-generation-engine", "animation-planning-generation-engine"],
    defaultSource: VideoGenerationSource.System,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write],
  },
  {
    category: VideoGenerationCategory.AudioSynchronization,
    moduleId: "audio-sync-generation-engine",
    moduleName: "Audio Synchronization Generation Engine",
    subdirectory: "audio-sync",
    dependencies: ["video-generation-engine", "video-intelligence-engine"],
    defaultSource: VideoGenerationSource.ProductionPlan,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write],
  },
  {
    category: VideoGenerationCategory.MarketingVideoPlanning,
    moduleId: "marketing-video-generation-engine",
    moduleName: "Marketing Video Generation Engine",
    subdirectory: "marketing-video",
    dependencies: ["video-generation-engine", "audio-sync-generation-engine"],
    defaultSource: VideoGenerationSource.ProductionPlan,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write, VideoGenerationAccessPermission.Validate],
  },
  {
    category: VideoGenerationCategory.VideoProductionPlanning,
    moduleId: "video-production-generation-engine",
    moduleName: "Video Production Generation Engine",
    subdirectory: "production",
    dependencies: ["video-generation-engine", "marketing-video-generation-engine"],
    defaultSource: VideoGenerationSource.ProductionPlan,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write, VideoGenerationAccessPermission.Validate],
  },
  {
    category: VideoGenerationCategory.RenderingPlanning,
    moduleId: "rendering-planning-generation-engine",
    moduleName: "Rendering Planning Generation Engine",
    subdirectory: "rendering",
    dependencies: ["video-generation-engine", "video-production-generation-engine"],
    defaultSource: VideoGenerationSource.ProductionPlan,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write, VideoGenerationAccessPermission.Validate],
  },
  {
    category: VideoGenerationCategory.VideoQualityValidation,
    moduleId: "video-quality-validation-engine",
    moduleName: "Video Quality Validation Engine",
    subdirectory: "quality-validation",
    dependencies: ["video-generation-engine", "rendering-planning-generation-engine"],
    defaultSource: VideoGenerationSource.ProductionPlan,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write, VideoGenerationAccessPermission.Validate],
  },
  {
    category: VideoGenerationCategory.VideoGenerationOptimization,
    moduleId: "video-generation-optimization-engine",
    moduleName: "Video Generation Optimization Engine",
    subdirectory: "optimization",
    dependencies: ["video-generation-engine", "video-quality-validation-engine"],
    defaultSource: VideoGenerationSource.ProductionPlan,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write, VideoGenerationAccessPermission.Validate],
  },
  {
    category: VideoGenerationCategory.ExportPlanning,
    moduleId: "export-planning-generation-engine",
    moduleName: "Export Planning Generation Engine",
    subdirectory: "export",
    dependencies: ["video-generation-engine", "video-generation-optimization-engine"],
    defaultSource: VideoGenerationSource.ProductionPlan,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Write, VideoGenerationAccessPermission.Validate],
  },
  {
    category: VideoGenerationCategory.BatchGeneration,
    moduleId: "batch-generation-engine",
    moduleName: "Batch Video Generation Engine",
    subdirectory: "batch",
    dependencies: ["video-generation-engine"],
    defaultSource: VideoGenerationSource.System,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Admin],
  },
  {
    category: VideoGenerationCategory.DistributedGeneration,
    moduleId: "distributed-generation-engine",
    moduleName: "Distributed Generation Engine",
    subdirectory: "distributed",
    dependencies: ["video-generation-engine", "batch-generation-engine"],
    defaultSource: VideoGenerationSource.System,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Admin],
  },
  {
    category: VideoGenerationCategory.CloudGeneration,
    moduleId: "cloud-generation-preparation-engine",
    moduleName: "Cloud Generation Preparation Engine",
    subdirectory: "cloud",
    dependencies: ["video-generation-engine", "distributed-generation-engine"],
    defaultSource: VideoGenerationSource.System,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Admin],
  },
  {
    category: VideoGenerationCategory.GenerationHealthMonitoring,
    moduleId: "generation-health-monitor",
    moduleName: "Generation Health Monitor",
    subdirectory: "health",
    dependencies: ["video-generation-engine", "video-generation-optimization-engine"],
    defaultSource: VideoGenerationSource.System,
    accessPermissions: [VideoGenerationAccessPermission.Read, VideoGenerationAccessPermission.Validate],
  },
];

export const SUPPORTED_GENERATION_ASSET_TYPES: GenerationAssetType[] = [
  GenerationAssetType.Storyboard,
  GenerationAssetType.Script,
  GenerationAssetType.Scene,
  GenerationAssetType.Timeline,
  GenerationAssetType.CameraPlan,
  GenerationAssetType.MotionPlan,
  GenerationAssetType.Character,
  GenerationAssetType.Background,
  GenerationAssetType.Image,
  GenerationAssetType.Audio,
  GenerationAssetType.Voice,
  GenerationAssetType.Music,
  GenerationAssetType.Effect,
  GenerationAssetType.Transition,
  GenerationAssetType.Template,
  GenerationAssetType.ExportProfile,
];

export const GENERATION_BLUEPRINT_STAGES: GenerationBlueprintStage[] = [
  GenerationBlueprintStage.StoryGeneration,
  GenerationBlueprintStage.SceneGeneration,
  GenerationBlueprintStage.ShotGeneration,
  GenerationBlueprintStage.CameraPlanning,
  GenerationBlueprintStage.MotionPlanning,
  GenerationBlueprintStage.AnimationPlanning,
  GenerationBlueprintStage.VisualEffectsPlanning,
  GenerationBlueprintStage.AudioSynchronization,
  GenerationBlueprintStage.MarketingVideoPlanning,
  GenerationBlueprintStage.VideoProductionPlanning,
  GenerationBlueprintStage.RenderingPlanning,
  GenerationBlueprintStage.VideoQualityValidation,
  GenerationBlueprintStage.VideoGenerationOptimization,
  GenerationBlueprintStage.ExportPlanning,
];

export const SUPPORTED_VIDEO_GENERATION_SOURCES: VideoGenerationSource[] = [
  VideoGenerationSource.MemoryEngine,
  VideoGenerationSource.KnowledgeEngine,
  VideoGenerationSource.ProductIntelligenceEngine,
  VideoGenerationSource.ImageIntelligenceEngine,
  VideoGenerationSource.VideoIntelligenceEngine,
  VideoGenerationSource.ProductionPlan,
  VideoGenerationSource.Storyboard,
  VideoGenerationSource.Script,
  VideoGenerationSource.UserInput,
  VideoGenerationSource.System,
  VideoGenerationSource.Manual,
];
