import { useEffect, useState } from "react";
import { AudioLines, CheckCircle2, ChevronRight, CircleDot, FileText, Heart, Image, LayoutGrid, List, Palette, Search, Sparkles, SwatchBook, Type, Video, X } from "lucide-react";
import { BrandCenterManager } from "./brand-store";
import type { BrandAsset, BrandAssetKind, BrandCenterState, BrandTab } from "./types";
import "./brand-center.css";

const manager = new BrandCenterManager();
const tabs: Array<{ id: BrandTab; label: string }> = [{ id: "overview", label: "Brand dashboard" }, { id: "assets", label: "Asset library" }, { id: "identity", label: "Identity" }, { id: "templates", label: "Templates" }, { id: "guidelines", label: "Guidelines" }];
const kindIcon = { logo: Sparkles, icon: CircleDot, template: LayoutGrid, image: Image, video: Video, audio: AudioLines, document: FileText, graphic: Palette, background: SwatchBook, texture: SwatchBook } as const;

export function BrandCenter() {
  const [state, setState] = useState<BrandCenterState>(() => manager.load());
  const [query, setQuery] = useState("");
  const [kind, setKind] = useState<BrandAssetKind | "all" | "favorites" | "recent">("all");
  const [selected, setSelected] = useState<BrandAsset | null>(null);
  useEffect(() => { manager.save(state); }, [state]);
  const brand = state.profiles.find((profile) => profile.id === state.activeBrandId) ?? state.profiles[0];
  const visible = state.assets.filter((asset) => asset.brandId === brand.id && (kind === "all" || kind === "favorites" && state.favorites.includes(asset.id) || kind === "recent" && state.recent.includes(asset.id) || asset.kind === kind) && (!query || `${asset.name} ${asset.category} ${asset.kind} ${asset.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())));
  const choose = (asset: BrandAsset) => { setSelected(asset); setState((current) => manager.selectAsset(current, asset.id)); };
  return <div className="brand-center"><aside className="brand-sidebar"><div className="brand-side-title"><span>BRAND CENTER</span><h2>Identity library</h2></div><div className="brand-select"><span>ACTIVE BRAND</span><select value={brand.id} onChange={(event) => setState((current) => ({ ...current, activeBrandId: event.target.value }))}>{state.profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></div><nav>{tabs.map((tab) => <button key={tab.id} className={state.tab === tab.id ? "active" : ""} onClick={() => setState((current) => ({ ...current, tab: tab.id }))}>{tab.label}<ChevronRight size={14} /></button>)}</nav><div className="brand-status"><CheckCircle2 size={15} /><div><b>{brand.status === "active" ? "Active brand" : "Draft brand"}</b><small>Local interface library</small></div></div></aside><section className="brand-main"><header className="brand-heading"><div><span>BUSINESS IDENTITY</span><h1>{tabs.find((tab) => tab.id === state.tab)?.label}</h1><p>{brand.name} · {brand.category} · updated today</p></div><div className="brand-profile-chip"><span>KA</span><div><b>{brand.owner}</b><small>{brand.status}</small></div></div></header>{state.tab === "overview" && <Overview brand={brand} assets={state.assets.filter((asset) => asset.brandId === brand.id)} onTab={(tab) => setState((current) => ({ ...current, tab }))} />}{state.tab === "assets" && <AssetLibrary state={state} visible={visible} query={query} kind={kind} selected={selected} onQuery={setQuery} onKind={setKind} onChoose={choose} onFavorite={(id) => setState((current) => manager.toggleFavorite(current, id))} onView={(view) => setState((current) => ({ ...current, view }))} />}{state.tab === "identity" && <Identity brand={brand} />}{state.tab === "templates" && <AssetLibrary state={state} visible={visible.filter((asset) => asset.kind === "template")} query={query} kind={kind} selected={selected} onQuery={setQuery} onKind={setKind} onChoose={choose} onFavorite={(id) => setState((current) => manager.toggleFavorite(current, id))} onView={(view) => setState((current) => ({ ...current, view }))} templates />}{state.tab === "guidelines" && <Guidelines brand={brand} />}</section></div>;
}
function Overview({ brand, assets, onTab }: { brand: BrandCenterState["profiles"][number]; assets: BrandAsset[]; onTab: (tab: BrandTab) => void }) { return <div className="brand-overview"><section className="brand-hero"><div><span>ACTIVE BRAND</span><h2>{brand.name}</h2><p>{brand.description}</p><button onClick={() => onTab("identity")}>View identity <ChevronRight size={14} /></button></div><div className="brand-mark-preview"><Sparkles size={34} /></div></section><div className="brand-summary"><Summary value={assets.filter((asset) => asset.kind === "logo").length} label="Logo variations" /><Summary value={brand.colors.length} label="Color tokens" /><Summary value={assets.filter((asset) => asset.kind === "template").length} label="Templates" /><Summary value={assets.length} label="Library assets" /></div><section className="overview-grid"><Panel title="Recent changes"><Change title="Brand Center initialized" detail="Local identity profile and resource library prepared." /><Change title="Typography system prepared" detail={`${brand.typography.heading} heading and ${brand.typography.body} body styles.`} /><Change title="Guideline workspace available" detail="Usage, color, voice, and visual identity rules are ready for future editing." /></Panel><Panel title="Asset summary"><div className="asset-summary">{["logo", "icon", "template", "document", "background", "texture"].map((type) => <button key={type} onClick={() => onTab(type === "template" ? "templates" : "assets")}><span>{type}</span><b>{assets.filter((asset) => asset.kind === type).length}</b><ChevronRight size={13} /></button>)}</div></Panel></section></div>; }
function AssetLibrary({ state, visible, query, kind, selected, onQuery, onKind, onChoose, onFavorite, onView, templates = false }: { state: BrandCenterState; visible: BrandAsset[]; query: string; kind: BrandAssetKind | "all" | "favorites" | "recent"; selected: BrandAsset | null; onQuery: (value: string) => void; onKind: (value: BrandAssetKind | "all" | "favorites" | "recent") => void; onChoose: (asset: BrandAsset) => void; onFavorite: (id: string) => void; onView: (view: BrandCenterState["view"]) => void; templates?: boolean }) { return <div className="brand-library"><div className="brand-library-head"><div><span>{templates ? "TEMPLATE LIBRARY" : "CREATIVE ASSET LIBRARY"}</span><h2>{templates ? "Reusable compositions" : "Brand resources"}</h2></div><div className="brand-view"><button className={state.view === "grid" ? "active" : ""} onClick={() => onView("grid")}><LayoutGrid size={15} /></button><button className={state.view === "list" ? "active" : ""} onClick={() => onView("list")}><List size={15} /></button></div></div><div className="brand-controls"><label><Search size={15} /><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search assets, categories, tags..." /></label><select value={kind} onChange={(event) => onKind(event.target.value as typeof kind)}><option value="all">All resources</option><option value="logo">Logos</option><option value="icon">Icons</option><option value="template">Templates</option><option value="image">Images</option><option value="video">Videos</option><option value="audio">Audio</option><option value="document">Documents</option><option value="background">Backgrounds</option><option value="texture">Textures</option><option value="favorites">Favorites</option><option value="recent">Recent</option></select></div><div className={`brand-assets ${state.view}`}>{visible.map((asset) => <AssetCard key={asset.id} asset={asset} selected={selected?.id === asset.id} onChoose={onChoose} onFavorite={onFavorite} />)}{!visible.length && <div className="brand-empty"><SwatchBook size={26} /><b>No matching assets</b><p>Try another category or broaden the search.</p></div>}</div>{selected && <aside className="brand-metadata"><button onClick={() => onChoose(selected)} title="Selected asset"><X size={14} /></button><span>ASSET METADATA</span><h3>{selected.name}</h3><Metadata label="Type" value={selected.kind} /><Metadata label="Category" value={selected.category} /><Metadata label="Version" value={selected.version} /><Metadata label="Status" value="Prepared" /><p>{selected.detail}</p></aside>}</div>; }
function AssetCard({ asset, selected, onChoose, onFavorite }: { asset: BrandAsset; selected: boolean; onChoose: (asset: BrandAsset) => void; onFavorite: (id: string) => void }) { const Icon = kindIcon[asset.kind]; return <article className={selected ? "selected" : ""} onClick={() => onChoose(asset)}><div className={`asset-art ${asset.kind}`}><Icon size={29} /><button onClick={(event) => { event.stopPropagation(); onFavorite(asset.id); }}><Heart size={14} fill={asset.favorite ? "currentColor" : "none"} /></button></div><b>{asset.name}</b><small>{asset.category} · {asset.version}</small></article>; }
function Identity({ brand }: { brand: BrandCenterState["profiles"][number] }) { return <div className="identity-grid"><Panel title="Brand profile"><Metadata label="Description" value={brand.description} /><Metadata label="Category" value={brand.category} /><Metadata label="Owner" value={brand.owner} /><Metadata label="Status" value={brand.status} /></Panel><Panel title="Color palette"><div className="color-palette">{brand.colors.map((color) => <div key={color.name}><i style={{ background: color.value }} /><span><b>{color.name}</b><small>{color.role} · {color.value}</small></span></div>)}</div></Panel><Panel title="Typography"><div className="type-specimen"><span>Heading</span><strong style={{ fontFamily: brand.typography.heading }}>KWIZERA / Brand clarity</strong><span>Body</span><p style={{ fontFamily: brand.typography.body }}>A reusable type system prepared for consistent product, campaign, and studio communication.</p><small>Scale: {brand.typography.scale}</small></div></Panel><Panel title="Icon library"><div className="icon-row">{[Sparkles, Palette, CircleDot, SwatchBook, Type].map((Icon, index) => <span key={index}><Icon size={19} /></span>)}</div></Panel></div>; }
function Guidelines({ brand }: { brand: BrandCenterState["profiles"][number] }) { return <div className="guideline-grid"><Guideline title="Logo usage" items={["Keep clear space around every approved mark.", "Use approved variants only.", "Do not distort or recolor logo proportions."]} /><Guideline title="Color rules" items={brand.colors.map((color) => `${color.name}: ${color.role.toLowerCase()} use`)} /><Guideline title="Typography rules" items={[`${brand.typography.heading} for headings`, `${brand.typography.body} for body content`, `Scale ${brand.typography.scale}`]} /><Guideline title="Brand voice" items={[brand.voice, "Use direct, helpful language.", "Keep technical explanations clear and grounded."]} /><Guideline title="Visual identity" items={["Use confident hierarchy and deliberate space.", "Prioritize source assets and legible contrast.", "Keep composition focused."]} /><Guideline title="Marketing style" items={["Lead with product value and evidence.", "Maintain consistent visual system across channels.", "Future campaign automation is outside this workspace."]} /></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="brand-panel"><header><span>BRAND RESOURCE</span><h3>{title}</h3></header>{children}</section>; }
function Summary({ value, label }: { value: number; label: string }) { return <article><b>{value}</b><span>{label}</span></article>; }
function Change({ title, detail }: { title: string; detail: string }) { return <div className="brand-change"><i /><div><b>{title}</b><p>{detail}</p></div><small>Now</small></div>; }
function Metadata({ label, value }: { label: string; value: string }) { return <div className="brand-meta-row"><span>{label}</span><b>{value}</b></div>; }
function Guideline({ title, items }: { title: string; items: string[] }) { return <section><header><span>GUIDELINE</span><h3>{title}</h3></header>{items.map((item) => <p key={item}><i />{item}</p>)}</section>; }