import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import type { AiCoreManager } from "../core/ai-core-manager.js";
import type { CreativeWorkspaceManager } from "../creative-workspace/creative-workspace-manager.js";
import type { DecisionIntelligenceManager } from "../decision-intelligence/decision-intelligence-manager.js";
import type { MarketingIntelligenceManager } from "../marketing-intelligence/marketing-intelligence-manager.js";
import type { ProductIntelligenceManager } from "../product-intelligence/product-intelligence-manager.js";
import { LearningCategory, LearningOutcome, LearningSource } from "../learning-memory-engine/types.js";
import { KnowledgeVerificationStatus } from "../knowledge-foundation/types.js";
import { KnowledgeStorageType } from "../knowledge-storage-engine/types.js";

export interface SaleRecord { id?: string; projectId?: string; productId: string; productName: string; occurredAt: string; quantity: number; unitPrice: number; currency: string; }
export interface InventoryRecord { sku: string; name: string; quantityOnHand: number; reorderPoint: number; targetStock: number; updatedAt?: string; projectId?: string; }
export interface MarketingMetric { id?: string; projectId?: string; campaign: string; occurredAt: string; spend: number; impressions: number; engagements: number; conversions: number; attributedRevenue: number; }
export type BusinessReportKind = "daily" | "weekly" | "monthly" | "annual" | "sales" | "marketing" | "inventory" | "executive";
export type BusinessExportFormat = "json" | "csv" | "pdf" | "excel";
export interface BusinessRecommendation { area: "pricing" | "marketing" | "inventory" | "product" | "growth"; priority: "high" | "medium" | "low"; explanation: string; expectedOutcome: string; evidence: string[]; }
export interface BusinessStore { sales: Required<SaleRecord>[]; inventory: Required<InventoryRecord>[]; marketing: Required<MarketingMetric>[]; reports: Array<{ id: string; kind: BusinessReportKind; createdAt: string; snapshot: BusinessDashboard }>; }
export interface BusinessDashboard { generatedAt: string; dataStatus: "no-business-data" | "partial" | "ready"; sales: { revenue: number; units: number; transactions: number; daily: Array<{ date: string; revenue: number }>; weekly: Array<{ week: string; revenue: number }>; monthly: Array<{ month: string; revenue: number }>; products: Array<{ productId: string; productName: string; revenue: number; units: number }> }; marketing: { spend: number; attributedRevenue: number; roiPercent: number | null; impressions: number; engagements: number; engagementRate: number | null; conversions: number; conversionRate: number | null }; inventory: { items: number; lowStock: InventoryRecord[]; overstock: InventoryRecord[]; stockValueUnavailable: true }; projects: { total: number; active: number }; forecast: { available: boolean; nextSevenDaysRevenue: number | null; method: string; demandTrend: "up" | "down" | "flat" | "unknown" }; recommendations: BusinessRecommendation[]; health: { score: number; risks: string[] }; integrations: Record<string, boolean>; }

const EMPTY: BusinessStore = { sales: [], inventory: [], marketing: [], reports: [] };
const MAX_RECORDS = 10_000;

/** Offline-first business data owner. It calculates only from validated local source records. */
export class BusinessIntelligenceManager {
  private root = "";
  private store: BusinessStore = structuredClone(EMPTY);

  constructor(private readonly core: AiCoreManager | null, private readonly workspace: CreativeWorkspaceManager, private readonly products: ProductIntelligenceManager, private readonly marketingIntelligence: MarketingIntelligenceManager, private readonly decisions: DecisionIntelligenceManager) {}

  async initialize(storageRoot: string): Promise<void> { this.root = path.join(storageRoot, "business-intelligence-runtime"); await fs.mkdir(path.join(this.root, "exports"), { recursive: true }); this.store = await this.readStore(); }
  async recordSales(input: SaleRecord[]): Promise<number> { this.ensureReady(); if (!input.length || input.length > 1_000) throw new Error("Sales import must contain between 1 and 1,000 records"); const records = input.map(normalizeSale); ensureSingleCurrency([...this.store.sales, ...records]); this.store.sales = [...records, ...this.store.sales].slice(0, MAX_RECORDS); await this.persist(); await this.recordFoundationEvent("sales-import"); return records.length; }
  async upsertInventory(input: InventoryRecord[]): Promise<number> { this.ensureReady(); if (!input.length || input.length > 1_000) throw new Error("Inventory import must contain between 1 and 1,000 records"); for (const record of input.map(normalizeInventory)) { this.store.inventory = [record, ...this.store.inventory.filter((item) => item.sku !== record.sku)]; } await this.persist(); await this.recordFoundationEvent("inventory-import"); return input.length; }
  async recordMarketing(input: MarketingMetric[]): Promise<number> { this.ensureReady(); if (!input.length || input.length > 1_000) throw new Error("Marketing import must contain between 1 and 1,000 records"); const records = input.map(normalizeMarketing); this.store.marketing = [...records, ...this.store.marketing].slice(0, MAX_RECORDS); await this.persist(); await this.recordFoundationEvent("marketing-import"); return records.length; }
  async getDashboard(): Promise<BusinessDashboard> {
    this.ensureReady(); ensureSingleCurrency(this.store.sales); const projects = await this.workspace.listProjects(); const sales = salesSummary(this.store.sales); const marketing = marketingSummary(this.store.marketing); const inventory = inventorySummary(this.store.inventory); const forecast = buildForecast(sales.daily); const recommendations = buildRecommendations(sales, marketing, inventory, forecast); const risks = recommendations.filter((item) => item.priority === "high").map((item) => item.explanation); const availableSources = [this.store.sales.length > 0, this.store.marketing.length > 0, this.store.inventory.length > 0].filter(Boolean).length;
    return { generatedAt: new Date().toISOString(), dataStatus: availableSources === 0 ? "no-business-data" : availableSources === 3 ? "ready" : "partial", sales, marketing, inventory, projects: { total: projects.length, active: projects.filter((project) => Boolean(project.modifiedAt)).length }, forecast, recommendations, health: { score: Math.max(0, Math.min(100, 100 - risks.length * 15 - (availableSources ? 0 : 35))), risks }, integrations: { aiCore: Boolean(this.core), productIntelligence: this.products.isInitialized(), marketingIntelligence: this.marketingIntelligence.isInitialized(), decisionIntelligence: this.decisions.isInitialized(), memoryFoundation: Boolean(this.core?.memoryFoundation?.learningMemoryEngine), knowledgeFoundation: Boolean(this.core?.knowledgeFoundation?.getStorageEngine()), workflowEngine: Boolean(this.core?.workflowEngine), projectManagement: true } };
  }
  async generateReport(kind: BusinessReportKind): Promise<{ id: string; kind: BusinessReportKind; createdAt: string; snapshot: BusinessDashboard }> { const report = { id: randomUUID(), kind, createdAt: new Date().toISOString(), snapshot: await this.getDashboard() }; this.store.reports.unshift(report); this.store.reports.splice(100); await this.persist(); await this.recordFoundationEvent(`report-${kind}`); return structuredClone(report); }
  async exportReport(kind: BusinessReportKind, format: BusinessExportFormat): Promise<{ fileName: string; downloadPath: string; format: BusinessExportFormat }> { const report = await this.generateReport(kind); const baseName = `business-${kind}-${report.id}`; const target = path.join(this.root, "exports"); let fileName: string; let data: Buffer | string;
    if (format === "json") { fileName = `${baseName}.json`; data = `${JSON.stringify(report, null, 2)}\n`; }
    else if (format === "csv" || format === "excel") { fileName = `${baseName}.csv`; data = reportCsv(report); }
    else { fileName = `${baseName}.pdf`; data = pdf(reportText(report)); }
    await fs.writeFile(path.join(target, fileName), data); return { fileName, downloadPath: `/api/business-intelligence/exports/${encodeURIComponent(fileName)}`, format };
  }
  async getExportPath(fileName: string): Promise<string | null> { if (!/^[a-zA-Z0-9._-]+$/.test(fileName)) return null; const filePath = path.join(this.root, "exports", fileName); try { await fs.access(filePath); return filePath; } catch { return null; } }

  private async readStore(): Promise<BusinessStore> { try { const saved = JSON.parse(await fs.readFile(path.join(this.root, "business.json"), "utf8")) as Partial<BusinessStore>; return { sales: saved.sales ?? [], inventory: saved.inventory ?? [], marketing: saved.marketing ?? [], reports: saved.reports ?? [] }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return structuredClone(EMPTY); throw error; } }
  private async persist(): Promise<void> { const file = path.join(this.root, "business.json"); const temporary = `${file}.${randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(this.store)}\n`, "utf8"); await fs.rename(temporary, file); }
  private async recordFoundationEvent(event: string): Promise<void> { const dashboard = await this.getDashboard(); const memory = this.core?.memoryFoundation?.learningMemoryEngine; const knowledge = this.core?.knowledgeFoundation; const description = `Business ${event}: ${dashboard.sales.transactions} sales records, ${dashboard.inventory.items} inventory records, ${dashboard.recommendations.length} evidence-backed recommendation(s).`;
    if (memory?.isStartupComplete()) await memory.learnFromEvent({ source: event.startsWith("report") ? LearningSource.ExportResult : LearningSource.ProjectHistory, category: LearningCategory.Project, title: `Business intelligence ${event}`, description, outcome: LearningOutcome.Success, qualityScore: dashboard.health.score, lessonLearned: "Business summaries use locally imported records and preserve their source limitations.", patterns: dashboard.recommendations.map((item) => item.area), metadata: { event, dataStatus: dashboard.dataStatus, salesRecords: dashboard.sales.transactions, inventoryItems: dashboard.inventory.items, recommendationAreas: dashboard.recommendations.map((item) => item.area) } });
    if (knowledge?.isStartupComplete()) await knowledge.getStorageEngine().storeRecord({ knowledgeId: `business-${event}-${randomUUID()}`, knowledgeType: KnowledgeStorageType.Business, category: "business-intelligence", title: `Business intelligence ${event}`, description, summary: `Local business data status: ${dashboard.dataStatus}. ${description}`, source: "business-intelligence-runtime", tags: ["business", event, dashboard.dataStatus], keywords: dashboard.recommendations.map((item) => item.area), relatedMemory: [], relatedKnowledge: [], qualityScore: dashboard.health.score, confidenceScore: dashboard.dataStatus === "ready" ? 80 : 55, sourceReliability: 80, verificationStatus: KnowledgeVerificationStatus.Pending, payload: { event, dataStatus: dashboard.dataStatus, salesTransactions: dashboard.sales.transactions, inventoryItems: dashboard.inventory.items, marketingRoiAvailable: dashboard.marketing.roiPercent !== null, recommendationAreas: dashboard.recommendations.map((item) => item.area) } }); }
  private ensureReady(): void { if (!this.root) throw new Error("Business Intelligence Manager is not initialized"); }
}

function normalizeSale(input: SaleRecord): Required<SaleRecord> { positive(input.quantity, "Sale quantity"); nonNegative(input.unitPrice, "Sale unit price"); return { id: input.id ?? randomUUID(), projectId: input.projectId ?? "", productId: required(input.productId, "Product ID"), productName: required(input.productName, "Product name"), occurredAt: date(input.occurredAt), quantity: input.quantity, unitPrice: input.unitPrice, currency: required(input.currency, "Currency").toUpperCase() }; }
function normalizeInventory(input: InventoryRecord): Required<InventoryRecord> { nonNegative(input.quantityOnHand, "Quantity on hand"); nonNegative(input.reorderPoint, "Reorder point"); nonNegative(input.targetStock, "Target stock"); return { sku: required(input.sku, "SKU"), name: required(input.name, "Inventory name"), quantityOnHand: input.quantityOnHand, reorderPoint: input.reorderPoint, targetStock: input.targetStock, updatedAt: input.updatedAt ? date(input.updatedAt) : new Date().toISOString(), projectId: input.projectId ?? "" }; }
function normalizeMarketing(input: MarketingMetric): Required<MarketingMetric> { for (const [value, label] of [[input.spend, "Spend"], [input.impressions, "Impressions"], [input.engagements, "Engagements"], [input.conversions, "Conversions"], [input.attributedRevenue, "Attributed revenue"]] as const) nonNegative(value, label); return { id: input.id ?? randomUUID(), projectId: input.projectId ?? "", campaign: required(input.campaign, "Campaign"), occurredAt: date(input.occurredAt), spend: input.spend, impressions: input.impressions, engagements: input.engagements, conversions: input.conversions, attributedRevenue: input.attributedRevenue }; }
function ensureSingleCurrency(records: Required<SaleRecord>[]): void { const currencies = new Set(records.map((record) => record.currency)); if (currencies.size > 1) throw new Error("Sales analytics requires one currency per local business ledger; convert records before import"); }
function salesSummary(records: Required<SaleRecord>[]): BusinessDashboard["sales"] { const byDate = new Map<string, number>(); const products = new Map<string, { productId: string; productName: string; revenue: number; units: number }>(); let revenue = 0; let units = 0; for (const record of records) { const total = record.quantity * record.unitPrice; revenue += total; units += record.quantity; const day = record.occurredAt.slice(0, 10); byDate.set(day, (byDate.get(day) ?? 0) + total); const existing = products.get(record.productId) ?? { productId: record.productId, productName: record.productName, revenue: 0, units: 0 }; existing.revenue += total; existing.units += record.quantity; products.set(record.productId, existing); } const daily = [...byDate].sort(([a], [b]) => a.localeCompare(b)).map(([date, value]) => ({ date, revenue: round(value) })); return { revenue: round(revenue), units, transactions: records.length, daily, weekly: aggregate(daily, (date) => `${date.slice(0, 4)}-W${week(date)}`), monthly: aggregate(daily, (date) => date.slice(0, 7)), products: [...products.values()].sort((a, b) => b.revenue - a.revenue).map((item) => ({ ...item, revenue: round(item.revenue) })) }; }
function marketingSummary(records: Required<MarketingMetric>[]): BusinessDashboard["marketing"] { const totals = records.reduce((result, item) => ({ spend: result.spend + item.spend, attributedRevenue: result.attributedRevenue + item.attributedRevenue, impressions: result.impressions + item.impressions, engagements: result.engagements + item.engagements, conversions: result.conversions + item.conversions }), { spend: 0, attributedRevenue: 0, impressions: 0, engagements: 0, conversions: 0 }); return { ...totals, spend: round(totals.spend), attributedRevenue: round(totals.attributedRevenue), roiPercent: totals.spend ? round((totals.attributedRevenue - totals.spend) / totals.spend * 100) : null, engagementRate: totals.impressions ? round(totals.engagements / totals.impressions * 100) : null, conversionRate: totals.impressions ? round(totals.conversions / totals.impressions * 100) : null }; }
function inventorySummary(records: Required<InventoryRecord>[]): BusinessDashboard["inventory"] { return { items: records.length, lowStock: records.filter((item) => item.quantityOnHand <= item.reorderPoint), overstock: records.filter((item) => item.targetStock > 0 && item.quantityOnHand > item.targetStock) .map((item) => ({ ...item })), stockValueUnavailable: true }; }
function buildForecast(daily: Array<{ date: string; revenue: number }>): BusinessDashboard["forecast"] { if (daily.length < 2) return { available: false, nextSevenDaysRevenue: null, method: "Requires at least two observed sales days; no forecast is fabricated.", demandTrend: "unknown" }; const values = daily.slice(-7).map((item) => item.revenue); const average = values.reduce((sum, value) => sum + value, 0) / values.length; const trend = values.at(-1)! - values[0]; return { available: true, nextSevenDaysRevenue: round(average * 7), method: `Seven-day moving average from ${values.length} observed sales day(s).`, demandTrend: trend > average * .1 ? "up" : trend < -average * .1 ? "down" : "flat" }; }
function buildRecommendations(sales: BusinessDashboard["sales"], marketing: BusinessDashboard["marketing"], inventory: BusinessDashboard["inventory"], forecast: BusinessDashboard["forecast"]): BusinessRecommendation[] { const items: BusinessRecommendation[] = []; for (const item of inventory.lowStock) items.push({ area: "inventory", priority: "high", explanation: `${item.name} is at or below its reorder point.`, expectedOutcome: "Reduce stock-out risk.", evidence: [`On hand: ${item.quantityOnHand}`, `Reorder point: ${item.reorderPoint}`] }); for (const item of inventory.overstock) items.push({ area: "inventory", priority: "medium", explanation: `${item.name} exceeds its target stock.`, expectedOutcome: "Reduce carrying cost and free working capital.", evidence: [`On hand: ${item.quantityOnHand}`, `Target stock: ${item.targetStock}`] }); if (marketing.roiPercent !== null && marketing.roiPercent < 0) items.push({ area: "marketing", priority: "high", explanation: "Observed campaign spend exceeds attributed revenue.", expectedOutcome: "Improve ROI by reviewing targeting, offer, and creative.", evidence: [`ROI: ${marketing.roiPercent}%`, `Spend: ${marketing.spend}`, `Attributed revenue: ${marketing.attributedRevenue}`] }); if (sales.products.length > 1) { const weakest = sales.products.at(-1)!; items.push({ area: "product", priority: "medium", explanation: `${weakest.productName} is the lowest-revenue observed product.`, expectedOutcome: "Identify presentation, price, or channel improvements.", evidence: [`Revenue: ${weakest.revenue}`, `Units: ${weakest.units}`] }); } if (forecast.available) items.push({ area: "growth", priority: "low", explanation: `Observed demand trend is ${forecast.demandTrend}.`, expectedOutcome: "Plan stock and campaign capacity around the short-term forecast.", evidence: [forecast.method, `Forecast revenue: ${forecast.nextSevenDaysRevenue}`] }); return items; }
function aggregate(daily: Array<{ date: string; revenue: number }>, key: (date: string) => string): Array<{ [key: string]: string | number }> { const values = new Map<string, number>(); for (const item of daily) { const group = key(item.date); values.set(group, (values.get(group) ?? 0) + item.revenue); } return [...values].map(([period, revenue]) => ({ [period.includes("-W") ? "week" : "month"]: period, revenue: round(revenue) })); }
function reportCsv(report: { kind: BusinessReportKind; snapshot: BusinessDashboard }): string { const rows = [["metric", "value"], ["report_kind", report.kind], ["data_status", report.snapshot.dataStatus], ["revenue", String(report.snapshot.sales.revenue)], ["units", String(report.snapshot.sales.units)], ["transactions", String(report.snapshot.sales.transactions)], ["marketing_spend", String(report.snapshot.marketing.spend)], ["marketing_roi_percent", String(report.snapshot.marketing.roiPercent ?? "")], ["inventory_items", String(report.snapshot.inventory.items)], ["low_stock_items", String(report.snapshot.inventory.lowStock.length)], ["forecast_next_seven_days_revenue", String(report.snapshot.forecast.nextSevenDaysRevenue ?? "")]]; return rows.map((row) => row.map(csv).join(",")).join("\n") + "\n"; }
function reportText(report: { kind: BusinessReportKind; snapshot: BusinessDashboard }): string { const dashboard = report.snapshot; return `KWIZERA AI BUSINESS REPORT\nReport: ${report.kind}\nGenerated: ${dashboard.generatedAt}\nData status: ${dashboard.dataStatus}\nRevenue: ${dashboard.sales.revenue}\nUnits sold: ${dashboard.sales.units}\nMarketing spend: ${dashboard.marketing.spend}\nMarketing ROI: ${dashboard.marketing.roiPercent ?? "unavailable"}%\nInventory items: ${dashboard.inventory.items}\nLow stock: ${dashboard.inventory.lowStock.length}\nForecast: ${dashboard.forecast.nextSevenDaysRevenue ?? "unavailable"}\nRecommendations: ${dashboard.recommendations.map((item) => item.explanation).join(" | ") || "No evidence-backed recommendations yet."}`; }
function pdf(text: string): Buffer { const content = `BT /F1 10 Tf 48 760 Td 13 TL (${escapePdf(text).replace(/\n/g, ") Tj T* (")}) Tj ET`; const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", `<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`]; let output = "%PDF-1.4\n"; const offsets = [0]; for (let index = 0; index < objects.length; index++) { offsets.push(Buffer.byteLength(output)); output += `${index + 1} 0 obj\n${objects[index]}\nendobj\n`; } const xref = Buffer.byteLength(output); output += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("")}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`; return Buffer.from(output, "utf8"); }
function required(value: string, label: string): string { const result = value.trim(); if (!result) throw new Error(`${label} is required`); return result; } function date(value: string): string { if (Number.isNaN(Date.parse(value))) throw new Error("Occurred date must be an ISO date"); return new Date(value).toISOString(); } function nonNegative(value: number, label: string): void { if (!Number.isFinite(value) || value < 0) throw new Error(`${label} must be a non-negative finite number`); } function positive(value: number, label: string): void { nonNegative(value, label); if (!value) throw new Error(`${label} must be greater than zero`); } function round(value: number): number { return Math.round(value * 100) / 100; } function week(date: string): number { const current = new Date(`${date}T00:00:00Z`); const start = new Date(Date.UTC(current.getUTCFullYear(), 0, 1)); return Math.ceil((((current.getTime() - start.getTime()) / 86400000) + start.getUTCDay() + 1) / 7); } function csv(value: string): string { return `"${value.replace(/"/g, '""')}"`; } function escapePdf(value: string): string { return value.replace(/[\\()]/g, "\\$&"); }