/**
 * Curated trusted source discovery catalog (Knowledge Seeding Step 2).
 * Entries register as pending only — never auto-approved.
 */

import {
  KnowledgeSourceTrustClass,
  type KnowledgeSourceDefinition,
  type TrustedKnowledgeSourceEntry,
} from "./types.js";

interface CatalogInput {
  id: string;
  name: string;
  description: string;
  category: string;
  url: string;
  type: KnowledgeSourceDefinition["type"];
  publisher: string;
  topics: string[];
  domainIds: string[];
  license?: string;
  language?: KnowledgeSourceDefinition["language"];
  trustClass?: KnowledgeSourceTrustClass;
  updateFrequency?: KnowledgeSourceDefinition["updateFrequency"];
  accessMethod?: KnowledgeSourceDefinition["accessMethod"];
  officialWebsite?: string;
  upgradedFromExisting?: boolean;
}

function entry(input: CatalogInput): TrustedKnowledgeSourceEntry {
  const trustClass =
    input.trustClass ??
    (input.type === "official-documentation" || input.type === "official-api-documentation"
      ? KnowledgeSourceTrustClass.Official
      : input.type === "research-paper" || input.type === "technical-manual"
        ? KnowledgeSourceTrustClass.HighlyTrusted
        : input.type === "open-educational-resource" || input.type === "white-paper"
          ? KnowledgeSourceTrustClass.Trusted
          : KnowledgeSourceTrustClass.Community);

  const definition: KnowledgeSourceDefinition = {
    id: input.id,
    name: input.name,
    description: input.description,
    type: input.type,
    location: { kind: "url", value: input.url },
    tags: [input.category, ...input.topics],
    publisher: input.publisher,
    license: input.license ?? "Publisher terms / documentation license",
    category: input.category,
    domainIds: input.domainIds,
    officialWebsite: input.officialWebsite ?? new URL(input.url).origin,
    resourceType: input.type,
    language: input.language ?? "en",
    trustClass,
    updateFrequency: input.updateFrequency ?? "as-needed",
    accessMethod:
      input.accessMethod ??
      (input.type === "research-paper" ? "open-access-repository" : "https-documentation"),
    lastUpdated: "2026-01-01T00:00:00.000Z",
  };

  return {
    definition,
    category: input.category,
    discoveryTopics: input.topics,
    upgradedFromExisting: input.upgradedFromExisting,
  };
}

/**
 * Full discovery catalog: upgrades the original 25 library entries and adds
 * professional sources for creative, marketing, and production domains.
 */
export const TRUSTED_SOURCE_LIBRARY: TrustedKnowledgeSourceEntry[] = [
  // ---- Existing AI/ML (upgraded) ----
  entry({
    id: "huggingface-docs",
    name: "Hugging Face Documentation",
    description: "Official documentation for Hugging Face models, datasets, and libraries.",
    category: "AI/ML",
    url: "https://huggingface.co/docs",
    type: "official-api-documentation",
    publisher: "Hugging Face",
    topics: ["artificial-intelligence", "machine-learning"],
    domainIds: ["technical-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
    updateFrequency: "continuous",
  }),
  entry({
    id: "pytorch-docs",
    name: "PyTorch Documentation",
    description: "Official PyTorch API and framework documentation.",
    category: "AI/ML",
    url: "https://pytorch.org/docs/stable/index.html",
    type: "official-documentation",
    publisher: "PyTorch",
    topics: ["artificial-intelligence", "machine-learning"],
    domainIds: ["technical-knowledge"],
    upgradedFromExisting: true,
    updateFrequency: "monthly",
  }),
  entry({
    id: "tensorflow-docs",
    name: "TensorFlow Documentation",
    description: "Official TensorFlow API documentation.",
    category: "AI/ML",
    url: "https://www.tensorflow.org/api_docs",
    type: "official-documentation",
    publisher: "Google (TensorFlow)",
    topics: ["artificial-intelligence", "machine-learning"],
    domainIds: ["technical-knowledge"],
    upgradedFromExisting: true,
  }),
  entry({
    id: "onnx-docs",
    name: "ONNX Documentation",
    description: "Official Open Neural Network Exchange format documentation.",
    category: "AI/ML",
    url: "https://onnx.ai/onnx/",
    type: "official-documentation",
    publisher: "ONNX",
    topics: ["artificial-intelligence", "machine-learning"],
    domainIds: ["technical-knowledge"],
    upgradedFromExisting: true,
  }),
  entry({
    id: "comfyui-docs",
    name: "ComfyUI Documentation",
    description: "Official documentation for the ComfyUI node-based image/video generation interface.",
    category: "Image/Video",
    url: "https://docs.comfy.org/",
    type: "official-documentation",
    publisher: "Comfy-Org",
    topics: ["artificial-intelligence", "product-photography", "video-production"],
    domainIds: ["video-production-knowledge", "product-knowledge"],
    upgradedFromExisting: true,
  }),
  entry({
    id: "automatic1111-docs",
    name: "AUTOMATIC1111 Stable Diffusion WebUI Documentation",
    description: "Official project wiki documentation for the AUTOMATIC1111 Stable Diffusion WebUI.",
    category: "Image/Video",
    url: "https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki",
    type: "official-documentation",
    publisher: "AUTOMATIC1111",
    topics: ["artificial-intelligence", "product-photography"],
    domainIds: ["product-knowledge"],
    upgradedFromExisting: true,
    trustClass: KnowledgeSourceTrustClass.Community,
  }),
  entry({
    id: "ffmpeg-docs",
    name: "FFmpeg Documentation",
    description: "Official FFmpeg multimedia framework documentation.",
    category: "Image/Video",
    url: "https://ffmpeg.org/documentation.html",
    type: "official-documentation",
    publisher: "FFmpeg",
    topics: ["video-production", "video-editing", "rendering", "audio"],
    domainIds: ["video-production-knowledge", "video-editing-knowledge", "rendering-knowledge", "audio-knowledge"],
    upgradedFromExisting: true,
  }),
  entry({
    id: "opencv-docs",
    name: "OpenCV Documentation",
    description: "Official OpenCV computer vision library documentation.",
    category: "Computer Vision",
    url: "https://docs.opencv.org/",
    type: "official-documentation",
    publisher: "OpenCV",
    topics: ["artificial-intelligence", "machine-learning", "composition"],
    domainIds: ["composition-knowledge", "technical-knowledge"],
    upgradedFromExisting: true,
  }),
  entry({
    id: "blender-docs",
    name: "Blender Documentation",
    description: "Official Blender 3D creation suite manual.",
    category: "Image/Video",
    url: "https://docs.blender.org/",
    type: "user-manual",
    publisher: "Blender Foundation",
    topics: ["animation", "rendering", "motion-graphics", "video-editing"],
    domainIds: ["animation-knowledge", "rendering-knowledge", "motion-graphics-knowledge"],
    upgradedFromExisting: true,
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "mdn-docs",
    name: "MDN Web Docs",
    description: "Mozilla Developer Network reference documentation for web technologies.",
    category: "Programming",
    url: "https://developer.mozilla.org/en-US/",
    type: "official-documentation",
    publisher: "Mozilla",
    topics: ["software-engineering", "ui-ux"],
    domainIds: ["technical-knowledge", "ui-ux-knowledge"],
    upgradedFromExisting: true,
  }),
  entry({
    id: "nodejs-docs",
    name: "Node.js API Documentation",
    description: "Official Node.js runtime API documentation.",
    category: "Programming",
    url: "https://nodejs.org/docs/latest/api/",
    type: "official-api-documentation",
    publisher: "OpenJS Foundation",
    topics: ["software-engineering"],
    domainIds: ["technical-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
  }),
  entry({
    id: "typescript-docs",
    name: "TypeScript Documentation",
    description: "Official TypeScript language handbook and reference.",
    category: "Programming",
    url: "https://www.typescriptlang.org/docs/",
    type: "official-documentation",
    publisher: "Microsoft",
    topics: ["software-engineering"],
    domainIds: ["technical-knowledge"],
    upgradedFromExisting: true,
  }),
  entry({
    id: "react-docs",
    name: "React Documentation",
    description: "Official React library reference documentation.",
    category: "Programming",
    url: "https://react.dev/reference/react",
    type: "official-documentation",
    publisher: "Meta (React)",
    topics: ["software-engineering", "ui-ux"],
    domainIds: ["technical-knowledge", "ui-ux-knowledge"],
    upgradedFromExisting: true,
  }),
  entry({
    id: "express-docs",
    name: "Express Documentation",
    description: "Official Express.js web framework API documentation.",
    category: "Programming",
    url: "https://expressjs.com/en/4x/api.html",
    type: "official-api-documentation",
    publisher: "OpenJS Foundation",
    topics: ["software-engineering"],
    domainIds: ["technical-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
  }),
  entry({
    id: "sqlite-docs",
    name: "SQLite Documentation",
    description: "Official SQLite database engine documentation.",
    category: "Programming",
    url: "https://www.sqlite.org/docs.html",
    type: "official-documentation",
    publisher: "SQLite Consortium",
    topics: ["software-engineering"],
    domainIds: ["technical-knowledge"],
    upgradedFromExisting: true,
  }),
  entry({
    id: "ultralytics-docs",
    name: "Ultralytics Documentation",
    description: "Official Ultralytics YOLO computer vision model documentation.",
    category: "Computer Vision",
    url: "https://docs.ultralytics.com/",
    type: "official-documentation",
    publisher: "Ultralytics",
    topics: ["artificial-intelligence", "machine-learning"],
    domainIds: ["technical-knowledge"],
    upgradedFromExisting: true,
  }),
  entry({
    id: "google-search-docs",
    name: "Google Search Central Documentation",
    description: "Official Google Search API and SEO documentation.",
    category: "Marketing",
    url: "https://developers.google.com/search/docs",
    type: "official-api-documentation",
    publisher: "Google",
    topics: ["marketing", "ecommerce"],
    domainIds: ["marketing-knowledge", "ecommerce-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
  }),
  entry({
    id: "google-analytics-docs",
    name: "Google Analytics Documentation",
    description: "Official Google Analytics API and product documentation.",
    category: "Marketing",
    url: "https://developers.google.com/analytics",
    type: "official-api-documentation",
    publisher: "Google",
    topics: ["marketing"],
    domainIds: ["marketing-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
  }),
  entry({
    id: "meta-business-docs",
    name: "Meta Business & Marketing API Documentation",
    description: "Official Meta documentation for Marketing and Business APIs.",
    category: "Social Platforms",
    url: "https://developers.facebook.com/docs/marketing-apis",
    type: "official-api-documentation",
    publisher: "Meta",
    topics: ["marketing", "social-media", "facebook", "instagram"],
    domainIds: ["marketing-knowledge", "social-media-knowledge", "facebook-knowledge", "instagram-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
  }),
  entry({
    id: "facebook-developer-docs",
    name: "Facebook for Developers Documentation",
    description: "Official Facebook Platform developer documentation.",
    category: "Social Platforms",
    url: "https://developers.facebook.com/docs",
    type: "official-api-documentation",
    publisher: "Meta",
    topics: ["facebook", "social-media"],
    domainIds: ["facebook-knowledge", "social-media-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
  }),
  entry({
    id: "instagram-platform-docs",
    name: "Instagram Platform Documentation",
    description: "Official Instagram Graph API and platform documentation.",
    category: "Social Platforms",
    url: "https://developers.facebook.com/docs/instagram",
    type: "official-api-documentation",
    publisher: "Meta",
    topics: ["instagram", "social-media"],
    domainIds: ["instagram-knowledge", "social-media-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
  }),
  entry({
    id: "youtube-api-docs",
    name: "YouTube Data API Documentation",
    description: "Official YouTube Data API v3 reference documentation.",
    category: "Social Platforms",
    url: "https://developers.google.com/youtube/v3",
    type: "official-api-documentation",
    publisher: "Google (YouTube)",
    topics: ["youtube", "social-media", "video-production"],
    domainIds: ["youtube-knowledge", "social-media-knowledge", "video-production-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
  }),
  entry({
    id: "tiktok-developer-docs",
    name: "TikTok for Developers Documentation",
    description: "Official TikTok developer platform and API documentation.",
    category: "Social Platforms",
    url: "https://developers.tiktok.com/doc/overview",
    type: "official-api-documentation",
    publisher: "TikTok",
    topics: ["tiktok", "social-media"],
    domainIds: ["tiktok-knowledge", "social-media-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
  }),
  entry({
    id: "arxiv",
    name: "arXiv",
    description: "Open-access repository of scholarly research papers across scientific disciplines.",
    category: "Academic",
    url: "https://arxiv.org",
    type: "research-paper",
    publisher: "Cornell University",
    topics: ["artificial-intelligence", "machine-learning", "customer-psychology", "sales-psychology"],
    domainIds: ["technical-knowledge", "customer-psychology", "sales-psychology"],
    upgradedFromExisting: true,
    trustClass: KnowledgeSourceTrustClass.HighlyTrusted,
    accessMethod: "open-access-repository",
    license: "arXiv non-exclusive license / author licenses",
  }),
  entry({
    id: "crossref-docs",
    name: "Crossref Documentation",
    description: "Official Crossref scholarly metadata and DOI registration documentation.",
    category: "Academic",
    url: "https://www.crossref.org/documentation/",
    type: "official-api-documentation",
    publisher: "Crossref",
    topics: ["artificial-intelligence", "machine-learning"],
    domainIds: ["technical-knowledge"],
    upgradedFromExisting: true,
    accessMethod: "https-api-reference",
  }),

  // ---- New creative / production sources ----
  entry({
    id: "adobe-camera-raw-docs",
    name: "Adobe Camera Raw Documentation",
    description: "Official Adobe guidance for camera raw processing and photographic workflows.",
    category: "Photography",
    url: "https://helpx.adobe.com/camera-raw/using/introduction-camera-raw.html",
    type: "user-manual",
    publisher: "Adobe",
    topics: ["camera", "product-photography", "composition"],
    domainIds: ["camera-knowledge", "product-knowledge", "composition-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "canon-learning-center",
    name: "Canon USA Learning Resources",
    description: "Official Canon educational resources covering camera operation and photographic technique.",
    category: "Photography",
    url: "https://www.usa.canon.com/learning",
    type: "open-educational-resource",
    publisher: "Canon",
    topics: ["camera", "lighting", "composition", "product-photography"],
    domainIds: ["camera-knowledge", "lighting-knowledge", "composition-knowledge", "product-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "nikon-learn-explore",
    name: "Nikon Learn & Explore",
    description: "Official Nikon educational articles on camera settings, lenses, and lighting.",
    category: "Photography",
    url: "https://www.nikonusa.com/learn-and-explore",
    type: "open-educational-resource",
    publisher: "Nikon",
    topics: ["camera", "lighting", "composition"],
    domainIds: ["camera-knowledge", "lighting-knowledge", "composition-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "davinci-resolve-manual",
    name: "DaVinci Resolve Reference Manual",
    description: "Official Blackmagic Design reference manual for DaVinci Resolve editing and color.",
    category: "Video Editing",
    url: "https://www.blackmagicdesign.com/products/davinciresolve/training",
    type: "technical-manual",
    publisher: "Blackmagic Design",
    topics: ["video-editing", "video-production", "rendering"],
    domainIds: ["video-editing-knowledge", "video-production-knowledge", "rendering-knowledge"],
    trustClass: KnowledgeSourceTrustClass.HighlyTrusted,
  }),
  entry({
    id: "premiere-pro-user-guide",
    name: "Adobe Premiere Pro User Guide",
    description: "Official Adobe Premiere Pro user guide for professional video editing workflows.",
    category: "Video Editing",
    url: "https://helpx.adobe.com/premiere-pro/user-guide.html",
    type: "user-manual",
    publisher: "Adobe",
    topics: ["video-editing", "video-production"],
    domainIds: ["video-editing-knowledge", "video-production-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "after-effects-user-guide",
    name: "Adobe After Effects User Guide",
    description: "Official Adobe After Effects guide for motion graphics and visual effects.",
    category: "Motion Graphics",
    url: "https://helpx.adobe.com/after-effects/user-guide.html",
    type: "user-manual",
    publisher: "Adobe",
    topics: ["motion-graphics", "animation", "video-production"],
    domainIds: ["motion-graphics-knowledge", "animation-knowledge", "video-production-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "cinema4d-manual",
    name: "Maxon Cinema 4D Documentation",
    description: "Official Maxon Cinema 4D documentation for 3D animation and rendering.",
    category: "Animation",
    url: "https://docs.maxon.net/",
    type: "official-documentation",
    publisher: "Maxon",
    topics: ["animation", "rendering", "motion-graphics"],
    domainIds: ["animation-knowledge", "rendering-knowledge", "motion-graphics-knowledge"],
  }),
  entry({
    id: "unreal-engine-docs",
    name: "Unreal Engine Documentation",
    description: "Official Epic Games Unreal Engine documentation for real-time rendering and cinematography tools.",
    category: "Rendering",
    url: "https://dev.epicgames.com/documentation/en-us/unreal-engine",
    type: "official-documentation",
    publisher: "Epic Games",
    topics: ["rendering", "lighting", "camera", "animation"],
    domainIds: ["rendering-knowledge", "lighting-knowledge", "camera-knowledge", "animation-knowledge"],
  }),
  entry({
    id: "audiokinetic-wwise-docs",
    name: "Audiokinetic Wwise Documentation",
    description: "Official Wwise interactive audio middleware documentation.",
    category: "Audio",
    url: "https://www.audiokinetic.com/en/library/edge/",
    type: "official-documentation",
    publisher: "Audiokinetic",
    topics: ["audio", "music"],
    domainIds: ["audio-knowledge", "music-knowledge"],
  }),
  entry({
    id: "ableton-live-manual",
    name: "Ableton Live Manual",
    description: "Official Ableton Live reference manual for music production and arrangement.",
    category: "Music",
    url: "https://www.ableton.com/en/manual/welcome-to-live/",
    type: "user-manual",
    publisher: "Ableton",
    topics: ["music", "audio"],
    domainIds: ["music-knowledge", "audio-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "aes-standards",
    name: "Audio Engineering Society Standards",
    description: "Professional AES standards and recommended practices for audio engineering.",
    category: "Audio",
    url: "https://www.aes.org/standards/",
    type: "technical-standard",
    publisher: "Audio Engineering Society",
    topics: ["audio"],
    domainIds: ["audio-knowledge"],
    trustClass: KnowledgeSourceTrustClass.HighlyTrusted,
  }),
  entry({
    id: "smpte-standards",
    name: "SMPTE Standards",
    description: "Society of Motion Picture and Television Engineers standards for professional video production.",
    category: "Video Production",
    url: "https://www.smpte.org/standards",
    type: "technical-standard",
    publisher: "SMPTE",
    topics: ["video-production", "rendering", "video-editing"],
    domainIds: ["video-production-knowledge", "rendering-knowledge", "video-editing-knowledge"],
    trustClass: KnowledgeSourceTrustClass.HighlyTrusted,
  }),
  entry({
    id: "asc-cinematography",
    name: "American Society of Cinematographers Resources",
    description: "Professional cinematography education and reference resources from the ASC.",
    category: "Cinematography",
    url: "https://theasc.com/",
    type: "open-educational-resource",
    publisher: "American Society of Cinematographers",
    topics: ["camera", "lighting", "composition", "storytelling", "video-production"],
    domainIds: [
      "camera-knowledge",
      "lighting-knowledge",
      "composition-knowledge",
      "storytelling-knowledge",
      "video-production-knowledge",
    ],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "pixar-storytelling",
    name: "Pixar in a Box — Storytelling",
    description: "Open educational collaboration covering storytelling craft used in professional animation.",
    category: "Storytelling",
    url: "https://www.khanacademy.org/computing/pixar",
    type: "open-educational-resource",
    publisher: "Khan Academy / Pixar",
    topics: ["storytelling", "animation"],
    domainIds: ["storytelling-knowledge", "animation-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
    license: "Khan Academy / content partner terms",
  }),
  entry({
    id: "nngroup-ux",
    name: "Nielsen Norman Group UX Articles",
    description: "Evidence-based UX research articles and guidelines from Nielsen Norman Group.",
    category: "UI/UX",
    url: "https://www.nngroup.com/articles/",
    type: "research-paper",
    publisher: "Nielsen Norman Group",
    topics: ["ui-ux"],
    domainIds: ["ui-ux-knowledge"],
    trustClass: KnowledgeSourceTrustClass.HighlyTrusted,
  }),
  entry({
    id: "w3c-wai",
    name: "W3C Web Accessibility Initiative",
    description: "Official W3C accessibility standards and UI guidance.",
    category: "UI/UX",
    url: "https://www.w3.org/WAI/",
    type: "technical-standard",
    publisher: "W3C",
    topics: ["ui-ux", "software-engineering"],
    domainIds: ["ui-ux-knowledge", "technical-knowledge"],
    trustClass: KnowledgeSourceTrustClass.HighlyTrusted,
  }),
  entry({
    id: "shopify-commerce-docs",
    name: "Shopify Commerce Documentation",
    description: "Official Shopify documentation for e-commerce merchandising and storefront operations.",
    category: "E-commerce",
    url: "https://shopify.dev/docs",
    type: "official-documentation",
    publisher: "Shopify",
    topics: ["ecommerce", "marketing"],
    domainIds: ["ecommerce-knowledge", "marketing-knowledge"],
  }),
  entry({
    id: "google-merchant-center-docs",
    name: "Google Merchant Center Documentation",
    description: "Official Google documentation for product listing and e-commerce advertising.",
    category: "E-commerce",
    url: "https://support.google.com/merchants/",
    type: "official-documentation",
    publisher: "Google",
    topics: ["ecommerce", "marketing"],
    domainIds: ["ecommerce-knowledge", "marketing-knowledge"],
  }),
  entry({
    id: "hubspot-marketing-library",
    name: "HubSpot Marketing Library",
    description: "Open educational marketing resources covering campaigns, funnels, and content strategy.",
    category: "Marketing",
    url: "https://www.hubspot.com/resources",
    type: "open-educational-resource",
    publisher: "HubSpot",
    topics: ["marketing", "customer-psychology", "sales-psychology"],
    domainIds: ["marketing-knowledge", "customer-psychology", "sales-psychology"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "ama-marketing",
    name: "American Marketing Association Resources",
    description: "Professional marketing association resources and practice guidance.",
    category: "Marketing",
    url: "https://www.ama.org/",
    type: "white-paper",
    publisher: "American Marketing Association",
    topics: ["marketing", "branding"],
    domainIds: ["marketing-knowledge", "branding-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "apa-psychology",
    name: "American Psychological Association Resources",
    description: "Official APA resources relevant to consumer and behavioral psychology foundations.",
    category: "Psychology",
    url: "https://www.apa.org/topics",
    type: "open-educational-resource",
    publisher: "American Psychological Association",
    topics: ["customer-psychology", "sales-psychology"],
    domainIds: ["customer-psychology", "sales-psychology"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "branding-iso-guidelines",
    name: "ISO Brand-Related Standards Overview",
    description: "ISO standards documentation relevant to brand and quality management practices.",
    category: "Branding",
    url: "https://www.iso.org/standards.html",
    type: "technical-standard",
    publisher: "ISO",
    topics: ["branding"],
    domainIds: ["branding-knowledge"],
    trustClass: KnowledgeSourceTrustClass.HighlyTrusted,
  }),
  entry({
    id: "youtube-creator-academy",
    name: "YouTube Creator Academy",
    description: "Official YouTube educational resources for creators on storytelling, retention, and packaging.",
    category: "Social Platforms",
    url: "https://creatoracademy.youtube.com/",
    type: "open-educational-resource",
    publisher: "Google (YouTube)",
    topics: ["youtube", "storytelling", "video-production", "social-media"],
    domainIds: ["youtube-knowledge", "storytelling-knowledge", "video-production-knowledge", "social-media-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "meta-blueprint",
    name: "Meta Blueprint",
    description: "Official Meta Blueprint learning resources for Facebook and Instagram marketing.",
    category: "Social Platforms",
    url: "https://www.facebookblueprint.com/",
    type: "open-educational-resource",
    publisher: "Meta",
    topics: ["facebook", "instagram", "social-media", "marketing"],
    domainIds: ["facebook-knowledge", "instagram-knowledge", "social-media-knowledge", "marketing-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "tiktok-academy",
    name: "TikTok Creative Center / Academy Resources",
    description: "Official TikTok creative education resources for short-form video marketing.",
    category: "Social Platforms",
    url: "https://ads.tiktok.com/business/creativecenter",
    type: "open-educational-resource",
    publisher: "TikTok",
    topics: ["tiktok", "social-media", "marketing", "storytelling"],
    domainIds: ["tiktok-knowledge", "social-media-knowledge", "marketing-knowledge", "storytelling-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
  entry({
    id: "cie-lighting",
    name: "CIE Lighting Standards",
    description: "International Commission on Illumination standards for professional lighting science.",
    category: "Lighting",
    url: "https://cie.co.at/",
    type: "technical-standard",
    publisher: "CIE",
    topics: ["lighting"],
    domainIds: ["lighting-knowledge"],
    trustClass: KnowledgeSourceTrustClass.HighlyTrusted,
  }),
  entry({
    id: "aws-well-architected",
    name: "AWS Well-Architected Framework",
    description: "Official AWS white paper framework for software and systems engineering best practices.",
    category: "Software Engineering",
    url: "https://docs.aws.amazon.com/wellarchitected/",
    type: "white-paper",
    publisher: "Amazon Web Services",
    topics: ["software-engineering"],
    domainIds: ["technical-knowledge"],
    trustClass: KnowledgeSourceTrustClass.Trusted,
  }),
];

export const EXISTING_TRUSTED_SOURCE_IDS = TRUSTED_SOURCE_LIBRARY.filter((e) => e.upgradedFromExisting).map(
  (e) => e.definition.id
);

export const NEW_TRUSTED_SOURCE_IDS = TRUSTED_SOURCE_LIBRARY.filter((e) => !e.upgradedFromExisting).map(
  (e) => e.definition.id
);

/** Hostname each library entry is expected to resolve to, used for domain-consistency checks. */
export function trustedLibraryHostname(entryId: string): string | null {
  const found = TRUSTED_SOURCE_LIBRARY.find((item) => item.definition.id === entryId);
  if (!found || found.definition.location.kind !== "url") return null;
  try {
    return new URL(found.definition.location.value).hostname;
  } catch {
    return null;
  }
}
