import { useEffect, useState } from "react";
import { Activity, Bell, Bot, CheckCircle2, ChevronRight, CircleAlert, Cpu, FolderKanban, Gauge, Image, LayoutDashboard, Lightbulb, MonitorCog, MoreHorizontal, Plus, RefreshCw, Settings, Sparkles, Video, X } from "lucide-react";
import { DashboardLayoutManager } from "./layout-store";
import type { DashboardCoreStatus, DashboardLayout, DashboardProject, DashboardWidgetId, DashboardWorkspace } from "./types";
import "./business-dashboard.css";

const layoutManager = new DashboardLayoutManager();
const widgets: Array<{ id: DashboardWidgetId; label: string }> = [
  { id: "kpis", label: "KPI overview" }, { id: "ai", label: "AI overview" }, { id: "activity", label: "Recent activity" }, { id: "projects", label: "Recent projects" }, { id: "health", label: "System health" }, { id: "notifications", label: "Notification center" }, { id: "actions", label: "Quick actions" },
];

async function fetchJson<T>(path: string): Promise<T | null> { try { const response = await fetch(path); return response.ok ? await response.json() as T : null; } catch { return null; } }
function bytes(value: number) { return value ? `${(value / 1024 / 1024).toFixed(1)} MB` : "--"; }
function time(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }

export function BusinessDashboard({ onNavigate }: { onNavigate: (workspace: string) => void }) {
  const [layout, setLayout] = useState<DashboardLayout>(() => layoutManager.load());
  const [core, setCore] = useState<DashboardCoreStatus | null>(null);
  const [workspace, setWorkspace] = useState<DashboardWorkspace | null>(null);
  const [updatedAt, setUpdatedAt] = useState(new Date());
  const [personalizeOpen, setPersonalizeOpen] = useState(false);
  const refresh = async () => { const [nextCore, nextWorkspace] = await Promise.all([fetchJson<DashboardCoreStatus>("/api/desktop-workspace/status"), fetchJson<DashboardWorkspace>("/api/workspace")]); setCore(nextCore); setWorkspace(nextWorkspace); setUpdatedAt(new Date()); };
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 15_000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { layoutManager.save(layout); }, [layout]);
  const hidden = (id: DashboardWidgetId) => layout.hidden.includes(id);
  const compact = (id: DashboardWidgetId) => layout.compact.includes(id);
  const activeProjects = workspace?.projects.filter((project) => project.id === workspace.activeProject?.id).length ?? 0;
  const storage = workspace?.projects.reduce((sum, project) => sum + project.productImages.reduce((total, image) => total + image.sizeBytes, 0), 0) ?? 0;
  const notifications = buildNotifications(core, workspace?.activeProject ?? null);
  return <div className="business-dashboard">
    <header className="business-header"><div><span>BUSINESS COMMAND CENTER</span><h2>Welcome back, <strong>creator.</strong></h2><p>{workspace?.activeProject?.name ?? "No active project"} · {updatedAt.toLocaleDateString(undefined, { weekday: "long", month: "long", day: "numeric" })}</p></div><div><button className="business-refresh" onClick={() => void refresh()}><RefreshCw size={15} />Refresh</button><button className="business-icon" onClick={() => setPersonalizeOpen(!personalizeOpen)} title="Personalize dashboard"><SlidersIcon /></button></div></header>
    {!hidden("kpis") && <Widget id="kpis" title="Business overview" detail="Prepared metrics" compact={compact("kpis")} onToggle={() => setLayout(layoutManager.toggleDensity(layout, "kpis"))}><div className="kpi-grid"><Kpi icon={<FolderKanban />} value={workspace?.projects.length ?? 0} label="Total projects" /><Kpi icon={<Activity />} value={activeProjects} label="Active projects" /><Kpi icon={<CheckCircle2 />} value="--" label="Completed projects" /><Kpi icon={<Bot />} value="--" label="AI tasks" /><Kpi icon={<Image />} value="--" label="Generated images" /><Kpi icon={<Video />} value="--" label="Generated videos" /><Kpi icon={<Gauge />} value="--" label="Marketing campaigns" /><Kpi icon={<Cpu />} value={bytes(storage)} label="Storage usage" /></div></Widget>}
    <div className="business-grid">
      {!hidden("ai") && <Widget id="ai" title="AI overview" detail="Read-only runtime presence" compact={compact("ai")} onToggle={() => setLayout(layoutManager.toggleDensity(layout, "ai"))}><div className="ai-overview"><div className={`ai-summary ${core?.aiCore ? "ready" : ""}`}><Sparkles size={21} /><div><b>{core?.aiCore ? "AI Core ready" : "AI Core unavailable"}</b><small>{core?.activeProject ?? "Waiting for local runtime"}</small></div></div><StatusRow label="Active AI agents" value={core?.aiCore ? "Prepared" : "Offline"} good={Boolean(core?.aiCore)} /><StatusRow label="Running tasks" value={core?.taskScheduler ? "Available" : "Not sampled"} good={Boolean(core?.taskScheduler)} /><StatusRow label="Queue status" value={core?.workflowEngine ? "Ready" : "Idle"} good={Boolean(core?.workflowEngine)} /><StatusRow label="Automation" value={core?.automationEngine ? "Connected" : "Standby"} good={Boolean(core?.automationEngine)} /><StatusRow label="Learning" value={core?.memoryFoundation ? "Connected" : "Standby"} good={Boolean(core?.memoryFoundation)} /></div></Widget>}
      {!hidden("actions") && <Widget id="actions" title="Quick actions" detail="Navigation only" compact={compact("actions")} onToggle={() => setLayout(layoutManager.toggleDensity(layout, "actions")}><div className="business-actions"><Action icon={<Plus />} label="New project" to="projects" onNavigate={onNavigate} /><Action icon={<FolderKanban />} label="Open project" to="projects" onNavigate={onNavigate} /><Action icon={<Sparkles />} label="AI Studio" to="ai" onNavigate={onNavigate} /><Action icon={<Image />} label="Image Studio" to="image" onNavigate={onNavigate} /><Action icon={<Video />} label="Video Studio" to="video" onNavigate={onNavigate} /><Action icon={<Gauge />} label="Marketing Studio" to="marketing" onNavigate={onNavigate} /><Action icon={<Lightbulb />} label="Knowledge Center" to="knowledge" onNavigate={onNavigate} /><Action icon={<Settings />} label="Settings" to="settings" onNavigate={onNavigate} /></div></Widget>}
      {!hidden("activity") && <Widget id="activity" title="Recent activity" detail="Live-ready activity feed" compact={compact("activity")} onToggle={() => setLayout(layoutManager.toggleDensity(layout, "activity")}><ActivityFeed projects={workspace?.projects ?? []} /></Widget>}
      {!hidden("projects") && <Widget id="projects" title="Recent projects" detail={`${workspace?.projects.length ?? 0} available`} compact={compact("projects")} onToggle={() => setLayout(layoutManager.toggleDensity(layout, "projects")}><RecentProjects projects={workspace?.projects ?? []} active={workspace?.activeProject?.id} onNavigate={onNavigate} /></Widget>}
      {!hidden("health") && <Widget id="health" title="System health" detail="Local readiness" compact={compact("health")} onToggle={() => setLayout(layoutManager.toggleDensity(layout, "health")}><div className="health-grid"><Health label="CPU usage" value="Not sampled" /><Health label="GPU usage" value="Not sampled" /><Health label="RAM usage" value="Not sampled" /><Health label="Disk usage" value={bytes(storage)} /><Health label="AI engine" value={core?.aiCore ? "Ready" : "Offline"} good={core?.aiCore} /><Health label="Database" value="Local workspace" good /><Health label="Memory" value={core?.memoryFoundation ? "Connected" : "Standby"} good={core?.memoryFoundation} /><Health label="Background services" value={core?.workflowEngine ? "Ready" : "Standby"} good={core?.workflowEngine} /></div></Widget>}
      {!hidden("notifications") && <Widget id="notifications" title="Notification center" detail="Interface history" compact={compact("notifications")} onToggle={() => setLayout(layoutManager.toggleDensity(layout, "notifications")}><div className="business-notifications">{notifications.map((item) => <article key={item.title}><i className={item.tone} /><div><b>{item.title}</b><p>{item.detail}</p></div><small>{item.when}</small></article>)}</div></Widget>}
    </div>
    {personalizeOpen && <aside className="dashboard-personalize"><header><div><span>DASHBOARD PERSONALIZATION</span><h3>Visible widgets</h3></div><button onClick={() => setPersonalizeOpen(false)}><X size={15} /></button></header>{widgets.map((widget) => <label key={widget.id}><span>{widget.label}<small>{layout.compact.includes(widget.id) ? "Compact" : "Expanded"}</small></span><div><button onClick={() => setLayout(layoutManager.toggleDensity(layout, widget.id))} title="Toggle widget density"><MoreHorizontal size={15} /></button><input type="checkbox" checked={!hidden(widget.id)} onChange={() => setLayout(layoutManager.toggleVisibility(layout, widget.id))} /></div></label>)}</aside>}
  </div>;
}
function SlidersIcon() { return <LayoutDashboard size={16} />; }
function Widget({ title, detail, compact, onToggle, children }: { id: DashboardWidgetId; title: string; detail: string; compact: boolean; onToggle: () => void; children: React.ReactNode }) { return <section className={`business-widget ${compact ? "compact" : ""}`}><header><div><span>{detail.toUpperCase()}</span><h3>{title}</h3></div><button onClick={onToggle} title="Toggle widget size"><MoreHorizontal size={16} /></button></header>{children}</section>; }
function Kpi({ icon, value, label }: { icon: React.ReactNode; value: string | number; label: string }) { return <article className="kpi"><span>{icon}</span><b>{value}</b><small>{label}</small></article>; }
function StatusRow({ label, value, good }: { label: string; value: string; good: boolean }) { return <div className="status-row"><span><i className={good ? "good" : ""} />{label}</span><b>{value}</b></div>; }
function Action({ icon, label, to, onNavigate }: { icon: React.ReactNode; label: string; to: string; onNavigate: (workspace: string) => void }) { return <button onClick={() => onNavigate(to)}><span>{icon}</span>{label}<ChevronRight size={13} /></button>; }
function ActivityFeed({ projects }: { projects: DashboardProject[] }) { const events = projects.slice(0, 4).map((project) => ({ icon: <FolderKanban />, title: `${project.name} updated`, detail: "Project workspace synchronization", when: time(project.modifiedAt) })); const entries = events.length ? events : [{ icon: <MonitorCog />, title: "Business dashboard ready", detail: "Waiting for project and runtime events", when: "Now" }]; return <div className="activity-feed">{entries.map((event) => <article key={event.title}><span>{event.icon}</span><div><b>{event.title}</b><p>{event.detail}</p></div><small>{event.when}</small></article>)}</div>; }
function RecentProjects({ projects, active, onNavigate }: { projects: DashboardProject[]; active?: string; onNavigate: (workspace: string) => void }) { return <div className="recent-projects">{projects.length ? projects.slice(0, 4).map((project) => <button key={project.id} onClick={() => onNavigate("projects")}><span className={project.id === active ? "current" : ""}><FolderKanban size={15} /></span><div><b>{project.name}</b><small>{project.productImages.length} source assets · {time(project.modifiedAt)}</small></div><ChevronRight size={14} /></button>) : <p>No projects yet. Create one from Projects to begin.</p>}</div>; }
function Health({ label, value, good = false }: { label: string; value: string; good?: boolean }) { return <div className="health"><span>{label}</span><b className={good ? "good" : ""}>{value}</b></div>; }
function buildNotifications(core: DashboardCoreStatus | null, project: DashboardProject | null) { return [{ tone: core?.aiCore ? "success" : "warning", title: core?.aiCore ? "AI Core connected" : "AI Core waiting", detail: core?.aiCore ? "Runtime status is available to the dashboard." : "The dashboard will update when the local runtime responds.", when: "Now" }, { tone: project ? "info" : "warning", title: project ? "Project context synchronized" : "No active project", detail: project ? `${project.name} is available across workspace surfaces.` : "Create or open a project to populate business context.", when: "Now" }, { tone: "info", title: "Dashboard personalization active", detail: "Widget visibility and density are saved locally.", when: "Now" }]; }