import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import type { AiCoreManager } from "../core/ai-core-manager.js";
import type { AiToolManager } from "../tool-management/tool-manager.js";
import { AiSecretsManager } from "./secrets-manager.js";
import { AUTHENTICATION_TYPES, CONNECTOR_CATEGORIES, type ConnectorDefinition, type ConnectorHealth, type ConnectorProfile, type ConnectorRequest, type ConnectorResponse, type ConnectorTransport, type HttpRequest, type HttpResponse, type RegisteredConnector } from "./types.js";

const healthy = (): ConnectorHealth => ({ available: false, authenticated: false, responseTimeMs: 0, executionCount: 0, failureCount: 0, errorRate: 0, stability: "healthy", lastCheckedAt: new Date().toISOString() });
const defaultTransport: ConnectorTransport = async (request) => {
  const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), request.timeoutMs);
  try { const response = await fetch(request.url, { method: request.method, headers: request.headers, body: request.body, redirect: "error", signal: controller.signal }); const text = await response.text(); let body: unknown = text; try { body = text ? JSON.parse(text) : {}; } catch { /* Non-JSON API responses are returned as text. */ }
    return { status: response.status, headers: Object.fromEntries(response.headers.entries()), body };
  } finally { clearTimeout(timer); }
};

/** Central local-first registry and secure executor for approved external service connectors. */
export class AiConnectorManager {
  readonly secrets = new AiSecretsManager();
  private root = "";
  private core: AiCoreManager | null = null;
  private tools: AiToolManager | null = null;
  private initialized = false;
  private readonly connectors = new Map<string, RegisteredConnector>();
  private readonly logs: Array<{ at: string; event: string; connectorId?: string; detail: string }> = [];

  constructor(private readonly transport: ConnectorTransport = defaultTransport) {}
  async initialize(core: AiCoreManager, tools: AiToolManager, storageRoot: string, secretsPassphrase?: string): Promise<void> { this.root = path.join(storageRoot, "connector-management"); this.core = core; this.tools = tools; await fs.mkdir(this.root, { recursive: true }); await this.secrets.initialize(storageRoot, secretsPassphrase); await this.restore(); this.initialized = true; }
  isInitialized(): boolean { return this.initialized; }
  list(category?: RegisteredConnector["category"]): RegisteredConnector[] { return [...this.connectors.values()].filter((connector) => connector.status !== "removed" && (!category || connector.category === category)).map((connector) => structuredClone(connector)); }
  get(connectorId: string): RegisteredConnector | null { const connector = this.connectors.get(connectorId); return connector && connector.status !== "removed" ? structuredClone(connector) : null; }
  getLogs(): ReadonlyArray<{ at: string; event: string; connectorId?: string; detail: string }> { return this.logs; }

  async register(definition: ConnectorDefinition): Promise<RegisteredConnector> { this.ensureReady(); this.validateDefinition(definition); if (this.connectors.has(definition.id) && this.connectors.get(definition.id)!.status !== "removed") throw new Error(`Connector already registered: ${definition.id}`); const now = new Date().toISOString(); const connector: RegisteredConnector = { ...definition, status: "registered", health: healthy(), profiles: {}, registeredAt: now, updatedAt: now }; this.connectors.set(connector.id, connector); await this.log("registration", connector.id, `Registered ${connector.name} v${connector.version}`); await this.persist(); return structuredClone(connector); }
  async discover(definitions: ConnectorDefinition[]): Promise<number> { let count = 0; for (const definition of definitions) if (!this.connectors.has(definition.id)) { await this.register(definition); count++; } return count; }
  async enable(connectorId: string): Promise<void> { const connector = this.require(connectorId); this.validateConnector(connector); connector.status = "enabled"; connector.updatedAt = new Date().toISOString(); await this.log("enabled", connectorId, "Connector enabled"); await this.persist(); }
  async disable(connectorId: string): Promise<void> { const connector = this.require(connectorId); connector.status = "disabled"; connector.updatedAt = new Date().toISOString(); await this.log("disabled", connectorId, "Connector disabled"); await this.persist(); }
  async remove(connectorId: string): Promise<void> { const connector = this.require(connectorId); connector.status = "removed"; connector.updatedAt = new Date().toISOString(); await this.log("removed", connectorId, "Connector removed; encrypted secret retained until explicitly deleted"); await this.persist(); }
  async update(connectorId: string, changes: Partial<Pick<ConnectorDefinition, "name" | "description" | "version" | "endpoint" | "authentication" | "retryPolicy" | "timeoutMs" | "fallbackConnectorId">>): Promise<RegisteredConnector> { const connector = this.require(connectorId); const candidate = { ...connector, ...changes }; this.validateDefinition(candidate); Object.assign(connector, changes, { updatedAt: new Date().toISOString() }); await this.log("update", connectorId, "Connector configuration updated"); await this.persist(); return structuredClone(connector); }
  async configureProfile(connectorId: string, profile: ConnectorProfile, configuration: RegisteredConnector["profiles"][ConnectorProfile]): Promise<RegisteredConnector> { const connector = this.require(connectorId); connector.profiles[profile] = structuredClone(configuration); connector.updatedAt = new Date().toISOString(); await this.log("profile", connectorId, `Configured ${profile} profile`); await this.persist(); return structuredClone(connector); }
  validate(connectorId: string): { valid: boolean; errors: string[] } { try { this.validateConnector(this.require(connectorId)); return { valid: true, errors: [] }; } catch (error) { return { valid: false, errors: [error instanceof Error ? error.message : String(error)] }; } }

  async execute(request: ConnectorRequest): Promise<ConnectorResponse> { return this.executeInternal(request, new Set()); }
  async monitor(connectorId?: string): Promise<Record<string, ConnectorHealth>> { const targets = connectorId ? [this.require(connectorId)] : this.list().map((connector) => this.require(connector.id)); for (const connector of targets) { connector.health.available = connector.status === "enabled"; connector.health.authenticated = !connector.authentication.secretId || (this.secrets.isUnlocked() && this.secrets.has(connector.authentication.secretId)); connector.health.lastCheckedAt = new Date().toISOString(); } await this.persist(); return Object.fromEntries(targets.map((connector) => [connector.id, structuredClone(connector.health)])); }
  getIntegrationStatus(): Record<string, boolean> { return { aiCore: Boolean(this.core), toolRegistry: Boolean(this.tools), toolManager: Boolean(this.tools), pluginManager: Boolean(this.core?.pluginManager), workflowEngine: Boolean(this.core?.workflowEngine), automationEngine: Boolean(this.core?.workflowEngine), communicationBus: Boolean(this.core?.communicationBus), taskScheduler: Boolean(this.core?.taskManager), multiAgentSystem: false }; }

  private async executeInternal(request: ConnectorRequest, visited: Set<string>): Promise<ConnectorResponse> {
    const started = performance.now(); let attempts = 0; let connector: RegisteredConnector | undefined;
    try {
      connector = this.require(request.connectorId); if (connector.status !== "enabled") throw new Error("Connector is not enabled"); if (visited.has(connector.id)) throw new Error("Connector fallback cycle detected"); visited.add(connector.id);
      this.validatePermissions(connector, request.permissions); const resolved = this.resolveProfile(connector, request.profile); this.validateDefinition(resolved); this.validateRequest(resolved, request); const headers = this.headers(resolved, request.headers); const url = new URL(request.path, resolved.endpoint.baseUrl).toString();
      let response: HttpResponse | undefined; let lastError: string | undefined;
      for (let attempt = 1; attempt <= resolved.retryPolicy.maxAttempts; attempt++) { attempts = attempt; try { response = await this.transport({ url, method: request.method ?? "GET", headers, body: request.body === undefined ? undefined : JSON.stringify(request.body), timeoutMs: resolved.timeoutMs }); if (response.status >= 200 && response.status < 300) { this.record(connector, started, true); await this.log("api-call", connector.id, `${request.method ?? "GET"} ${request.path} succeeded`); await this.persist(); return { connectorId: connector.id, status: "succeeded", statusCode: response.status, data: response.body, attempts, durationMs: Math.round(performance.now() - started) }; } lastError = `Remote service returned HTTP ${response.status}`; if (!resolved.retryPolicy.retryStatusCodes.includes(response.status)) break; await this.delay(this.retryDelay(resolved.retryPolicy, response.headers, attempt)); } catch (error) { lastError = error instanceof Error ? error.message : String(error); if (attempt < resolved.retryPolicy.maxAttempts) await this.delay(this.retryDelay(resolved.retryPolicy, {}, attempt)); } }
      throw new Error(lastError ?? "Connector request failed");
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error); if (connector) { connector.lastError = message; this.record(connector, started, false); await this.log("error", connector.id, message); await this.persist(); if (connector.fallbackConnectorId && !visited.has(connector.fallbackConnectorId)) { await this.log("fallback", connector.id, `Trying backup connector ${connector.fallbackConnectorId}`); const fallback = await this.executeInternal({ ...request, connectorId: connector.fallbackConnectorId }, visited); if (fallback.status === "succeeded" || fallback.status === "fallback-succeeded") return { ...fallback, status: "fallback-succeeded", fallbackConnectorId: fallback.connectorId }; } }
      return { connectorId: request.connectorId, status: "failed", error: message, attempts, durationMs: Math.round(performance.now() - started) };
    }
  }

  private resolveProfile(connector: RegisteredConnector, profile: ConnectorProfile | undefined): RegisteredConnector { return profile && connector.profiles[profile] ? { ...connector, ...connector.profiles[profile], endpoint: { ...connector.endpoint, ...connector.profiles[profile]?.endpoint }, authentication: { ...connector.authentication, ...connector.profiles[profile]?.authentication }, retryPolicy: { ...connector.retryPolicy, ...connector.profiles[profile]?.retryPolicy } } : connector; }
  private headers(connector: RegisteredConnector, requestHeaders: Record<string, string> | undefined): Record<string, string> { const headers = { ...(connector.endpoint.headers ?? {}), ...(requestHeaders ?? {}) }; if (Object.keys(headers).some((key) => ["authorization", "host", "proxy-authorization"].includes(key.toLowerCase()))) throw new Error("Sensitive transport headers are managed by the connector"); if (connector.authentication.secretId) { const secret = this.secrets.get(connector.authentication.secretId); if (connector.authentication.type === "api-key") headers[connector.authentication.headerName ?? "X-API-Key"] = secret; else if (connector.authentication.type === "custom") headers[connector.authentication.headerName ?? "Authorization"] = secret; else headers.Authorization = `${connector.authentication.tokenPrefix ?? "Bearer"} ${secret}`; } return headers; }
  private validateRequest(connector: RegisteredConnector, request: ConnectorRequest): void { if (!request.path.startsWith("/") || request.path.startsWith("//")) throw new Error("Connector path must be an absolute relative path"); if (connector.endpoint.allowedPaths?.length && !connector.endpoint.allowedPaths.some((prefix) => request.path.startsWith(prefix))) throw new Error("Connector path is not permitted"); }
  private validateConnector(connector: ConnectorDefinition): void { this.validateDefinition(connector); if (connector.fallbackConnectorId === connector.id) throw new Error("Connector cannot fall back to itself"); }
  private validateDefinition(connector: ConnectorDefinition): void { if (!/^[a-z0-9][a-z0-9.-]{2,100}$/i.test(connector.id)) throw new Error("Connector id is invalid"); if (!connector.name.trim() || !connector.description.trim() || !connector.provider.trim()) throw new Error("Connector name, description, and provider are required"); if (!CONNECTOR_CATEGORIES.includes(connector.category)) throw new Error("Connector category is invalid"); if (!AUTHENTICATION_TYPES.includes(connector.authentication.type)) throw new Error("Connector authentication type is invalid"); if (!/^\d+\.\d+\.\d+$/.test(connector.version)) throw new Error("Connector version must be semantic"); const endpoint = new URL(connector.endpoint.baseUrl); const local = endpoint.hostname === "localhost" || endpoint.hostname === "127.0.0.1" || endpoint.hostname === "::1"; if (endpoint.username || endpoint.password || endpoint.search || endpoint.hash) throw new Error("Connector endpoint cannot contain credentials, query parameters, or fragments"); if (endpoint.protocol !== "https:" && !(local && connector.endpoint.allowInsecureLocalhost && endpoint.protocol === "http:")) throw new Error("Connector endpoint must use HTTPS; HTTP is allowed only for explicit localhost development connectors"); if (!Number.isInteger(connector.timeoutMs) || connector.timeoutMs < 100 || connector.timeoutMs > 120000) throw new Error("Connector timeout must be between 100ms and 120000ms"); const policy = connector.retryPolicy; if (!Number.isInteger(policy.maxAttempts) || policy.maxAttempts < 1 || policy.maxAttempts > 5 || policy.initialDelayMs < 0 || policy.maxDelayMs < policy.initialDelayMs) throw new Error("Connector retry policy is invalid"); }
  private validatePermissions(connector: ConnectorDefinition, permissions: string[] | undefined): void { const granted = new Set(permissions ?? []); if (connector.requiredPermissions.some((permission) => !granted.has(permission))) throw new Error("Required connector permission was not granted"); }
  private record(connector: RegisteredConnector, started: number, success: boolean): void { connector.health.executionCount++; if (!success) connector.health.failureCount++; connector.health.responseTimeMs = Math.round(performance.now() - started); connector.health.errorRate = Math.round(connector.health.failureCount / connector.health.executionCount * 100); connector.health.stability = connector.health.errorRate >= 50 ? "unhealthy" : connector.health.errorRate ? "degraded" : "healthy"; connector.health.lastCheckedAt = new Date().toISOString(); }
  private retryDelay(policy: ConnectorDefinition["retryPolicy"], headers: Record<string, string>, attempt: number): number { const retryAfter = Number(headers["retry-after"]); if (Number.isFinite(retryAfter) && retryAfter >= 0) return Math.min(retryAfter * 1000, policy.maxDelayMs); return Math.min(policy.initialDelayMs * 2 ** (attempt - 1), policy.maxDelayMs); }
  private async delay(milliseconds: number): Promise<void> { if (milliseconds > 0) await new Promise<void>((resolve) => setTimeout(resolve, milliseconds)); }
  private require(connectorId: string): RegisteredConnector { this.ensureReady(); const connector = this.connectors.get(connectorId); if (!connector || connector.status === "removed") throw new Error(`Connector not found: ${connectorId}`); return connector; }
  private ensureReady(): void { if (!this.initialized || !this.tools) throw new Error("Connector Manager is not initialized"); }
  private async log(event: string, connectorId: string | undefined, detail: string): Promise<void> { const entry = { at: new Date().toISOString(), event, connectorId, detail }; this.logs.unshift(entry); this.logs.splice(100); await fs.appendFile(path.join(this.root, "connector-events.jsonl"), `${JSON.stringify(entry)}\n`, "utf8"); }
  private async restore(): Promise<void> { try { const saved = JSON.parse(await fs.readFile(path.join(this.root, "connectors.json"), "utf8")) as RegisteredConnector[]; for (const connector of saved) this.connectors.set(connector.id, connector); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } }
  private async persist(): Promise<void> { const target = path.join(this.root, "connectors.json"); const temporary = `${target}.${randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(this.list(), null, 2)}\n`, "utf8"); await fs.rename(temporary, target); }
}
