/**
 * Curated Professional Marketing, Branding, Customer & Sales Psychology catalog (Expansion Step 7).
 * Distinct from Storytelling Step 4 where concepts overlap (e.g. marketing-customer-journey vs customer-journey).
 */

import {
  BRANDING_DOMAIN_ID,
  CUSTOMER_PSYCHOLOGY_DOMAIN_ID,
  MARKETING_DOMAIN_ID,
  PROFESSIONAL_MARKETING_BRANDING_PSYCHOLOGY_VERSION,
  SALES_PSYCHOLOGY_DOMAIN_ID,
  type BrandingTopicId,
  type CustomerPsychologyTopicId,
  type MarketingTopicId,
  type MbpDomainBridge,
  type MbpTopicId,
  type ProfessionalMbpTopic,
  type SalesPsychologyTopicId,
  type VideoMarketingTopicId,
} from "./professional-marketing-branding-psychology-types.js";

type PartialTopic = Omit<ProfessionalMbpTopic, "knowledgeId" | "title" | "metadata"> & {
  knowledgeId?: string;
  title?: string;
};

function metaFor(
  domainId: ProfessionalMbpTopic["metadata"]["domainId"],
  category: ProfessionalMbpTopic["metadata"]["category"],
  confidenceScore: number
): ProfessionalMbpTopic["metadata"] {
  return {
    domainId,
    category,
    difficulty: confidenceScore >= 90 ? "advanced" : confidenceScore >= 84 ? "intermediate" : "foundation",
    expansionStep: 7,
    version: PROFESSIONAL_MARKETING_BRANDING_PSYCHOLOGY_VERSION,
    learningOnly: true,
    createsAdvertisements: false,
  };
}

function mkt(p: PartialTopic): ProfessionalMbpTopic {
  return { ...p, knowledgeId: p.knowledgeId ?? `mkt-${p.topicId}`, title: p.title ?? p.name, metadata: metaFor(MARKETING_DOMAIN_ID, "professional-marketing", p.confidenceScore) };
}
function brand(p: PartialTopic): ProfessionalMbpTopic {
  return { ...p, knowledgeId: p.knowledgeId ?? `brand-${p.topicId}`, title: p.title ?? p.name, metadata: metaFor(BRANDING_DOMAIN_ID, "professional-branding", p.confidenceScore) };
}
function cust(p: PartialTopic): ProfessionalMbpTopic {
  return { ...p, knowledgeId: p.knowledgeId ?? `cust-${p.topicId}`, title: p.title ?? p.name, metadata: metaFor(CUSTOMER_PSYCHOLOGY_DOMAIN_ID, "professional-customer-psychology", p.confidenceScore) };
}
function sales(p: PartialTopic): ProfessionalMbpTopic {
  return { ...p, knowledgeId: p.knowledgeId ?? `sales-${p.topicId}`, title: p.title ?? p.name, metadata: metaFor(SALES_PSYCHOLOGY_DOMAIN_ID, "professional-sales-psychology", p.confidenceScore) };
}
function vmkt(p: PartialTopic): ProfessionalMbpTopic {
  return { ...p, knowledgeId: p.knowledgeId ?? `vmkt-${p.topicId}`, title: p.title ?? p.name, metadata: metaFor(MARKETING_DOMAIN_ID, "professional-video-marketing", p.confidenceScore) };
}

export const PROFESSIONAL_MARKETING_TOPICS: ProfessionalMbpTopic[] = [
  mkt({
    topicId: "marketing-fundamentals",
    name: "Marketing Fundamentals",
    description: "Core marketing concepts: audience, value, channels, message, and measurement.",
    professionalDefinition: "Marketing fundamentals are the foundational practices for attracting, converting, and retaining customers through researched audience needs and measurable campaigns.",
    purpose: "Give AI Me a shared base for recommending any marketing strategy.",
    bestPractices: ["Start with audience and offer clarity", "One primary goal per campaign", "Measure leading and lagging indicators"],
    commonMistakes: ["Channel-first planning", "Vanity metrics without conversion"],
    workflow: ["Define goal", "Define audience", "Craft offer/message", "Choose channels", "Launch", "Measure", "Iterate"],
    professionalExamples: ["Launch brief: awareness → consideration creative with one KPI"],
    relatedTopics: ["marketing-funnel", "marketing-customer-journey", "product-marketing", "conversion-optimization"],
    relatedDomains: ["marketing-knowledge", "branding-knowledge", "customer-psychology", "product-knowledge"],
    keywords: ["marketing fundamentals", "campaign", "audience", "offer", "KPI"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  mkt({
    topicId: "digital-marketing",
    name: "Digital Marketing",
    description: "Online channel mix: search, social, email, web, and paid media working together.",
    professionalDefinition: "Digital marketing coordinates owned, earned, and paid digital channels to drive awareness, leads, and sales with trackable attribution.",
    purpose: "Recommend coherent digital channel strategies for commercial video and content.",
    bestPractices: ["Align creative to channel norms", "Track UTMs and conversions", "Retarget with stage-appropriate messages"],
    commonMistakes: ["Same creative on every channel", "No attribution plan"],
    workflow: ["Map funnel stages to channels", "Brief creative per channel", "Set tracking", "Optimize weekly"],
    professionalExamples: ["YouTube awareness + Meta retargeting + email nurture"],
    relatedTopics: ["social-media-marketing", "performance-marketing", "content-marketing", "video-marketing"],
    relatedDomains: ["marketing-knowledge", "social-media-knowledge", "rendering-knowledge"],
    keywords: ["digital marketing", "channels", "paid media", "attribution", "online"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  mkt({
    topicId: "product-marketing",
    name: "Product Marketing",
    description: "Positioning, packaging messages, and go-to-market for a specific product.",
    professionalDefinition: "Product marketing translates product capabilities into audience-relevant benefits, competitive positioning, and launch narratives.",
    purpose: "Ensure creative and video present the right product story to the right buyer.",
    bestPractices: ["Lead with outcomes", "Differentiate clearly", "Align sales and creative messaging"],
    commonMistakes: ["Feature dumps", "Positioning that ignores competitors"],
    workflow: ["ICP", "Positioning", "Messaging pillars", "Launch assets", "Enable sales"],
    professionalExamples: ["Feature → benefit matrix feeding demo video script"],
    relatedTopics: ["value-proposition", "feature-presentation", "benefit-presentation", "product-demonstration"],
    relatedDomains: ["marketing-knowledge", "product-knowledge", "branding-knowledge", "sales-psychology"],
    keywords: ["product marketing", "positioning", "GTM", "messaging", "ICP"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  mkt({
    topicId: "content-marketing",
    name: "Content Marketing",
    description: "Creating valuable content that builds trust and demand over time.",
    professionalDefinition: "Content marketing attracts and nurtures audiences by publishing useful, consistent content that supports brand authority and eventual conversion.",
    purpose: "Guide long-form and series video strategies beyond single ads.",
    bestPractices: ["Serve a real audience job", "Consistency over virality spikes", "CTA soft until trust exists"],
    commonMistakes: ["Content with no distribution plan", "Always selling"],
    workflow: ["Audience jobs", "Content pillars", "Calendar", "Produce", "Distribute", "Repurpose"],
    professionalExamples: ["How-to series that warms leads into product demo CTAs"],
    relatedTopics: ["video-marketing", "brand-trust", "authority", "lead-generation"],
    relatedDomains: ["marketing-knowledge", "branding-knowledge", "storytelling-knowledge", "social-media-knowledge"],
    keywords: ["content marketing", "content pillars", "nurture", "authority content"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  mkt({
    topicId: "video-marketing",
    name: "Video Marketing",
    description: "Using video as a primary channel for awareness, education, and conversion.",
    professionalDefinition: "Video marketing plans, produces, and distributes video assets mapped to funnel stages and platform behaviors.",
    purpose: "Connect video creative choices to marketing outcomes.",
    bestPractices: ["Map each video to a funnel job", "Optimize first 3 seconds", "Design for sound-off", "Measure retention and CVR"],
    commonMistakes: ["One video for every stage", "Ignoring platform length norms"],
    workflow: ["Goal", "Audience stage", "Concept", "Produce", "Distribute", "Optimize"],
    professionalExamples: ["Hook ad → demo retarget → testimonial closer"],
    relatedTopics: ["hook-creation", "audience-retention", "video-cta-placement", "performance-marketing"],
    relatedDomains: ["marketing-knowledge", "video-production-knowledge", "video-editing-knowledge", "social-media-knowledge"],
    keywords: ["video marketing", "video ads", "funnel video", "video strategy"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  mkt({
    topicId: "social-media-marketing",
    name: "Social Media Marketing",
    description: "Campaign and creative strategy across social platforms (high-level; not platform-deep Step 8).",
    professionalDefinition: "Social media marketing uses platform-native formats, community behaviors, and paid/organic mix to grow reach and conversion.",
    purpose: "Frame social as a system without duplicating deep platform packs (Step 8).",
    bestPractices: ["Native aspect and length", "Hook-first creative", "Test hooks separately from bodies"],
    commonMistakes: ["TV spots cropped for social", "Ignoring comments/social proof"],
    workflow: ["Choose platforms", "Adapt creative", "Schedule/boost", "Engage", "Learn"],
    professionalExamples: ["Vertical hook variants testing 3 openings for same demo body"],
    relatedTopics: ["video-marketing", "first-3-seconds-strategy", "social-proof", "attention-psychology"],
    relatedDomains: ["marketing-knowledge", "social-media-knowledge", "branding-knowledge"],
    keywords: ["social media marketing", "social ads", "organic social", "platform native"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  mkt({
    topicId: "influencer-marketing",
    name: "Influencer Marketing",
    description: "Partnering with creators for reach, trust transfer, and authentic product context.",
    professionalDefinition: "Influencer marketing leverages creator credibility and audience fit to distribute product stories with negotiated creative control.",
    purpose: "Recommend when creator-led video outperforms brand-only creative.",
    bestPractices: ["Prioritize audience fit over vanity followers", "Brief outcomes not scripts only", "Disclose partnerships"],
    commonMistakes: ["Wrong creator fit", "Over-scripting killing authenticity"],
    workflow: ["Define ICP", "Shortlist creators", "Brief", "Approve", "Measure codes/links"],
    professionalExamples: ["Micro-influencer unboxing with unique discount code"],
    relatedTopics: ["social-proof", "trust-building", "product-demonstration", "brand-trust"],
    relatedDomains: ["marketing-knowledge", "social-media-knowledge", "customer-psychology", "branding-knowledge"],
    keywords: ["influencer", "creator", "UGC", "sponsored", "affiliate"],
    confidenceScore: 90,
    qualityScore: 89,
  }),
  mkt({
    topicId: "performance-marketing",
    name: "Performance Marketing",
    description: "Paid acquisition optimized to measurable actions (lead, purchase, install).",
    professionalDefinition: "Performance marketing is accountable paid media focused on CPA/ROAS with rapid creative testing and funnel instrumentation.",
    purpose: "Guide conversion-oriented video and offer creative.",
    bestPractices: ["One primary conversion event", "Iterate hooks weekly", "Separate testing from scaling"],
    commonMistakes: ["Scaling unproven creatives", "Optimizing for clicks only"],
    workflow: ["Define KPI", "Build test matrix", "Launch", "Kill/scale", "Refresh creative"],
    professionalExamples: ["3 hooks × 2 bodies × 2 CTAs multivariate test"],
    relatedTopics: ["conversion-optimization", "hook-creation", "cta-strategy", "marketing-funnel"],
    relatedDomains: ["marketing-knowledge", "sales-psychology", "social-media-knowledge", "video-editing-knowledge"],
    keywords: ["performance marketing", "ROAS", "CPA", "paid ads", "creative testing"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  mkt({
    topicId: "marketing-funnel",
    name: "Marketing Funnel",
    description: "Stages from awareness to advocacy and the creative jobs at each stage.",
    professionalDefinition: "The marketing funnel models progression through awareness, consideration, conversion, and loyalty—each needing different proof and CTA intensity.",
    purpose: "Match video concepts to funnel stage instead of one-size creative.",
    bestPractices: ["Stage-specific KPIs", "Increase proof deeper in funnel", "Align CTA to stage"],
    commonMistakes: ["Hard sell to cold traffic", "No remarketing bridge"],
    workflow: ["Map stages", "Assign assets", "Set KPIs", "Connect retargeting"],
    professionalExamples: ["TOF hook film → MOF demo → BOF offer + urgency"],
    relatedTopics: ["marketing-customer-journey", "performance-marketing", "video-marketing", "conversion-optimization"],
    relatedDomains: ["marketing-knowledge", "customer-psychology", "sales-psychology", "social-media-knowledge"],
    keywords: ["marketing funnel", "TOF", "MOF", "BOF", "awareness consideration"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  mkt({
    topicId: "marketing-customer-journey",
    name: "Customer Journey",
    description: "Marketing-stage journey mapping (distinct from narrative customer-journey in storytelling knowledge).",
    professionalDefinition: "Marketing customer journey maps touchpoints and decisions from first attention to retention, guiding message sequence and channel choice.",
    purpose: "Recommend journey-aware campaigns without duplicating storytelling narrative journey knowledge.",
    bestPractices: ["Map jobs-to-be-done per stage", "Remove friction points", "Use video where attention is highest"],
    commonMistakes: ["Assuming linear journeys", "Ignoring post-purchase"],
    workflow: ["Research journey", "Find drop-offs", "Brief creative for gaps", "Measure stage conversion"],
    professionalExamples: ["Retarget cart abandoners with objection-handling demo"],
    relatedTopics: ["marketing-funnel", "customer-behavior", "decision-making", "customer-retention"],
    relatedDomains: ["marketing-knowledge", "customer-psychology", "social-media-knowledge", "product-knowledge"],
    keywords: ["customer journey", "touchpoints", "journey map", "marketing journey"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  mkt({
    topicId: "lead-generation",
    name: "Lead Generation",
    description: "Capturing qualified interest for sales or nurture.",
    professionalDefinition: "Lead generation attracts and captures prospect information or intent signals through offers, content, and CTAs designed for qualification.",
    purpose: "Connect video/content hooks to lead capture mechanisms.",
    bestPractices: ["Offer matches awareness level", "Minimize form friction", "Qualify with intent signals"],
    commonMistakes: ["Asking too much too soon", "Leads with no nurture"],
    workflow: ["Define MQL", "Create lead magnet", "Drive traffic", "Capture", "Nurture"],
    professionalExamples: ["Webinar signup CTA after educational video"],
    relatedTopics: ["content-marketing", "cta-strategy", "value-proposition", "conversion-optimization"],
    relatedDomains: ["marketing-knowledge", "sales-psychology", "customer-psychology"],
    keywords: ["lead generation", "leads", "MQL", "lead magnet", "capture"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  mkt({
    topicId: "conversion-optimization",
    name: "Conversion Optimization",
    description: "Improving the rate of desired actions through creative, offer, and UX tests.",
    professionalDefinition: "Conversion optimization systematically tests messages, creative, offers, and paths to increase the percentage of visitors who take the target action.",
    purpose: "Guide iterative improvement of video CTAs and landing alignment.",
    bestPractices: ["One hypothesis per test", "Statistically sufficient samples", "Align ad promise to landing"],
    commonMistakes: ["Changing too many variables", "Message mismatch ad→page"],
    workflow: ["Baseline", "Hypothesis", "Variant", "Test", "Implement winner"],
    professionalExamples: ["CTA copy test: Shop now vs See fit guide"],
    relatedTopics: ["cta-strategy", "performance-marketing", "offer-presentation", "video-cta-placement"],
    relatedDomains: ["marketing-knowledge", "sales-psychology", "social-media-knowledge", "rendering-knowledge"],
    keywords: ["conversion optimization", "CRO", "A/B test", "CVR"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
];

export const PROFESSIONAL_BRANDING_TOPICS: ProfessionalMbpTopic[] = [
  brand({
    topicId: "brand-identity",
    name: "Brand Identity",
    description: "The distinctive system of meaning, marks, and expressions that make a brand recognizable.",
    professionalDefinition: "Brand identity is the intentional set of verbal and visual assets—name, logo, colors, type, voice—that encode what the brand stands for.",
    purpose: "Anchor all creative decisions in a coherent identity.",
    bestPractices: ["Document core identity elements", "Prioritize recognition over novelty", "Keep identity flexible for platforms"],
    commonMistakes: ["Inconsistent marks", "Identity that doesn’t match audience"],
    workflow: ["Audit", "Define pillars", "Design system", "Roll out"],
    professionalExamples: ["Identity kit driving all video end cards and lower thirds"],
    relatedTopics: ["visual-identity", "brand-guidelines", "logo-usage", "brand-voice"],
    relatedDomains: ["branding-knowledge", "marketing-knowledge", "product-knowledge"],
    keywords: ["brand identity", "identity system", "brand marks"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  brand({
    topicId: "brand-positioning",
    name: "Brand Positioning",
    description: "How the brand is meant to be perceived versus alternatives in the customer’s mind.",
    professionalDefinition: "Brand positioning articulates the target, frame of reference, point of difference, and reason to believe that define competitive place.",
    purpose: "Keep messaging and creative differentiated.",
    bestPractices: ["One sharp difference", "Proof that supports the claim", "Repeat consistently"],
    commonMistakes: ["Generic ‘quality’ positioning", "Positioning nobody believes"],
    workflow: ["Research", "Draft positioning", "Test", "Lock into briefs"],
    professionalExamples: ["Position: fastest setup for non-technical teams — shown in 20s demo"],
    relatedTopics: ["value-proposition", "brand-story", "product-marketing", "authority"],
    relatedDomains: ["branding-knowledge", "marketing-knowledge", "sales-psychology", "product-knowledge"],
    keywords: ["brand positioning", "differentiation", "competitive frame"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  brand({
    topicId: "brand-awareness",
    name: "Brand Awareness",
    description: "Making the brand known and easily recalled in buying situations.",
    professionalDefinition: "Brand awareness is the extent to which audiences recognize and recall a brand, built through distinctive assets and repeated distinctive exposures.",
    purpose: "Guide top-funnel video and distinctive brand coding.",
    bestPractices: ["Use distinctive brand assets early", "Frequency with variation", "Measure aided/unaided recall proxies"],
    commonMistakes: ["Logo-only with no memory structures", "Inconsistent cues"],
    workflow: ["Define assets", "TOF creative", "Distribute", "Measure reach/recall proxies"],
    professionalExamples: ["Sonic logo + color flash in first 1s of every ad"],
    relatedTopics: ["first-3-seconds-strategy", "logo-usage", "visual-identity", "hook-creation"],
    relatedDomains: ["branding-knowledge", "marketing-knowledge", "social-media-knowledge"],
    keywords: ["brand awareness", "recognition", "recall", "distinctive assets"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  brand({
    topicId: "brand-trust",
    name: "Brand Trust",
    description: "Credibility and reliability perceptions that reduce purchase risk.",
    professionalDefinition: "Brand trust is the audience belief that the brand will deliver as promised—built via proof, consistency, transparency, and social evidence.",
    purpose: "Recommend trust cues in creative and claims.",
    bestPractices: ["Show real proof", "Consistent delivery of promises", "Avoid hype that breaks trust"],
    commonMistakes: ["Fake urgency", "Unsubstantiated claims"],
    workflow: ["List trust gaps", "Choose proof types", "Place in creative", "Verify claims"],
    professionalExamples: ["Verified reviews + demo evidence in mid-funnel video"],
    relatedTopics: ["trust-building", "social-proof", "authority", "brand-consistency"],
    relatedDomains: ["branding-knowledge", "customer-psychology", "sales-psychology", "marketing-knowledge"],
    keywords: ["brand trust", "credibility", "reliability", "proof"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  brand({
    topicId: "brand-consistency",
    name: "Brand Consistency",
    description: "Keeping identity and message coherent across touchpoints and time.",
    professionalDefinition: "Brand consistency is disciplined reuse of verbal, visual, and experiential cues so recognition and meaning compound.",
    purpose: "Prevent fragmented campaigns that dilute memory.",
    bestPractices: ["Follow guidelines", "Allow controlled flexibility", "QA across channels"],
    commonMistakes: ["Every campaign reinvented", "Rigid rules that break platforms"],
    workflow: ["Guidelines", "Templates", "Review gates", "Audit"],
    professionalExamples: ["Same end-card layout across all video lengths"],
    relatedTopics: ["brand-guidelines", "visual-identity", "brand-voice", "logo-usage"],
    relatedDomains: ["branding-knowledge", "marketing-knowledge", "social-media-knowledge", "rendering-knowledge"],
    keywords: ["brand consistency", "coherence", "guidelines adherence"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  brand({
    topicId: "brand-voice",
    name: "Brand Voice",
    description: "The consistent personality of brand language across copy and scripts.",
    professionalDefinition: "Brand voice is the stable tonal and linguistic personality—formal, witty, expert, caring—applied across scripts, captions, and CTAs.",
    purpose: "Keep video scripts and CTAs sounding like the same brand.",
    bestPractices: ["Define do/don’t examples", "Adapt intensity not personality", "Align VO casting to voice"],
    commonMistakes: ["Tone whiplash across ads", "Voice that insults the audience"],
    workflow: ["Voice chart", "Script against chart", "Review", "Caption match"],
    professionalExamples: ["Expert-calm VO across demo and testimonial edits"],
    relatedTopics: ["brand-story", "brand-guidelines", "ending-strategy", "cta-strategy"],
    relatedDomains: ["branding-knowledge", "storytelling-knowledge", "marketing-knowledge"],
    keywords: ["brand voice", "tone", "verbal identity", "script voice"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  brand({
    topicId: "brand-story",
    name: "Brand Story",
    description: "The overarching narrative of origin, belief, and promise (identity-level, not film craft).",
    professionalDefinition: "Brand story is the strategic narrative of why the brand exists, whom it serves, and what change it stands for—guiding campaigns without replacing tactical storytelling craft.",
    purpose: "Inform film concepts while remaining distinct from storytelling-domain brand-storytelling technique.",
    bestPractices: ["Truth over mythology", "Human stakes", "Connect to product proof"],
    commonMistakes: ["Purpose-washing", "Story disconnected from offer"],
    workflow: ["Origin/belief", "Audience role", "Promise", "Proof pillars"],
    professionalExamples: ["Founder problem story feeding annual brand film pillars"],
    relatedTopics: ["brand-positioning", "brand-identity", "emotional-triggers", "brand-trust"],
    relatedDomains: ["branding-knowledge", "storytelling-knowledge", "marketing-knowledge", "customer-psychology"],
    keywords: ["brand story", "origin story", "brand narrative", "promise"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  brand({
    topicId: "brand-guidelines",
    name: "Brand Guidelines",
    description: "Documented rules for using identity assets correctly.",
    professionalDefinition: "Brand guidelines specify approved usage of logo, color, type, imagery, voice, and motion so teams execute consistently.",
    purpose: "Enable quality control across video and design outputs.",
    bestPractices: ["Include video/motion sections", "Show correct/incorrect examples", "Keep accessible to vendors"],
    commonMistakes: ["Guidelines never updated", "No motion rules"],
    workflow: ["Compile rules", "Add examples", "Train teams", "Enforce in review"],
    professionalExamples: ["Motion section: allowed easings, logo clear space in end cards"],
    relatedTopics: ["logo-usage", "visual-identity", "brand-consistency", "brand-voice"],
    relatedDomains: ["branding-knowledge", "marketing-knowledge", "rendering-knowledge"],
    keywords: ["brand guidelines", "brand book", "usage rules", "style guide"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  brand({
    topicId: "logo-usage",
    name: "Logo Usage",
    description: "Correct placement, clear space, colorways, and misuse prevention for logos.",
    professionalDefinition: "Logo usage rules define how the mark may appear—sizing, clear space, backgrounds, and forbidden treatments—across video frames and end cards.",
    purpose: "Protect recognition and legal trademark presentation.",
    bestPractices: ["Respect clear space", "Prefer approved colorways", "Avoid stretch/rotate/effects that break marks"],
    commonMistakes: ["Low-contrast logo on busy BG", "Animated distortion"],
    workflow: ["Check guidelines", "Place in safe area", "Verify contrast", "Approve"],
    professionalExamples: ["End card logo centered with required padding and brand field"],
    relatedTopics: ["brand-awareness", "visual-identity", "brand-guidelines", "ending-strategy"],
    relatedDomains: ["branding-knowledge", "marketing-knowledge", "product-knowledge"],
    keywords: ["logo usage", "clear space", "lockup", "trademark"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  brand({
    topicId: "visual-identity",
    name: "Visual Identity",
    description: "The visual system—color, type, imagery, layout—that expresses the brand.",
    professionalDefinition: "Visual identity is the coordinated graphic system that makes brand materials instantly recognizable and emotionally on-tone.",
    purpose: "Guide art direction for video frames, motion, and product presentation.",
    bestPractices: ["Limit palette", "Define photography style", "Design for motion-safe layouts"],
    commonMistakes: ["Clashing campaign art direction", "Illegible type on video"],
    workflow: ["System components", "Templates", "Art direction brief", "QA frames"],
    professionalExamples: ["Consistent color grade and type system across all SKUs’ videos"],
    relatedTopics: ["brand-identity", "brand-consistency", "logo-usage", "product-perception"],
    relatedDomains: ["branding-knowledge", "product-knowledge", "marketing-knowledge", "rendering-knowledge"],
    keywords: ["visual identity", "brand visuals", "art direction", "design system"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
];

export const PROFESSIONAL_CUSTOMER_PSYCHOLOGY_TOPICS: ProfessionalMbpTopic[] = [
  cust({
    topicId: "customer-behavior",
    name: "Customer Behavior",
    description: "Observable patterns in how customers notice, evaluate, buy, and return.",
    professionalDefinition: "Customer behavior knowledge explains patterned actions and contexts that shape attention, evaluation, purchase, and loyalty.",
    purpose: "Ground creative recommendations in how people actually act.",
    bestPractices: ["Observe real journeys", "Separate stated vs revealed preference", "Design for defaults and friction"],
    commonMistakes: ["Assuming rational shoppers only", "Ignoring context of use"],
    workflow: ["Research behavior", "Map frictions", "Brief creative", "Measure behavior change"],
    professionalExamples: ["Mobile users skip intros → mandate hook-first edits"],
    relatedTopics: ["attention-psychology", "decision-making", "marketing-customer-journey", "buying-motivation"],
    relatedDomains: ["customer-psychology", "marketing-knowledge", "social-media-knowledge"],
    keywords: ["customer behavior", "buyer behavior", "usage context"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  cust({
    topicId: "buying-motivation",
    name: "Buying Motivation",
    description: "Why people buy—functional, emotional, social, and identity motives.",
    professionalDefinition: "Buying motivation covers the drivers—jobs-to-be-done, status, fear reduction, belonging—that make offers relevant.",
    purpose: "Choose which motive a video should activate.",
    bestPractices: ["Pick one primary motive", "Show motive visually", "Align CTA to motive"],
    commonMistakes: ["Mixed motives muddying message", "Feature focus with no motive"],
    workflow: ["Interview motives", "Prioritize", "Script to motive", "Test"],
    professionalExamples: ["Status motive: premium unboxing; safety motive: warranty proof"],
    relatedTopics: ["emotional-triggers", "value-proposition", "benefit-presentation", "product-perception"],
    relatedDomains: ["customer-psychology", "sales-psychology", "marketing-knowledge", "product-knowledge"],
    keywords: ["buying motivation", "motives", "jobs to be done", "desire"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  cust({
    topicId: "emotional-triggers",
    name: "Emotional Triggers",
    description: "Emotions that move attention and action—used ethically in commercial creative.",
    professionalDefinition: "Emotional triggers are affective cues (relief, pride, fear of loss, joy) that intensify engagement when matched to brand and truth.",
    purpose: "Recommend emotional tone for hooks and stories without manipulation that breaks trust.",
    bestPractices: ["Earn emotion with truth", "Match brand ethics", "Resolve tension responsibly"],
    commonMistakes: ["Fearmongering", "Emotion unrelated to offer"],
    workflow: ["Choose emotion", "Design trigger moment", "Resolve with product role", "CTA"],
    professionalExamples: ["Relief after chaos messy-kitchen → clean system demo"],
    relatedTopics: ["buying-motivation", "attention-psychology", "hook-creation", "urgency"],
    relatedDomains: ["customer-psychology", "storytelling-knowledge", "sales-psychology", "branding-knowledge"],
    keywords: ["emotional triggers", "emotion", "affect", "feeling cues"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  cust({
    topicId: "trust-building",
    name: "Trust Building",
    description: "Psychological and creative tactics that increase perceived trustworthiness.",
    professionalDefinition: "Trust building reduces perceived risk via proof, transparency, consistency, and credible messengers.",
    purpose: "Strengthen mid/bottom-funnel creative.",
    bestPractices: ["Specific proof > vague claims", "Show real use", "Consistent brand cues"],
    commonMistakes: ["Stocky fake testimonials", "Overclaiming"],
    workflow: ["Identify risks", "Select proof", "Place in journey", "Substantiate"],
    professionalExamples: ["Demo + verified review + clear return policy line"],
    relatedTopics: ["brand-trust", "social-proof", "authority", "customer-satisfaction"],
    relatedDomains: ["customer-psychology", "branding-knowledge", "sales-psychology", "marketing-knowledge"],
    keywords: ["trust building", "credibility", "risk reduction", "proof"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  cust({
    topicId: "decision-making",
    name: "Decision Making",
    description: "How buyers choose under limited attention, bias, and uncertainty.",
    professionalDefinition: "Decision-making psychology covers heuristics, evaluation criteria, and friction that shape yes/no/wait outcomes.",
    purpose: "Design offers and CTAs that support clear decisions.",
    bestPractices: ["Reduce cognitive load", "Make next step obvious", "Address top objections"],
    commonMistakes: ["Too many choices", "Hidden price/terms"],
    workflow: ["List decision criteria", "Simplify options", "Script clarity", "Test CTA"],
    professionalExamples: ["Single plan highlighted as recommended in offer scene"],
    relatedTopics: ["objection-handling", "offer-presentation", "cta-strategy", "buying-motivation"],
    relatedDomains: ["customer-psychology", "sales-psychology", "marketing-knowledge"],
    keywords: ["decision making", "heuristics", "choice", "friction"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  cust({
    topicId: "attention-psychology",
    name: "Attention Psychology",
    description: "How attention is captured, held, and lost in media environments.",
    professionalDefinition: "Attention psychology explains salience, novelty, pattern interrupt, and cognitive limits that govern whether creative is noticed and retained.",
    purpose: "Inform hooks, pacing, and visual hierarchy for video marketing.",
    bestPractices: ["Pattern interrupt early", "One focal point", "Reward attention with clarity"],
    commonMistakes: ["Slow opens on social", "Competing stimuli"],
    workflow: ["Design hook", "Remove rivals", "Pace reveals", "Measure drop-off"],
    professionalExamples: ["First-frame motion + question overlay before logo"],
    relatedTopics: ["hook-creation", "first-3-seconds-strategy", "audience-retention", "emotional-triggers"],
    relatedDomains: ["customer-psychology", "marketing-knowledge", "social-media-knowledge", "storytelling-knowledge"],
    keywords: ["attention", "salience", "pattern interrupt", "focus"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  cust({
    topicId: "product-perception",
    name: "Product Perception",
    description: "How sensory and presentation cues shape perceived quality and fit.",
    professionalDefinition: "Product perception is the constructed sense of quality, efficacy, and desirability formed from visuals, demos, context, and claims.",
    purpose: "Recommend presentation strategies for products in video and photography contexts.",
    bestPractices: ["Show material truth", "Context of use", "Consistent quality cues"],
    commonMistakes: ["Misleading scale", "Beauty without function"],
    workflow: ["Define desired perception", "Choose cues", "Shoot/animate", "Validate with audience"],
    professionalExamples: ["Macro texture + real-use demo to raise quality perception"],
    relatedTopics: ["benefit-presentation", "feature-presentation", "visual-identity", "product-demonstration"],
    relatedDomains: ["customer-psychology", "product-knowledge", "branding-knowledge", "marketing-knowledge"],
    keywords: ["product perception", "perceived quality", "desirability", "presentation"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  cust({
    topicId: "consumer-expectations",
    name: "Consumer Expectations",
    description: "What audiences expect from category, brand, and platform experiences.",
    professionalDefinition: "Consumer expectations are anticipated standards for quality, speed, claims, and creative norms that shape satisfaction and trust.",
    purpose: "Avoid creative that violates category or platform expectations unintentionally.",
    bestPractices: ["Know category codes", "Exceed on the brand difference", "Set expectations ads can keep"],
    commonMistakes: ["Overpromising in hooks", "Breaking platform norms without intent"],
    workflow: ["Audit expectations", "Align promise", "Deliver proof", "Measure satisfaction"],
    professionalExamples: ["Beauty ad shows texture truth to meet ‘what it really looks like’ expectation"],
    relatedTopics: ["customer-satisfaction", "brand-trust", "product-perception", "first-3-seconds-strategy"],
    relatedDomains: ["customer-psychology", "branding-knowledge", "marketing-knowledge", "social-media-knowledge"],
    keywords: ["consumer expectations", "category norms", "promise", "standards"],
    confidenceScore: 90,
    qualityScore: 89,
  }),
  cust({
    topicId: "customer-satisfaction",
    name: "Customer Satisfaction",
    description: "Post-experience evaluation that drives reviews, repeat, and referrals.",
    professionalDefinition: "Customer satisfaction is the gap between expected and experienced outcomes; creative should set honest expectations and reinforce success.",
    purpose: "Connect marketing promises to post-purchase reality.",
    bestPractices: ["Promise what product delivers", "Onboard via content", "Invite fair reviews"],
    commonMistakes: ["Hype that causes disappointment", "Ignoring onboarding content"],
    workflow: ["Align claims", "Support first use", "Collect feedback", "Close loop in creative"],
    professionalExamples: ["Setup video reduces return rate and boosts 5-star reviews"],
    relatedTopics: ["consumer-expectations", "customer-retention", "trust-building", "content-marketing"],
    relatedDomains: ["customer-psychology", "marketing-knowledge", "product-knowledge"],
    keywords: ["customer satisfaction", "CSAT", "expectations gap", "reviews"],
    confidenceScore: 90,
    qualityScore: 89,
  }),
  cust({
    topicId: "customer-retention",
    name: "Customer Retention",
    description: "Keeping customers active and loyal after the first purchase.",
    professionalDefinition: "Customer retention strategies increase repeat purchase and advocacy through value reinforcement, habit, community, and service.",
    purpose: "Extend video marketing beyond acquisition into loyalty content.",
    bestPractices: ["Reinforce value in use", "Educate for habits", "Win-back with relevant offers"],
    commonMistakes: ["Only acquiring, never nurturing", "Generic win-back spam"],
    workflow: ["Identify churn reasons", "Build retention content", "Trigger journeys", "Measure LTV"],
    professionalExamples: ["Tips series for power users; loyalty offer film"],
    relatedTopics: ["customer-satisfaction", "marketing-customer-journey", "brand-trust", "content-marketing"],
    relatedDomains: ["customer-psychology", "marketing-knowledge", "branding-knowledge"],
    keywords: ["customer retention", "loyalty", "LTV", "churn", "repeat"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
];

export const PROFESSIONAL_SALES_PSYCHOLOGY_TOPICS: ProfessionalMbpTopic[] = [
  sales({
    topicId: "persuasion-principles",
    name: "Persuasion Principles",
    description: "Ethical frameworks for influencing decisions (e.g., Cialdini-style levers) in creative form.",
    professionalDefinition: "Persuasion principles are structured influence levers—proof, authority, reciprocity, consistency, liking, scarcity—applied transparently in offers and creative.",
    purpose: "Recommend which persuasion lever fits the funnel stage and brand.",
    bestPractices: ["One primary lever per asset", "Never fabricate", "Pair with real value"],
    commonMistakes: ["Stacking all levers", "Dark patterns"],
    workflow: ["Choose lever", "Design proof", "Place in script", "Compliance check"],
    professionalExamples: ["Authority: expert demo; Social proof: review montage"],
    relatedTopics: ["social-proof", "authority", "scarcity", "reciprocity", "urgency"],
    relatedDomains: ["sales-psychology", "customer-psychology", "marketing-knowledge", "branding-knowledge"],
    keywords: ["persuasion", "influence", "Cialdini", "levers"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  sales({
    topicId: "value-proposition",
    name: "Value Proposition",
    description: "Clear statement of value for a specific customer and alternative.",
    professionalDefinition: "A value proposition articulates the meaningful benefit a customer gets, for whom, and why the brand wins versus alternatives.",
    purpose: "Anchor scripts, headlines, and offers.",
    bestPractices: ["Specific outcomes", "Audience qualifier", "Differentiator + proof"],
    commonMistakes: ["Vague value", "Feature labeled as value"],
    workflow: ["Draft", "Test clarity", "Map to creative pillars", "Repeat"],
    professionalExamples: ["‘Close books 5 days faster for small finance teams’"],
    relatedTopics: ["product-marketing", "benefit-presentation", "offer-presentation", "brand-positioning"],
    relatedDomains: ["sales-psychology", "marketing-knowledge", "product-knowledge", "branding-knowledge"],
    keywords: ["value proposition", "UVP", "benefits", "differentiation"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  sales({
    topicId: "urgency",
    name: "Urgency",
    description: "Time pressure that accelerates decisions when truthful.",
    professionalDefinition: "Urgency is a time-based reason to act now—deadlines, limited windows—used honestly to overcome delay.",
    purpose: "Support BOF creative without eroding trust.",
    bestPractices: ["Real deadlines only", "Pair with value", "Don’t cry wolf"],
    commonMistakes: ["Fake countdowns", "Urgency without offer clarity"],
    workflow: ["Validate time constraint", "Script urgency line", "Design end card timer if real", "Comply"],
    professionalExamples: ["Sale ends Sunday—shown with real end date"],
    relatedTopics: ["scarcity", "cta-strategy", "ending-strategy", "offer-presentation"],
    relatedDomains: ["sales-psychology", "marketing-knowledge", "customer-psychology"],
    keywords: ["urgency", "deadline", "act now", "time pressure"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  sales({
    topicId: "scarcity",
    name: "Scarcity",
    description: "Limited availability cues that increase perceived value when true.",
    professionalDefinition: "Scarcity communicates limited quantity or access, raising perceived value and motivating action when accurate.",
    purpose: "Recommend scarce offers carefully in video CTAs.",
    bestPractices: ["Truthful inventory/access limits", "Explain why scarce", "Avoid manipulative fakes"],
    commonMistakes: ["Fake ‘only 2 left’", "Scarcity on unlimited digital goods without basis"],
    workflow: ["Confirm constraint", "Message scarcity", "Show proof if possible", "CTA"],
    professionalExamples: ["Limited drop—batch number shown in film"],
    relatedTopics: ["urgency", "offer-presentation", "persuasion-principles", "video-cta-placement"],
    relatedDomains: ["sales-psychology", "marketing-knowledge", "customer-psychology"],
    keywords: ["scarcity", "limited", "availability", "exclusivity"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  sales({
    topicId: "social-proof",
    name: "Social Proof",
    description: "Evidence that others like us chose and benefited.",
    professionalDefinition: "Social proof uses others’ behavior and testimonials—reviews, counts, UGC—to reduce uncertainty and guide decisions.",
    purpose: "Recommend proof devices in video and landing alignment.",
    bestPractices: ["Specific outcomes", "Relevant peers", "Verifiable sources"],
    commonMistakes: ["Generic praise", "Irrelevant celebrity with no fit"],
    workflow: ["Collect proof", "Match to objection", "Film/edit proof", "Disclose"],
    professionalExamples: ["‘12,000 teams’ + customer face + metric"],
    relatedTopics: ["trust-building", "authority", "influencer-marketing", "persuasion-principles"],
    relatedDomains: ["sales-psychology", "customer-psychology", "marketing-knowledge", "social-media-knowledge"],
    keywords: ["social proof", "reviews", "testimonials", "UGC", "popularity"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  sales({
    topicId: "authority",
    name: "Authority",
    description: "Credibility from expertise, credentials, or institutional signals.",
    professionalDefinition: "Authority persuasion uses expert status, certifications, or credible demonstrators to increase acceptance of claims.",
    purpose: "Support complex or high-risk offers with expert cues.",
    bestPractices: ["Real credentials", "Show expertise in action", "Don’t fake white coats"],
    commonMistakes: ["False authority", "Credentials unrelated to claim"],
    workflow: ["Identify authority source", "Capture demo/interview", "Place near hard claims"],
    professionalExamples: ["Chef demonstrates cookware technique; engineer explains durability test"],
    relatedTopics: ["social-proof", "trust-building", "product-demonstration", "brand-trust"],
    relatedDomains: ["sales-psychology", "branding-knowledge", "customer-psychology", "product-knowledge"],
    keywords: ["authority", "expertise", "credentials", "expert"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  sales({
    topicId: "reciprocity",
    name: "Reciprocity",
    description: "Giving value first to encourage a fair return action.",
    professionalDefinition: "Reciprocity is the tendency to respond to value received with a return favor—used via free education, samples, or tools before the ask.",
    purpose: "Design lead magnets and educational video that earn the CTA.",
    bestPractices: ["Give real value first", "Ask proportionate to gift", "Avoid manipulative ‘free’"],
    commonMistakes: ["Empty freebies", "Huge ask after tiny gift"],
    workflow: ["Define gift", "Deliver in content", "Bridge to ask", "Measure"],
    professionalExamples: ["Free template download CTA after tutorial video"],
    relatedTopics: ["lead-generation", "content-marketing", "cta-strategy", "value-proposition"],
    relatedDomains: ["sales-psychology", "marketing-knowledge", "customer-psychology"],
    keywords: ["reciprocity", "give first", "lead magnet psychology"],
    confidenceScore: 90,
    qualityScore: 89,
  }),
  sales({
    topicId: "cta-strategy",
    name: "Call-To-Action Strategy",
    description: "Strategic choice of ask, wording, and intensity by funnel stage.",
    professionalDefinition: "CTA strategy selects the action, copy, and visual prominence appropriate to awareness level and offer, distinct from pure placement craft in storytelling/video-marketing topics.",
    purpose: "Recommend what to ask—not only where—in professional campaigns.",
    bestPractices: ["One primary CTA", "Verb + outcome", "Match stage (learn vs buy)"],
    commonMistakes: ["Competing CTAs", "Buy now on cold traffic always"],
    workflow: ["Pick action", "Write variants", "Design emphasis", "Test"],
    professionalExamples: ["TOF: Learn how it works; BOF: Start free trial"],
    relatedTopics: ["video-cta-placement", "conversion-optimization", "urgency", "offer-presentation"],
    relatedDomains: ["sales-psychology", "marketing-knowledge", "social-media-knowledge"],
    keywords: ["CTA strategy", "call to action", "ask", "conversion copy"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  sales({
    topicId: "offer-presentation",
    name: "Offer Presentation",
    description: "How price, package, bonuses, and terms are shown for clarity and attractiveness.",
    professionalDefinition: "Offer presentation structures the commercial offer—price anchoring, bundles, bonuses, guarantees—so value is obvious and objections drop.",
    purpose: "Improve BOF videos and end cards that sell.",
    bestPractices: ["Clear price and terms", "Anchor honestly", "Highlight guarantee"],
    commonMistakes: ["Hidden fees", "Confusing package math"],
    workflow: ["Define offer", "Visual hierarchy", "Script clarity", "Compliance"],
    professionalExamples: ["Was/now price with bonus checklist and 30-day guarantee"],
    relatedTopics: ["value-proposition", "cta-strategy", "scarcity", "objection-handling"],
    relatedDomains: ["sales-psychology", "marketing-knowledge", "product-knowledge"],
    keywords: ["offer presentation", "pricing display", "bundle", "guarantee"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  sales({
    topicId: "objection-handling",
    name: "Objection Handling",
    description: "Addressing doubts that block purchase inside creative and scripts.",
    professionalDefinition: "Objection handling anticipates buyer doubts—price, efficacy, fit, risk—and answers them with proof and reframing in the creative.",
    purpose: "Strengthen mid/bottom funnel video content.",
    bestPractices: ["List top 3 objections", "Answer with demo/proof", "Keep tone respectful"],
    commonMistakes: ["Ignoring obvious doubts", "Defensive tone"],
    workflow: ["Mine objections", "Map proof", "Script answers", "Place in MOF/BOF"],
    professionalExamples: ["‘Too expensive?’ → cost-per-use graphic; ‘Does it work?’ → demo"],
    relatedTopics: ["decision-making", "social-proof", "product-demonstration", "trust-building"],
    relatedDomains: ["sales-psychology", "customer-psychology", "product-knowledge", "marketing-knowledge"],
    keywords: ["objection handling", "objections", "doubts", "risk reversal"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
];

export const PROFESSIONAL_VIDEO_MARKETING_TOPICS: ProfessionalMbpTopic[] = [
  vmkt({
    topicId: "hook-creation",
    name: "Hook Creation",
    description: "Crafting the opening line/visual that earns the next seconds of attention.",
    professionalDefinition: "Hook creation designs the initial pattern interrupt—visual, verbal, or textual—that stops scrolling and frames the promise.",
    purpose: "Maximize thumb-stop and continuation rate.",
    bestPractices: ["Specific > generic", "Show tension or novelty", "Align hook to body content"],
    commonMistakes: ["Misleading clickbait hooks", "Logo-first hooks on social"],
    workflow: ["List hook angles", "Script 5 variants", "Shoot/edit", "Test"],
    professionalExamples: ["‘You’re wasting 4 hours a week on this…’ + messy desk visual"],
    relatedTopics: ["first-3-seconds-strategy", "attention-psychology", "audience-retention", "video-marketing"],
    relatedDomains: ["marketing-knowledge", "customer-psychology", "storytelling-knowledge", "social-media-knowledge"],
    keywords: ["hook", "thumb stop", "opening line", "pattern interrupt"],
    confidenceScore: 95,
    qualityScore: 94,
  }),
  vmkt({
    topicId: "first-3-seconds-strategy",
    name: "First 3 Seconds Strategy",
    description: "Deliberate plan for frames 0–3 where most drop-off happens on social.",
    professionalDefinition: "First-3-seconds strategy prioritizes immediate clarity of audience, problem, or intrigue before brand ceremony.",
    purpose: "Reduce early drop-off on paid and organic social video.",
    bestPractices: ["Motion or face early", "On-screen text", "Delay slow branding"],
    commonMistakes: ["Slow establishing shots", "Unreadable first text"],
    workflow: ["Storyboard first 3s", "Multiple opens", "Test retention curves"],
    professionalExamples: ["Cold open problem visual before brand slate"],
    relatedTopics: ["hook-creation", "audience-retention", "brand-awareness", "attention-psychology"],
    relatedDomains: ["marketing-knowledge", "social-media-knowledge", "storytelling-knowledge", "video-editing-knowledge"],
    keywords: ["first 3 seconds", "3-second hook", "early retention", "open strategy"],
    confidenceScore: 95,
    qualityScore: 94,
  }),
  vmkt({
    topicId: "audience-retention",
    name: "Audience Retention",
    description: "Keeping viewers watching through pacing, open loops, and payoffs.",
    professionalDefinition: "Audience retention craft uses curiosity loops, pattern variation, and timely payoffs to sustain watch time across the video.",
    purpose: "Improve average view duration and completion for algorithm and persuasion.",
    bestPractices: ["Open loops then pay off", "Vary shot size/pace", "Cut fluff"],
    commonMistakes: ["Long windups", "Payoff delayed too far"],
    workflow: ["Map retention risks", "Add open loops", "Trim", "Read retention graph"],
    professionalExamples: ["‘Stay for the third tip’ open loop paid off at 0:45"],
    relatedTopics: ["hook-creation", "first-3-seconds-strategy", "ending-strategy", "video-marketing"],
    relatedDomains: ["marketing-knowledge", "storytelling-knowledge", "video-editing-knowledge", "social-media-knowledge"],
    keywords: ["audience retention", "watch time", "completion rate", "open loops"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  vmkt({
    topicId: "product-demonstration",
    name: "Product Demonstration",
    description: "Showing the product working to create belief.",
    professionalDefinition: "Product demonstration presents observable use or performance so viewers can verify claims visually.",
    purpose: "Recommend demo structures for MOF video.",
    bestPractices: ["One claim per demo", "Real-time readability", "Before/after when honest"],
    commonMistakes: ["Demo too fast", "Demo of irrelevant features"],
    workflow: ["Pick claim", "Design demo", "Shoot clearly", "Caption key result"],
    professionalExamples: ["Stain removal in one wipe with timer"],
    relatedTopics: ["feature-presentation", "benefit-presentation", "objection-handling", "product-perception"],
    relatedDomains: ["marketing-knowledge", "product-knowledge", "sales-psychology", "video-production-knowledge"],
    keywords: ["product demonstration", "demo", "how it works", "proof"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  vmkt({
    topicId: "feature-presentation",
    name: "Feature Presentation",
    description: "Explaining what the product has in a scannable, visual way.",
    professionalDefinition: "Feature presentation structures product attributes so they are understandable, ordered by importance, and visually indicated.",
    purpose: "Support consideration content without dumping specs.",
    bestPractices: ["Prioritize top features", "Visual callouts", "Bridge each feature to a benefit"],
    commonMistakes: ["Spec laundry lists", "Features without benefits"],
    workflow: ["Rank features", "Storyboard callouts", "Animate/edit", "CTA"],
    professionalExamples: ["Three icon callouts: battery, waterproof, sync"],
    relatedTopics: ["benefit-presentation", "product-demonstration", "product-marketing", "value-proposition"],
    relatedDomains: ["marketing-knowledge", "product-knowledge", "sales-psychology", "storytelling-knowledge"],
    keywords: ["feature presentation", "features", "callouts", "specs"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  vmkt({
    topicId: "benefit-presentation",
    name: "Benefit Presentation",
    description: "Showing outcomes and value the customer receives.",
    professionalDefinition: "Benefit presentation translates features into customer outcomes—time saved, status, relief—made concrete in picture and copy.",
    purpose: "Keep creative customer-centric.",
    bestPractices: ["Outcome language", "Show life after", "One benefit spine"],
    commonMistakes: ["Feature labeled as benefit", "Abstract benefits"],
    workflow: ["Feature→benefit map", "Visualize outcome", "Script", "Prove"],
    professionalExamples: ["‘More family time’ after automation demo"],
    relatedTopics: ["feature-presentation", "buying-motivation", "value-proposition", "emotional-triggers"],
    relatedDomains: ["marketing-knowledge", "customer-psychology", "product-knowledge", "sales-psychology"],
    keywords: ["benefit presentation", "outcomes", "customer value", "benefits"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  vmkt({
    topicId: "video-cta-placement",
    name: "Call-To-Action Placement",
    description: "Where CTAs appear in video timelines and frames (distinct from CTA strategy and storytelling CTA topics).",
    professionalDefinition: "Video CTA placement decides timed and spatial positioning of asks—mid-roll, end card, lower-third—so action is visible and earned.",
    purpose: "Recommend when/where to show CTAs in video without duplicating sales CTA strategy.",
    bestPractices: ["End card always for conversion films", "Soft mid-CTA on longer videos", "Clear safe areas"],
    commonMistakes: ["CTA before value", "CTA buried in clutter"],
    workflow: ["Choose primary CTA", "Place after proof", "Design end card", "Test mid-CTA"],
    professionalExamples: ["Demo proof at 0:20; end card Shop now 3s hold"],
    relatedTopics: ["cta-strategy", "ending-strategy", "conversion-optimization", "audience-retention"],
    relatedDomains: ["marketing-knowledge", "sales-psychology", "video-editing-knowledge", "rendering-knowledge"],
    keywords: ["CTA placement", "end card", "mid-roll CTA", "video ask"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  vmkt({
    topicId: "ending-strategy",
    name: "Ending Strategy",
    description: "How videos close for memory, branding, and action.",
    professionalDefinition: "Ending strategy designs the final seconds—payoff, brand lockup, CTA, and emotional residue—so the video finishes with purpose.",
    purpose: "Avoid weak endings that waste acquired attention.",
    bestPractices: ["Pay off open loops", "Clear brand + CTA", "Hold long enough to read"],
    commonMistakes: ["Abrupt stop", "Multiple competing end asks"],
    workflow: ["Write payoff", "Design end card", "Time hold", "QC on mute"],
    professionalExamples: ["Resolve story → logo → single CTA"],
    relatedTopics: ["video-cta-placement", "hook-creation", "brand-consistency", "audience-retention"],
    relatedDomains: ["marketing-knowledge", "branding-knowledge", "storytelling-knowledge", "video-editing-knowledge"],
    keywords: ["ending strategy", "video close", "end card strategy", "payoff"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
];

export const MBP_DOMAIN_BRIDGES: MbpDomainBridge[] = [
  { domainId: "marketing-knowledge", knowledgeId: "mbp-bridge-marketing-knowledge", title: "Marketing Knowledge Domain", description: "Hub for marketing and video marketing expansion Step 7.", relationshipEvidence: "Primary domain for marketing strategy topics." },
  { domainId: "branding-knowledge", knowledgeId: "mbp-bridge-branding-knowledge", title: "Branding Knowledge Domain", description: "Hub for branding expansion Step 7.", relationshipEvidence: "Primary domain for brand identity topics." },
  { domainId: "customer-psychology", knowledgeId: "mbp-bridge-customer-psychology", title: "Customer Psychology Domain", description: "Hub for customer psychology expansion Step 7.", relationshipEvidence: "Primary domain for audience psychology topics." },
  { domainId: "sales-psychology", knowledgeId: "mbp-bridge-sales-psychology", title: "Sales Psychology Domain", description: "Hub for sales psychology expansion Step 7.", relationshipEvidence: "Primary domain for persuasion and offer topics." },
  { domainId: "storytelling-knowledge", knowledgeId: "mbp-bridge-storytelling-knowledge", title: "Storytelling Knowledge (related)", description: "Marketing creative inherits narrative craft.", relationshipEvidence: "Hooks and journeys use storytelling structures." },
  { domainId: "video-production-knowledge", knowledgeId: "mbp-bridge-video-production-knowledge", title: "Video Production Knowledge (related)", description: "Video marketing executes through production.", relationshipEvidence: "Production delivers marketing video plans." },
  { domainId: "video-editing-knowledge", knowledgeId: "mbp-bridge-video-editing-knowledge", title: "Video Editing Knowledge (related)", description: "Retention and CTA placement depend on edit craft.", relationshipEvidence: "Editors realize hooks, pace, and end cards." },
  { domainId: "product-knowledge", knowledgeId: "mbp-bridge-product-knowledge", title: "Product Photography / Product Knowledge (related)", description: "Product presentation depends on product truth.", relationshipEvidence: "Features/benefits require accurate product knowledge." },
  { domainId: "social-media-knowledge", knowledgeId: "mbp-bridge-social-media-knowledge", title: "Social Media Knowledge (related)", description: "Social distribution norms shape video marketing.", relationshipEvidence: "Hooks and formats follow social behaviors (deep packs in Step 8)." },
  { domainId: "rendering-knowledge", knowledgeId: "mbp-bridge-rendering-knowledge", title: "Rendering Knowledge (related)", description: "Delivery encodes affect how campaigns appear on platforms.", relationshipEvidence: "Export settings finish marketing video for channels." },
];

export const REQUIRED_MARKETING_TOPIC_IDS: MarketingTopicId[] = PROFESSIONAL_MARKETING_TOPICS.map((t) => t.topicId as MarketingTopicId);
export const REQUIRED_BRANDING_TOPIC_IDS: BrandingTopicId[] = PROFESSIONAL_BRANDING_TOPICS.map((t) => t.topicId as BrandingTopicId);
export const REQUIRED_CUSTOMER_PSYCHOLOGY_TOPIC_IDS: CustomerPsychologyTopicId[] = PROFESSIONAL_CUSTOMER_PSYCHOLOGY_TOPICS.map((t) => t.topicId as CustomerPsychologyTopicId);
export const REQUIRED_SALES_PSYCHOLOGY_TOPIC_IDS: SalesPsychologyTopicId[] = PROFESSIONAL_SALES_PSYCHOLOGY_TOPICS.map((t) => t.topicId as SalesPsychologyTopicId);
export const REQUIRED_VIDEO_MARKETING_TOPIC_IDS: VideoMarketingTopicId[] = PROFESSIONAL_VIDEO_MARKETING_TOPICS.map((t) => t.topicId as VideoMarketingTopicId);

export function getMbpTopic(id: string): ProfessionalMbpTopic | null {
  const all = [
    ...PROFESSIONAL_MARKETING_TOPICS,
    ...PROFESSIONAL_BRANDING_TOPICS,
    ...PROFESSIONAL_CUSTOMER_PSYCHOLOGY_TOPICS,
    ...PROFESSIONAL_SALES_PSYCHOLOGY_TOPICS,
    ...PROFESSIONAL_VIDEO_MARKETING_TOPICS,
  ];
  return all.find((t) => t.topicId === id || t.knowledgeId === id || t.name.toLowerCase() === id.toLowerCase()) ?? null;
}

export function findMbpTopics(query: string, pool: ProfessionalMbpTopic[]): ProfessionalMbpTopic[] {
  return rankTopics(query, pool, identityHay, (t) => [t.topicId, t.name, t.title]);
}

function identityHay(t: ProfessionalMbpTopic): string[] {
  return [t.topicId, t.name, t.title, t.description, t.purpose, t.professionalDefinition, ...t.keywords, ...t.bestPractices, ...t.workflow];
}

function rankTopics(
  query: string,
  items: ProfessionalMbpTopic[],
  haystackOf: (item: ProfessionalMbpTopic) => string[],
  identityOf: (item: ProfessionalMbpTopic) => string[]
): ProfessionalMbpTopic[] {
  const lower = query.trim().toLowerCase();
  if (!lower) return [...items];
  const stop = new Set([
    "what", "is", "are", "how", "should", "i", "the", "a", "an", "do", "does", "can", "to", "for", "of", "in", "on", "and", "or",
    "about", "explain", "recommend", "best", "use", "when", "why", "marketing", "branding", "customer", "sales", "strategy", "strategies",
  ]);
  const tokens = lower.replace(/[^\w\s-]/g, " ").split(/\s+/).filter((t) => t.length > 2 && !stop.has(t));
  const exact = items.filter((item) => {
    const ids = identityOf(item).map((v) => v.toLowerCase());
    return ids.some((id) => id === lower || id.replace(/-/g, " ") === lower || lower.includes(id) || id.includes(lower));
  });
  if (exact.length) {
    return exact.sort((a, b) => {
      const score = (item: ProfessionalMbpTopic) => {
        const ids = identityOf(item).map((v) => v.toLowerCase());
        return ids.some((id) => id === lower || id.replace(/-/g, " ") === lower) ? 1 : 0;
      };
      return score(b) - score(a);
    });
  }
  const direct = items.filter((item) => {
    const hay = haystackOf(item).join(" ").toLowerCase();
    if (hay.includes(lower)) return true;
    return tokens.length > 0 && tokens.every((token) => hay.includes(token));
  });
  if (direct.length) return direct;
  return items
    .map((item) => {
      const parts = haystackOf(item).map((p) => p.toLowerCase());
      const hay = parts.join(" ");
      let score = 0;
      for (const token of tokens) {
        if (hay.includes(token)) score += 1;
        if (parts[0]?.includes(token)) score += 2;
        if (parts[1]?.includes(token)) score += 2;
      }
      return { item, score };
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((x) => x.item);
}

export type { MbpTopicId };
