/**
 * Curated Professional Lighting & Composition Knowledge catalog (Expansion Step 3).
 */

import {
  COMPOSITION_DOMAIN_ID,
  LIGHTING_DOMAIN_ID,
  PROFESSIONAL_LIGHTING_COMPOSITION_VERSION,
  type CompositionTopicId,
  type LightingCompositionDomainBridge,
  type LightingTopicId,
  type ProfessionalLightingCompositionTopic,
} from "./professional-lighting-composition-types.js";

function lit(
  partial: Omit<ProfessionalLightingCompositionTopic, "knowledgeId" | "title" | "metadata"> & {
    knowledgeId?: string;
    title?: string;
  }
): ProfessionalLightingCompositionTopic {
  return {
    ...partial,
    knowledgeId: partial.knowledgeId ?? `lit-${partial.topicId}`,
    title: partial.title ?? partial.name,
    metadata: {
      domainId: LIGHTING_DOMAIN_ID,
      category: "professional-lighting",
      difficulty: partial.confidenceScore >= 90 ? "advanced" : partial.confidenceScore >= 84 ? "intermediate" : "foundation",
      expansionStep: 3,
      version: PROFESSIONAL_LIGHTING_COMPOSITION_VERSION,
      learningOnly: true,
      generatesImages: false,
      generatesVideo: false,
    },
  };
}

function comp(
  partial: Omit<ProfessionalLightingCompositionTopic, "knowledgeId" | "title" | "metadata"> & {
    knowledgeId?: string;
    title?: string;
  }
): ProfessionalLightingCompositionTopic {
  return {
    ...partial,
    knowledgeId: partial.knowledgeId ?? `comp-${partial.topicId}`,
    title: partial.title ?? partial.name,
    metadata: {
      domainId: COMPOSITION_DOMAIN_ID,
      category: "professional-composition",
      difficulty: partial.confidenceScore >= 90 ? "advanced" : partial.confidenceScore >= 84 ? "intermediate" : "foundation",
      expansionStep: 3,
      version: PROFESSIONAL_LIGHTING_COMPOSITION_VERSION,
      learningOnly: true,
      generatesImages: false,
      generatesVideo: false,
    },
  };
}

export const PROFESSIONAL_LIGHTING_TOPICS: ProfessionalLightingCompositionTopic[] = [
  lit({
    topicId: "lighting-fundamentals",
    name: "Lighting Fundamentals",
    description: "Core principles of how light quality, direction, intensity, and color shape image and mood.",
    purpose: "Establish a controllable lighting language so every setup serves story, product clarity, and brand tone.",
    whenToUse: ["Any professional shoot planning", "Teaching crews a shared lighting vocabulary", "Diagnosing look problems"],
    whenNotToUse: ["When skipping to fixtures without defining intent"],
    advantages: ["Transferable across stills and video", "Prevents gear-first mistakes"],
    limitations: ["Requires discipline before complex rigs"],
    bestPractices: ["Define mood and subject priority before placing lights", "Control spill and reflections intentionally", "Match lighting plan to camera exposure strategy"],
    commonMistakes: ["Adding lights without a key purpose", "Ignoring how light direction changes form"],
    professionalExamples: ["Brief: soft commercial beauty vs hard industrial drama before choosing fixtures"],
    relatedCameraTechniques: ["exposure", "white balance", "aperture", "ISO"],
    relatedStorytellingTechniques: ["mood setting", "attention direction", "genre signaling"],
    relatedTopics: ["key-light", "soft-lighting", "hard-lighting", "color-temperature"],
    relatedDomains: ["lighting-knowledge", "camera-knowledge", "video-production-knowledge", "composition-knowledge"],
    keywords: ["lighting fundamentals", "light quality", "direction", "intensity", "mood"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  lit({
    topicId: "natural-lighting",
    name: "Natural Lighting",
    description: "Using sunlight, skylight, and available ambient daylight as primary illumination.",
    purpose: "Create authentic, cost-efficient looks while managing time-of-day and weather constraints.",
    whenToUse: ["Outdoor lifestyle", "Window-lit interiors", "Documentary authenticity"],
    whenNotToUse: ["When schedule cannot follow sun", "When color/contrast must be studio-locked"],
    advantages: ["Believable rendering", "Large soft sources (open sky)"],
    limitations: ["Changing conditions", "Hard to repeat exactly"],
    bestPractices: ["Scout sun path", "Use diffusion/bounce/neg fill", "Protect continuity across hours"],
    commonMistakes: ["Shooting midday without control", "Mixed window + warm practicals unmanaged"],
    professionalExamples: ["Golden-hour product lifestyle with reflector fill"],
    relatedCameraTechniques: ["ND filters", "white balance", "exposure", "frame rate for flicker-free ambient"],
    relatedStorytellingTechniques: ["realism", "time-of-day symbolism"],
    relatedTopics: ["outdoor-lighting", "soft-lighting", "hard-lighting", "color-temperature"],
    relatedDomains: ["lighting-knowledge", "camera-knowledge", "storytelling-knowledge", "marketing-knowledge"],
    keywords: ["natural light", "daylight", "window light", "golden hour", "available light"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  lit({
    topicId: "artificial-lighting",
    name: "Artificial Lighting",
    description: "Controlled electric sources—LED, tungsten, HMI, practicals—shaped for production.",
    purpose: "Deliver repeatable, schedule-independent illumination with precise creative control.",
    whenToUse: ["Studio work", "Night/interior control", "Brand-consistent campaigns"],
    whenNotToUse: ["When natural light alone meets look and schedule"],
    advantages: ["Repeatability", "Direction/intensity control", "Color options"],
    limitations: ["Power, heat, setup time", "Can look unnatural if overlit"],
    bestPractices: ["Match color families", "Flag spill", "Balance key-to-fill ratios intentionally"],
    commonMistakes: ["Too many competing keys", "Ignoring fixture flicker at camera shutter"],
    professionalExamples: ["LED softbox key + negative fill for clean ecommerce"],
    relatedCameraTechniques: ["shutter/flicker sync", "ISO", "white balance", "ND"],
    relatedStorytellingTechniques: ["stylized worlds", "controlled glamour"],
    relatedTopics: ["three-point-lighting", "indoor-lighting", "product-lighting", "color-temperature"],
    relatedDomains: ["lighting-knowledge", "camera-knowledge", "video-production-knowledge", "rendering-knowledge"],
    keywords: ["artificial light", "LED", "studio lights", "practicals", "controlled lighting"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  lit({
    topicId: "three-point-lighting",
    name: "Three-Point Lighting",
    description: "Classic key, fill, and back/rim arrangement that models subjects with controlled depth.",
    purpose: "Build a reliable portrait/product baseline that separates subject from background.",
    whenToUse: ["Interviews", "Talking-head content", "Product heroes needing form"],
    whenNotToUse: ["When a single motivated practical is the style", "Documentary available-light only"],
    advantages: ["Teaches ratios clearly", "Flexible starting template"],
    limitations: ["Can look formulaic if unchanged", "Needs space for three positions"],
    bestPractices: ["Set key first", "Fill only as needed", "Back light for separation not hotspot hair"],
    commonMistakes: ["Equal-intensity lights flattening form", "Rim blowing highlights"],
    professionalExamples: ["Interview: soft key 45°, weak fill, subtle hair light"],
    relatedCameraTechniques: ["exposure for key highlight", "depth of field", "eye light catchlights"],
    relatedStorytellingTechniques: ["clarity", "authority", "clean commercial presence"],
    relatedTopics: ["key-light", "fill-light", "back-light", "portrait-lighting"],
    relatedDomains: ["lighting-knowledge", "camera-knowledge", "composition-knowledge", "marketing-knowledge"],
    keywords: ["three-point", "key fill back", "classic lighting", "interview lighting"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  lit({
    topicId: "key-light",
    name: "Key Light",
    description: "The primary illumination that defines form, exposure anchor, and dominant direction.",
    purpose: "Establish the main modeling light that viewers read as the scene’s light logic.",
    whenToUse: ["Every controlled setup", "When one direction must own the look"],
    whenNotToUse: ["When intentionally silhouette-only with no key"],
    advantages: ["Defines shape", "Sets exposure reference"],
    limitations: ["Wrong angle creates unflattering shadows"],
    bestPractices: ["Place for flattering facial/product planes", "Decide hardness early", "Meter/expose for key"],
    commonMistakes: ["Multiple competing keys", "Key too frontal flattening subjects"],
    professionalExamples: ["45° elevated soft key for beauty; hard side key for drama"],
    relatedCameraTechniques: ["exposure", "false color/waveform", "aperture for DOF under key"],
    relatedStorytellingTechniques: ["focus of attention", "hero emphasis"],
    relatedTopics: ["fill-light", "three-point-lighting", "hard-lighting", "soft-lighting"],
    relatedDomains: ["lighting-knowledge", "camera-knowledge", "storytelling-knowledge"],
    keywords: ["key light", "main light", "modeling light", "primary illumination"],
    confidenceScore: 95,
    qualityScore: 94,
  }),
  lit({
    topicId: "fill-light",
    name: "Fill Light",
    description: "Secondary light or bounce that lifts shadows without overpowering the key.",
    purpose: "Control contrast and retain detail in shadow side while preserving key direction.",
    whenToUse: ["Beauty/commercial polish", "Readable faces", "Product label detail in shadows"],
    whenNotToUse: ["Low-key drama needing deep shadows", "When neg fill is the creative choice"],
    advantages: ["Protects detail", "Softens harshness"],
    limitations: ["Excess fill kills dimension"],
    bestPractices: ["Start with bounce/neg before adding a second lamp", "Keep fill softer and dimmer than key", "Watch for double shadows"],
    commonMistakes: ["Fill equals key intensity", "Fill from wrong side creating second nose shadow"],
    professionalExamples: ["White card fill opposite soft key for ecommerce"],
    relatedCameraTechniques: ["contrast ratio", "exposure latitude", "ISO noise in shadows"],
    relatedStorytellingTechniques: ["approachability", "clarity over mystery"],
    relatedTopics: ["key-light", "soft-lighting", "high-key-lighting", "shadows"],
    relatedDomains: ["lighting-knowledge", "camera-knowledge", "product-knowledge", "marketing-knowledge"],
    keywords: ["fill light", "bounce", "shadow lift", "contrast control"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  lit({
    topicId: "back-light",
    name: "Back Light",
    description: "Light from behind the subject toward camera, used for separation and edge definition.",
    purpose: "Detach subject from background and add dimensional polish.",
    whenToUse: ["Dark wardrobes on dark sets", "Interview separation", "Silhouette accents"],
    whenNotToUse: ["When flare/halo ruins product clarity", "Lens-facing spill uncontrolled"],
    advantages: ["Depth and polish", "Prevents subject merging with BG"],
    limitations: ["Easy to overdo", "Can create veiling flare"],
    bestPractices: ["Flag into lens", "Control intensity on hair/shoulders", "Combine with subtle ambient"],
    commonMistakes: ["Hot rim clipping", "Uneven shoulder highlights"],
    professionalExamples: ["Gentle backlight separating navy blazer from charcoal wall"],
    relatedCameraTechniques: ["lens hood/flags", "highlight roll-off", "exposure for edges"],
    relatedStorytellingTechniques: ["glamour", "presence", "figure-ground clarity"],
    relatedTopics: ["rim-light", "three-point-lighting", "key-light", "portrait-lighting"],
    relatedDomains: ["lighting-knowledge", "composition-knowledge", "camera-knowledge"],
    keywords: ["back light", "backlight", "separation light", "edge light"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  lit({
    topicId: "rim-light",
    name: "Rim Light",
    description: "A focused edge highlight outlining the subject’s contour.",
    purpose: "Create a crisp silhouette edge for premium, graphic, or dramatic emphasis.",
    whenToUse: ["Product contour hero", "Athletic/power portraits", "Dark-background commercials"],
    whenNotToUse: ["Soft documentary naturalism", "When reflections already outline chrome products"],
    advantages: ["Strong graphic read", "Premium feel"],
    limitations: ["Narrow angle tolerance", "Can look gimmicky"],
    bestPractices: ["Feather the rim", "Match color to brand mood", "Keep face exposure independent"],
    commonMistakes: ["Rim wrapping onto cheeks unwanted", "Color clash with key"],
    professionalExamples: ["Cool rim on black sneaker edges against void background"],
    relatedCameraTechniques: ["precise framing of highlight edge", "polarizer for glare control"],
    relatedStorytellingTechniques: ["hero outline", "power silhouette"],
    relatedTopics: ["back-light", "hard-lighting", "product-lighting", "low-key-lighting"],
    relatedDomains: ["lighting-knowledge", "product-knowledge", "marketing-knowledge", "composition-knowledge"],
    keywords: ["rim light", "edge highlight", "contour light", "outline"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  lit({
    topicId: "soft-lighting",
    name: "Soft Lighting",
    description: "Large relative source size producing gradual shadow transitions and gentle modeling.",
    purpose: "Flatter skin, reduce texture harshness, and create approachable commercial beauty.",
    whenToUse: ["Beauty", "Food steam softness", "Friendly brand films"],
    whenNotToUse: ["Gritty texture emphasis", "Hard architectural drama"],
    advantages: ["Forgiving", "Premium beauty default"],
    limitations: ["Can flatten without contrast control", "Needs larger modifiers/space"],
    bestPractices: ["Increase source size relative to subject", "Use diffusion close for softer look", "Add neg fill for shape"],
    commonMistakes: ["Soft light too frontal and flat", "Diffusion too far becoming harder"],
    professionalExamples: ["Large octabox key for skincare campaign"],
    relatedCameraTechniques: ["wide aperture beauty", "careful specular control on skin"],
    relatedStorytellingTechniques: ["warmth", "trust", "comfort"],
    relatedTopics: ["hard-lighting", "fill-light", "portrait-lighting", "high-key-lighting"],
    relatedDomains: ["lighting-knowledge", "marketing-knowledge", "product-knowledge", "camera-knowledge"],
    keywords: ["soft light", "diffusion", "softbox", "gentle shadows"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  lit({
    topicId: "hard-lighting",
    name: "Hard Lighting",
    description: "Small relative source creating sharp shadows and strong specular contrast.",
    purpose: "Reveal texture, carve dramatic shape, and signal intensity or grit.",
    whenToUse: ["Texture product reveals", "Noir/drama", "Graphic commercials"],
    whenNotToUse: ["Unflattering beauty without makeup/control", "When labels must stay evenly readable"],
    advantages: ["Punch and clarity of form", "Strong mood"],
    limitations: ["Harsh on skin", "Difficult multi-subject evenness"],
    bestPractices: ["Control shadow edge with distance", "Use flags for shape", "Expose carefully for speculars"],
    commonMistakes: ["Unmotivated hard light on faces", "Multiple hard sources = multiple shadows"],
    professionalExamples: ["Hard side light raking across leather grain"],
    relatedCameraTechniques: ["lower ISO for clean speculars", "polarizer", "precise focus on texture"],
    relatedStorytellingTechniques: ["conflict", "intensity", "industrial truth"],
    relatedTopics: ["soft-lighting", "shadows", "low-key-lighting", "product-lighting"],
    relatedDomains: ["lighting-knowledge", "storytelling-knowledge", "product-knowledge", "composition-knowledge"],
    keywords: ["hard light", "specular", "sharp shadows", "raking light"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  lit({
    topicId: "high-key-lighting",
    name: "High-Key Lighting",
    description: "Bright, low-contrast lighting with lifted shadows and often light backgrounds.",
    purpose: "Communicate openness, optimism, cleanliness, and airy brand energy.",
    whenToUse: ["Lifestyle brands", "Healthcare/clean tech", "Cheerful social ads"],
    whenNotToUse: ["Mystery/thriller tones", "When deep contrast sells luxury drama"],
    advantages: ["Friendly and clear", "Hides minor skin texture"],
    limitations: ["Can feel bland", "Risk of clipped whites"],
    bestPractices: ["Lift fill thoughtfully", "Protect highlight detail", "Keep background luminance intentional"],
    commonMistakes: ["Overexposed whites with no detail", "No residual shape left"],
    professionalExamples: ["White cyclorama soft wrap for apparel"],
    relatedCameraTechniques: ["expose to protect whites", "false color", "clean ISO"],
    relatedStorytellingTechniques: ["optimism", "simplicity", "transparency"],
    relatedTopics: ["soft-lighting", "fill-light", "low-key-lighting", "product-lighting"],
    relatedDomains: ["lighting-knowledge", "marketing-knowledge", "rendering-knowledge", "composition-knowledge"],
    keywords: ["high-key", "bright", "low contrast", "airy", "clean look"],
    confidenceScore: 90,
    qualityScore: 89,
  }),
  lit({
    topicId: "low-key-lighting",
    name: "Low-Key Lighting",
    description: "Dark-dominant lighting with selective highlights and deep shadows.",
    purpose: "Create drama, secrecy, premium night aesthetics, and focused attention.",
    whenToUse: ["Luxury night ads", "Thriller beats", "Selective product spotlight"],
    whenNotToUse: ["Informational demos needing full readability", "High-key brand systems"],
    advantages: ["Strong mood", "Hides clutter"],
    limitations: ["Noise risk if underexposed", "Can obscure product features"],
    bestPractices: ["Light what matters; crush what doesn’t", "Use negative fill", "Protect critical highlight shape"],
    commonMistakes: ["Muddy underexposure without designed blacks", "Losing logo legibility"],
    professionalExamples: ["Single hard key on watch face in void"],
    relatedCameraTechniques: ["exposure for highlight", "noise management", "manual WB in tungsten/LED night"],
    relatedStorytellingTechniques: ["suspense", "exclusivity", "intimacy"],
    relatedTopics: ["hard-lighting", "key-light", "shadows", "rim-light"],
    relatedDomains: ["lighting-knowledge", "storytelling-knowledge", "marketing-knowledge", "composition-knowledge"],
    keywords: ["low-key", "dark", "dramatic lighting", "selective highlight"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  lit({
    topicId: "color-temperature",
    name: "Color Temperature",
    description: "The Kelvin character of light sources—from warm tungsten to cool daylight—and how mixes read on camera.",
    purpose: "Design color mood and keep multi-source color coherent for grade and brand.",
    whenToUse: ["Planning motivated practicals", "Matching daylight/LED", "Emotional warmth/coolness"],
    whenNotToUse: ["Ignoring Kelvin then fighting in grade only"],
    advantages: ["Powerful mood lever", "Cross-fixture consistency when matched"],
    limitations: ["Mixed temps need intentional motivation"],
    bestPractices: ["Pick a hero temperature", "Gel/LED CCT to match", "Document Kelvin for continuity"],
    commonMistakes: ["Unmotivated mixed orange/blue", "Auto systems drifting CCT"],
    professionalExamples: ["3200K interior practicals with matched LED key"],
    relatedCameraTechniques: ["manual white balance", "custom WB", "log/grade pipeline"],
    relatedStorytellingTechniques: ["warm intimacy", "cool distance", "time-of-day cues"],
    relatedTopics: ["white-balance", "artificial-lighting", "natural-lighting", "indoor-lighting"],
    relatedDomains: ["lighting-knowledge", "camera-knowledge", "rendering-knowledge", "storytelling-knowledge"],
    keywords: ["color temperature", "Kelvin", "CCT", "warm", "cool"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  lit({
    topicId: "white-balance",
    name: "White Balance",
    description: "Aligning camera color interpretation to lighting so neutrals and brand colors stay accurate (lighting-side practice).",
    purpose: "Ensure lighting and camera agree on white so skin and product color remain trustworthy.",
    whenToUse: ["Every controlled setup", "Multi-cam matching", "Brand color critical work"],
    whenNotToUse: ["Intentional creative WB shifts without documentation"],
    advantages: ["Accurate color", "Faster grade"],
    limitations: ["Cannot fix badly mixed lighting alone"],
    bestPractices: ["Set after lights are locked", "Use custom card under key", "Match cameras before rolling"],
    commonMistakes: ["AWB drift", "Balancing before final light changes"],
    professionalExamples: ["Custom WB under 5600K soft key for true packaging white"],
    relatedCameraTechniques: ["custom white balance", "Kelvin lock", "multi-cam match"],
    relatedStorytellingTechniques: ["realism", "brand trust"],
    relatedTopics: ["color-temperature", "product-lighting", "portrait-lighting", "artificial-lighting"],
    relatedDomains: ["lighting-knowledge", "camera-knowledge", "product-knowledge", "rendering-knowledge"],
    keywords: ["white balance", "neutral", "color accuracy", "custom WB", "lighting white balance"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  lit({
    topicId: "shadows",
    name: "Shadows",
    description: "Designed absence of light that reveals form, depth, and mood.",
    purpose: "Use shadow shape and density as compositional and storytelling tools—not accidents.",
    whenToUse: ["Modeling faces/products", "Hiding clutter", "Dramatic beats"],
    whenNotToUse: ["When critical text falls into unreadable shadow"],
    advantages: ["Creates dimension", "Directs eye"],
    limitations: ["Noise and crushed detail if uncontrolled"],
    bestPractices: ["Shape with flags/neg fill", "Decide shadow edge (hard/soft)", "Keep story-critical detail above noise floor"],
    commonMistakes: ["Random multipole shadows", "Blocking eyes unintentionally"],
    professionalExamples: ["Single shadow under bottle for grounded product beauty"],
    relatedCameraTechniques: ["exposure latitude", "ISO", "contrast monitoring"],
    relatedStorytellingTechniques: ["mystery", "weight", "focus"],
    relatedTopics: ["hard-lighting", "soft-lighting", "fill-light", "low-key-lighting"],
    relatedDomains: ["lighting-knowledge", "composition-knowledge", "storytelling-knowledge", "camera-knowledge"],
    keywords: ["shadows", "contrast", "form", "neg fill", "shade"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  lit({
    topicId: "reflections",
    name: "Reflections",
    description: "Managing specular reflections on glossy, chrome, glass, and wet surfaces.",
    purpose: "Make reflective products readable and premium by shaping what the surface mirrors.",
    whenToUse: ["Electronics", "Automotive/paint", "Glass bottles", "Watches"],
    whenNotToUse: ["Ignoring reflection as ‘fix later’ on hero chrome"],
    advantages: ["Defines premium materials", "Can create graphic light shapes"],
    limitations: ["Shows crew/gear easily", "Time-consuming"],
    bestPractices: ["Light the reflection, not only the object", "Use large soft sources and black cards", "Polarize when helpful"],
    commonMistakes: ["Hot specular blowouts", "Visible softbox shapes unwanted"],
    professionalExamples: ["Graduated white card reflection on smartphone face"],
    relatedCameraTechniques: ["polarizing filter", "camera angle vs reflection angle", "highlight protection"],
    relatedStorytellingTechniques: ["luxury proof", "material honesty"],
    relatedTopics: ["product-lighting", "soft-lighting", "hard-lighting", "key-light"],
    relatedDomains: ["lighting-knowledge", "product-knowledge", "camera-knowledge", "rendering-knowledge"],
    keywords: ["reflections", "specular", "gloss", "chrome", "glass"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  lit({
    topicId: "product-lighting",
    name: "Product Lighting",
    description: "Lighting strategies that prove form, material, label readability, and desirability of products.",
    purpose: "Sell the product’s physical truth and brand promise through controlled light.",
    whenToUse: ["Ecommerce", "Pack shots", "Feature demos", "Hero commercials"],
    whenNotToUse: ["Lifestyle-only plates where product is incidental background"],
    advantages: ["Clarity of features", "Consistent catalog look"],
    limitations: ["Can look sterile without lifestyle accents"],
    bestPractices: ["Prioritize label/logo readability", "Control speculars", "Match tabletop and lifestyle keys"],
    commonMistakes: ["Beauty without readable branding", "Color casts on packaging"],
    professionalExamples: ["Soft overhead + side accent + controlled base reflection for cosmetics"],
    relatedCameraTechniques: ["macro focus", "deeper DOF for text", "accurate WB"],
    relatedStorytellingTechniques: ["benefit proof", "desire", "trust"],
    relatedTopics: ["reflections", "soft-lighting", "three-point-lighting", "high-key-lighting"],
    relatedDomains: ["lighting-knowledge", "product-knowledge", "marketing-knowledge", "composition-knowledge"],
    keywords: ["product lighting", "pack shot", "tabletop", "ecommerce light", "hero product"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  lit({
    topicId: "portrait-lighting",
    name: "Portrait Lighting",
    description: "Lighting patterns and modifiers optimized for faces—Rembrandt, loop, butterfly, split, and wrap.",
    purpose: "Flatter or characterize people while keeping eyes alive and skin tones believable.",
    whenToUse: ["Interviews", "Testimonials", "Founder films", "Beauty"],
    whenNotToUse: ["When silhouettes are the intent", "Group scenes needing even broad light only"],
    advantages: ["Emotional connection", "Professional polish"],
    limitations: ["Face-shape dependent", "Eyeglasses reflections"],
    bestPractices: ["Place catchlights intentionally", "Watch nose/eye sockets", "Match key height to face"],
    commonMistakes: ["Dead eyes (no catchlight)", "Double chin from low key"],
    professionalExamples: ["Soft loop lighting for CEO interview"],
    relatedCameraTechniques: ["85mm-class perspective", "eye focus", "skin-friendly exposure"],
    relatedStorytellingTechniques: ["empathy", "authority", "intimacy"],
    relatedTopics: ["three-point-lighting", "soft-lighting", "key-light", "fill-light"],
    relatedDomains: ["lighting-knowledge", "camera-knowledge", "storytelling-knowledge", "marketing-knowledge"],
    keywords: ["portrait lighting", "Rembrandt", "butterfly", "catchlight", "interview light"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  lit({
    topicId: "indoor-lighting",
    name: "Indoor Lighting",
    description: "Controlling interiors with practicals, windows, and supplemental fixtures.",
    purpose: "Build believable interior ambience while maintaining exposure and color control.",
    whenToUse: ["Offices", "Homes", "Retail sets", "Studio interiors"],
    whenNotToUse: ["When full daylight exterior is the plate"],
    advantages: ["Motivated practical storytelling", "Weather-independent"],
    limitations: ["Mixed CCT common", "Power/ceiling constraints"],
    bestPractices: ["Motivate keys from practicals/windows", "Gel/LED match", "Flag windows or balance exposure"],
    commonMistakes: ["Flat overhead-only office look", "Uncontrolled mixed Kelvin"],
    professionalExamples: ["Lamp practical as motivated key with soft augmentation"],
    relatedCameraTechniques: ["dual ISO", "WB lock", "highlight protection on windows"],
    relatedStorytellingTechniques: ["domestic warmth", "corporate clarity"],
    relatedTopics: ["artificial-lighting", "color-temperature", "natural-lighting", "three-point-lighting"],
    relatedDomains: ["lighting-knowledge", "video-production-knowledge", "storytelling-knowledge", "camera-knowledge"],
    keywords: ["indoor lighting", "interiors", "practicals", "window balance", "studio interior"],
    confidenceScore: 90,
    qualityScore: 89,
  }),
  lit({
    topicId: "outdoor-lighting",
    name: "Outdoor Lighting",
    description: "Shaping daylight and adding portable fixtures for exterior control.",
    purpose: "Keep outdoor images consistent and flattering despite sun movement and weather.",
    whenToUse: ["Lifestyle exteriors", "Architecture", "Event coverage with sun"],
    whenNotToUse: ["When interiors are primary"],
    advantages: ["Scale and realism", "Beautiful natural ambience"],
    limitations: ["Time windows", "Wind on modifiers"],
    bestPractices: ["Diffuse or shade harsh sun", "Use bounce/neg", "Plan backlight sun positions"],
    commonMistakes: ["Racoon-eye noon sun", "Ignoring background exposure blows"],
    professionalExamples: ["Silk overhead + reflector fill for midday interview"],
    relatedCameraTechniques: ["ND", "polarizer", "fast frame planning for changing light"],
    relatedStorytellingTechniques: ["freedom", "adventure", "authenticity"],
    relatedTopics: ["natural-lighting", "hard-lighting", "soft-lighting", "color-temperature"],
    relatedDomains: ["lighting-knowledge", "camera-knowledge", "marketing-knowledge", "video-production-knowledge"],
    keywords: ["outdoor lighting", "sunlight control", "silk", "reflector", "exterior"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
];

export const PROFESSIONAL_COMPOSITION_TOPICS: ProfessionalLightingCompositionTopic[] = [
  comp({
    topicId: "rule-of-thirds",
    name: "Rule of Thirds",
    description: "Dividing the frame into nine regions and placing key elements along lines or intersections.",
    purpose: "Create balanced, dynamic framing that avoids dead-center default placements.",
    whenToUse: ["General commercial framing", "Landscapes with horizon", "Interview off-center looks"],
    whenNotToUse: ["When centered symmetry is the stronger statement", "Graphic dead-center product locks"],
    advantages: ["Quick, teachable", "Naturally pleasing"],
    limitations: ["Can become formulaic", "Not sacred law"],
    bestPractices: ["Place eyes near upper third", "Align horizons on thirds", "Break intentionally when motivated"],
    commonMistakes: ["Horizon through the head", "Ignoring thirds then cropping badly later"],
    professionalExamples: ["Subject on right third looking into left look-room"],
    relatedCameraTechniques: ["aspect ratio safe frames", "grid overlays", "focal length perspective"],
    relatedStorytellingTechniques: ["open space for gaze", "directional energy"],
    relatedTopics: ["subject-placement", "look-room", "balance", "visual-hierarchy"],
    relatedDomains: ["composition-knowledge", "camera-knowledge", "storytelling-knowledge", "marketing-knowledge"],
    keywords: ["rule of thirds", "grid", "intersections", "off-center"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  comp({
    topicId: "golden-ratio",
    name: "Golden Ratio",
    description: "Composition using phi-based spirals or divisions for organic, classical balance.",
    purpose: "Guide the eye along a natural flow toward the subject with refined proportion.",
    whenToUse: ["Premium brand stills", "Hero product art direction", "Architectural elegance"],
    whenNotToUse: ["Fast run-and-gun where thirds suffice", "When grids confuse the crew"],
    advantages: ["Sophisticated flow", "Strong focal journey"],
    limitations: ["Harder to mark on set", "Easy to overclaim"],
    bestPractices: ["Use as guiding spiral not dogma", "Align subject near spiral calm point", "Simplify background"],
    commonMistakes: ["Forcing spiral overlays on unsuitable scenes"],
    professionalExamples: ["Product placed at spiral focus with leading curve of set design"],
    relatedCameraTechniques: ["prime lens framing", "controlled distortion"],
    relatedStorytellingTechniques: ["elevated taste", "timelessness"],
    relatedTopics: ["rule-of-thirds", "leading-lines", "subject-placement", "visual-hierarchy"],
    relatedDomains: ["composition-knowledge", "product-knowledge", "marketing-knowledge", "rendering-knowledge"],
    keywords: ["golden ratio", "phi", "golden spiral", "proportion"],
    confidenceScore: 88,
    qualityScore: 87,
  }),
  comp({
    topicId: "leading-lines",
    name: "Leading Lines",
    description: "Lines in the scene that steer the viewer’s eye toward the subject or through the story.",
    purpose: "Create directed attention and depth using architecture, roads, edges, and gestures.",
    whenToUse: ["Environments with strong geometry", "Journey storytelling", "Retail aisles"],
    whenNotToUse: ["When lines lead out of frame away from subject"],
    advantages: ["Powerful eye control", "Adds depth"],
    limitations: ["Requires clean environments"],
    bestPractices: ["Start lines from foreground", "Converge near subject", "Avoid competing line sets"],
    commonMistakes: ["Lines cutting through faces", "Accidental lead to clutter"],
    professionalExamples: ["Corridor lines ending on talent with product"],
    relatedCameraTechniques: ["wide lens exaggeration", "low/high angle to strengthen lines"],
    relatedStorytellingTechniques: ["path", "destiny", "focus"],
    relatedTopics: ["depth", "framing", "subject-placement", "foreground-elements"],
    relatedDomains: ["composition-knowledge", "storytelling-knowledge", "camera-knowledge", "video-production-knowledge"],
    keywords: ["leading lines", "vanishing point", "eye path", "geometry"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  comp({
    topicId: "framing",
    name: "Framing",
    description: "Using foreground apertures—doors, windows, hands, props—to enclose the subject.",
    purpose: "Focus attention and add layered depth with a natural vignette of environment.",
    whenToUse: ["Voyeur intimacy", "Architectural storytelling", "Product within lifestyle context"],
    whenNotToUse: ["When frame edges obscure critical branding"],
    advantages: ["Depth and context", "Strong subject isolation"],
    limitations: ["Can feel gimmicky if overused"],
    bestPractices: ["Keep frame soft or darker", "Ensure subject remains sharp/readable", "Match frame to story motive"],
    commonMistakes: ["Busy frames competing with subject", "Crooked unintentional frames"],
    professionalExamples: ["Shooting through shelf gap to product hero"],
    relatedCameraTechniques: ["deeper DOF for frame+subject", "rack focus frame to subject"],
    relatedStorytellingTechniques: ["observation", "context", "intimacy"],
    relatedTopics: ["foreground-elements", "depth", "subject-placement", "background-selection"],
    relatedDomains: ["composition-knowledge", "storytelling-knowledge", "camera-knowledge", "lighting-knowledge"],
    keywords: ["framing", "frame within frame", "aperture frame", "enclosure"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  comp({
    topicId: "symmetry",
    name: "Symmetry",
    description: "Balanced mirroring across a central axis for formal, graphic, or calm compositions.",
    purpose: "Communicate order, power, ceremony, or graphic brand precision.",
    whenToUse: ["Centered product locks", "Architecture", "Ritual/ceremonial moments"],
    whenNotToUse: ["When energy needs asymmetry", "Imperfect sets that fight perfect symmetry"],
    advantages: ["Instant graphic strength", "Memorable posters"],
    limitations: ["Can feel static", "Demands precise leveling"],
    bestPractices: ["Level horizons and verticals", "Center true optical center", "Use tiny asymmetry for life if needed"],
    commonMistakes: ["Almost-centered looking accidental", "Keystoned architecture"],
    professionalExamples: ["Dead-center perfume bottle on mirrored set"],
    relatedCameraTechniques: ["tripod level", "center punch framing", "longer lens to reduce distortion"],
    relatedStorytellingTechniques: ["authority", "order", "iconography"],
    relatedTopics: ["balance", "subject-placement", "visual-hierarchy", "rule-of-thirds"],
    relatedDomains: ["composition-knowledge", "product-knowledge", "marketing-knowledge", "camera-knowledge"],
    keywords: ["symmetry", "centered", "mirror", "formal balance"],
    confidenceScore: 90,
    qualityScore: 89,
  }),
  comp({
    topicId: "balance",
    name: "Balance",
    description: "Distributing visual weight—tone, size, color, detail—so the frame feels stable or intentionally tense.",
    purpose: "Control comfort vs tension by how elements counterweight each other.",
    whenToUse: ["Multi-element scenes", "Graphics+talent layouts", "Interview with set dressing"],
    whenNotToUse: ["Ignoring weight until the grade stage"],
    advantages: ["Professional polish", "Guides pacing of attention"],
    limitations: ["Subjective without clear hierarchy"],
    bestPractices: ["Counter large empty areas with tonal anchors", "Balance bright spots", "Check still frames"],
    commonMistakes: ["All weight piled on one side", "Text fighting subject weight"],
    professionalExamples: ["Talent on left balanced by product glow on right"],
    relatedCameraTechniques: ["exposure affecting tonal weight", "color contrast"],
    relatedStorytellingTechniques: ["stability", "unease via imbalance"],
    relatedTopics: ["symmetry", "negative-space", "visual-hierarchy", "subject-placement"],
    relatedDomains: ["composition-knowledge", "lighting-knowledge", "marketing-knowledge", "storytelling-knowledge"],
    keywords: ["balance", "visual weight", "counterweight", "stability"],
    confidenceScore: 91,
    qualityScore: 90,
  }),
  comp({
    topicId: "depth",
    name: "Depth",
    description: "Creating a sense of three-dimensional space via layers, overlap, scale, and atmosphere.",
    purpose: "Pull viewers into the scene and separate subject planes clearly.",
    whenToUse: ["Cinematic commercials", "Environmental portraits", "Product in context"],
    whenNotToUse: ["Flat graphic catalog requirements without layers"],
    advantages: ["Immersion", "Premium cinematic feel"],
    limitations: ["Needs space and layered set dressing"],
    bestPractices: ["Build FG/MG/BG", "Use overlap", "Control DOF to support planes"],
    commonMistakes: ["Everything on one plane", "BG competing sharpness"],
    professionalExamples: ["Foreground blur leaf, sharp talent, soft city BG"],
    relatedCameraTechniques: ["aperture/DOF", "focal length compression", "parallax moves"],
    relatedStorytellingTechniques: ["world-building", "presence"],
    relatedTopics: ["foreground-elements", "background-selection", "leading-lines", "framing"],
    relatedDomains: ["composition-knowledge", "camera-knowledge", "lighting-knowledge", "video-production-knowledge"],
    keywords: ["depth", "layers", "planes", "dimensionality", "overlap"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  comp({
    topicId: "negative-space",
    name: "Negative Space",
    description: "Empty or low-detail areas that give the subject room and emphasize isolation or calm.",
    purpose: "Heighten subject importance and leave room for typography or breath.",
    whenToUse: ["Minimal brand ads", "Title-safe compositions", "Premium sparse aesthetics"],
    whenNotToUse: ["When empty space feels unfinished without intent"],
    advantages: ["Elegant focus", "Design-friendly"],
    limitations: ["Can feel sparse if brand expects richness"],
    bestPractices: ["Keep negative space clean", "Align subject to allow text", "Use tonal calm"],
    commonMistakes: ["Accidental empty boredom", "Sensor dust/noise in large soft fields"],
    professionalExamples: ["Small product lower-right with large soft void for headline"],
    relatedCameraTechniques: ["clean backdrop", "even field lighting", "longer lens isolation"],
    relatedStorytellingTechniques: ["loneliness", "luxury minimalism", "focus"],
    relatedTopics: ["positive-space", "subject-placement", "visual-hierarchy", "balance"],
    relatedDomains: ["composition-knowledge", "marketing-knowledge", "product-knowledge", "rendering-knowledge"],
    keywords: ["negative space", "empty space", "minimal", "breathing room"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  comp({
    topicId: "positive-space",
    name: "Positive Space",
    description: "The occupied areas of the frame—subjects, props, and active visual mass.",
    purpose: "Define what the image is ‘about’ by shaping occupied mass against emptiness.",
    whenToUse: ["Busy storytelling frames", "Group compositions", "Product clusters"],
    whenNotToUse: ["When positive space becomes clutter without hierarchy"],
    advantages: ["Carries information", "Creates energy"],
    limitations: ["Overfill confuses"],
    bestPractices: ["Cluster related positives", "Leave gaps for eye rest", "Prioritize one dominant positive"],
    commonMistakes: ["Equal competing positives", "Touching edges awkwardly"],
    professionalExamples: ["Grouped skincare set as one positive mass on clean field"],
    relatedCameraTechniques: ["grouping within DOF", "avoid edge amputations"],
    relatedStorytellingTechniques: ["abundance", "community", "offer density"],
    relatedTopics: ["negative-space", "visual-hierarchy", "balance", "subject-placement"],
    relatedDomains: ["composition-knowledge", "product-knowledge", "marketing-knowledge", "storytelling-knowledge"],
    keywords: ["positive space", "occupied space", "subject mass", "active area"],
    confidenceScore: 89,
    qualityScore: 88,
  }),
  comp({
    topicId: "headroom",
    name: "Headroom",
    description: "Vertical space above a subject’s head within the frame.",
    purpose: "Keep portraits comfortable and professional by avoiding cramped or excessive top space.",
    whenToUse: ["Interviews", "Talking heads", "Standing portraits"],
    whenNotToUse: ["Intentional extreme crops for style"],
    advantages: ["Polished default", "Prevents awkward cuts"],
    limitations: ["Platform UI may steal top space—plan safe areas"],
    bestPractices: ["Leave modest headroom", "Account for social UI overlays", "Match headroom across coverage"],
    commonMistakes: ["Too much ceiling", "Cutting skulls"],
    professionalExamples: ["Medium interview with consistent headroom across cameras"],
    relatedCameraTechniques: ["eye-level height", "aspect ratio safe frames"],
    relatedStorytellingTechniques: ["respect", "presence"],
    relatedTopics: ["look-room", "eye-line", "subject-placement", "rule-of-thirds"],
    relatedDomains: ["composition-knowledge", "camera-knowledge", "video-production-knowledge", "marketing-knowledge"],
    keywords: ["headroom", "top space", "portrait framing", "interview framing"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  comp({
    topicId: "look-room",
    name: "Look Room",
    description: "Horizontal space in the direction a subject is looking or moving (also nose room).",
    purpose: "Give gaze and motion a destination so framing feels open and intentional.",
    whenToUse: ["Profiles", "Interviews looking off-camera", "Walking shots"],
    whenNotToUse: ["Centered symmetry looks", "When closed framing is psychological intent"],
    advantages: ["Natural comfort", "Implies offscreen world"],
    limitations: ["Too much look-room weakens presence"],
    bestPractices: ["More space in look direction", "Match look-room across edits", "Tighten for intensity intentionally"],
    commonMistakes: ["Subject staring into the near edge", "Inconsistent look-room in coverage"],
    professionalExamples: ["Talent on left third looking right into open space"],
    relatedCameraTechniques: ["eye-line matching", "screen direction"],
    relatedStorytellingTechniques: ["anticipation", "open possibilities", "conversation"],
    relatedTopics: ["headroom", "eye-line", "rule-of-thirds", "subject-placement"],
    relatedDomains: ["composition-knowledge", "storytelling-knowledge", "camera-knowledge", "video-production-knowledge"],
    keywords: ["look room", "nose room", "lead room", "gaze space"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
  comp({
    topicId: "eye-line",
    name: "Eye Line",
    description: "The height and direction of a subject’s gaze relative to camera and other subjects.",
    purpose: "Maintain spatial and emotional continuity so viewers understand who is looking at what.",
    whenToUse: ["Dialogue coverage", "Interviews", "Product-to-talent glances"],
    whenNotToUse: ["POV breaks that are intentionally discontinuous"],
    advantages: ["Invisible continuity", "Emotional clarity"],
    limitations: ["Requires marks and discipline"],
    bestPractices: ["Match eye-lines across angles", "Keep interview eyeline just off lens unless direct address", "Note height differences"],
    commonMistakes: ["Crossing eyelines confusing geography", "Camera too high creating unnoticed down-look"],
    professionalExamples: ["A/B interview cameras sharing consistent off-lens eyeline"],
    relatedCameraTechniques: ["camera height", "matching lenses", "continuity notes"],
    relatedStorytellingTechniques: ["connection", "power", "direct address"],
    relatedTopics: ["headroom", "look-room", "subject-placement", "framing"],
    relatedDomains: ["composition-knowledge", "camera-knowledge", "storytelling-knowledge", "video-production-knowledge"],
    keywords: ["eye line", "eyeline", "gaze", "continuity", "look direction"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  comp({
    topicId: "background-selection",
    name: "Background Selection",
    description: "Choosing and controlling what sits behind the subject for clarity, brand, and mood.",
    purpose: "Support the subject without stealing attention or introducing conflicting messages.",
    whenToUse: ["Every framed shot", "Location scouting", "Set dressing"],
    whenNotToUse: ["Leaving BG to chance on hero frames"],
    advantages: ["Instant production value", "Brand coherence"],
    limitations: ["Locations constrain options"],
    bestPractices: ["Simplify", "Watch merges (tone-on-tone)", "Remove exit signs/clutter", "Match grade intent"],
    commonMistakes: ["Trees/poles growing from heads", "Readable wrong text in BG"],
    professionalExamples: ["Seamless paper for pack; branded but soft office bokeh for interview"],
    relatedCameraTechniques: ["DOF separation", "longer lens compression", "camera move to clean BG"],
    relatedStorytellingTechniques: ["context", "status", "world"],
    relatedTopics: ["depth", "subject-placement", "visual-hierarchy", "negative-space"],
    relatedDomains: ["composition-knowledge", "lighting-knowledge", "marketing-knowledge", "product-knowledge"],
    keywords: ["background", "backdrop", "clean BG", "set dressing", "bokeh background"],
    confidenceScore: 92,
    qualityScore: 91,
  }),
  comp({
    topicId: "foreground-elements",
    name: "Foreground Elements",
    description: "Objects placed closer to camera to add depth, context, or selective reveal.",
    purpose: "Layer the frame and create parallax or discovery without losing the subject.",
    whenToUse: ["Cinematic depth", "Product among ingredients", "Environmental immersion"],
    whenNotToUse: ["When FG blocks logo/face critical reads"],
    advantages: ["Depth quickly", "Premium production cue"],
    limitations: ["Distraction risk", "Focus complexity"],
    bestPractices: ["Keep FG softer or darker", "Use sparse recognizable shapes", "Motivate FG story-wise"],
    commonMistakes: ["Busy FG junk", "Accidental focus on FG"],
    professionalExamples: ["Out-of-focus glassware FG with sharp cocktail hero"],
    relatedCameraTechniques: ["shallow DOF", "push-ins with parallax", "focus pulls"],
    relatedStorytellingTechniques: ["immersion", "discovery", "appetite cues"],
    relatedTopics: ["depth", "framing", "leading-lines", "background-selection"],
    relatedDomains: ["composition-knowledge", "camera-knowledge", "product-knowledge", "storytelling-knowledge"],
    keywords: ["foreground", "FG elements", "layers", "parallax layers"],
    confidenceScore: 90,
    qualityScore: 89,
  }),
  comp({
    topicId: "subject-placement",
    name: "Subject Placement",
    description: "Deciding where the primary subject sits in frame relative to space, gaze, and hierarchy.",
    purpose: "Make the subject unmistakably primary and aligned with story energy.",
    whenToUse: ["Every composed shot", "Multi-subject priority decisions"],
    whenNotToUse: ["Random centering without intent"],
    advantages: ["Clear communication", "Edit-friendly consistency"],
    limitations: ["Must reconcile with movement and overlays"],
    bestPractices: ["Place for look-room and headroom", "Keep brand marks clear", "Plan for captions/UI"],
    commonMistakes: ["Subject lost in pattern", "Amputating joints at edges"],
    professionalExamples: ["Product lower-third-safe center-right for vertical social"],
    relatedCameraTechniques: ["aspect ratio planning", "grid tools", "lens choice"],
    relatedStorytellingTechniques: ["priority", "power positions", "isolation"],
    relatedTopics: ["rule-of-thirds", "look-room", "visual-hierarchy", "balance"],
    relatedDomains: ["composition-knowledge", "camera-knowledge", "marketing-knowledge", "video-production-knowledge"],
    keywords: ["subject placement", "framing subject", "positioning", "primary subject"],
    confidenceScore: 93,
    qualityScore: 92,
  }),
  comp({
    topicId: "visual-hierarchy",
    name: "Visual Hierarchy",
    description: "Ordering attention so viewers see the most important element first, then secondary story points.",
    purpose: "Engineer reading order for persuasion—product, face, CTA, or proof in the intended sequence.",
    whenToUse: ["Ads with multiple claims", "Pack shots with badges", "UI-on-video frames"],
    whenNotToUse: ["When a single pure subject needs no ranking"],
    advantages: ["Clear messaging", "Stronger conversion framing"],
    limitations: ["Requires restraint and testing"],
    bestPractices: ["One dominant", "Use size/contrast/focus/light to rank", "Remove rivals"],
    commonMistakes: ["Everything screaming equally", "CTA fighting face"],
    professionalExamples: ["Bright product hero, softer lifestyle BG, reserved corner for logo"],
    relatedCameraTechniques: ["selective focus", "exposure contrast", "color pop"],
    relatedStorytellingTechniques: ["persuasion order", "clarity", "call-to-action support"],
    relatedTopics: ["subject-placement", "balance", "negative-space", "background-selection"],
    relatedDomains: ["composition-knowledge", "marketing-knowledge", "lighting-knowledge", "product-knowledge"],
    keywords: ["visual hierarchy", "attention order", "dominance", "focal point"],
    confidenceScore: 94,
    qualityScore: 93,
  }),
];

export const LIGHTING_COMPOSITION_DOMAIN_BRIDGES: LightingCompositionDomainBridge[] = [
  {
    domainId: "lighting-knowledge",
    knowledgeId: "lc-bridge-lighting-knowledge",
    title: "Lighting Knowledge Domain",
    description: "Hub for professional lighting expansion Step 3.",
    relationshipEvidence: "Primary domain for lighting technique topics.",
  },
  {
    domainId: "composition-knowledge",
    knowledgeId: "lc-bridge-composition-knowledge",
    title: "Composition Knowledge Domain",
    description: "Hub for professional composition expansion Step 3.",
    relationshipEvidence: "Primary domain for composition technique topics.",
  },
  {
    domainId: "camera-knowledge",
    knowledgeId: "lc-bridge-camera-knowledge",
    title: "Camera Knowledge (related)",
    description: "Lighting and composition coordinate with camera exposure, lenses, and framing.",
    relationshipEvidence: "Camera settings execute lighting exposure and compositional framing.",
  },
  {
    domainId: "video-production-knowledge",
    knowledgeId: "lc-bridge-video-production-knowledge",
    title: "Video Production Knowledge (related)",
    description: "Lighting and composition serve end-to-end production planning.",
    relationshipEvidence: "Production workflows depend on lighting and composition decisions.",
  },
  {
    domainId: "storytelling-knowledge",
    knowledgeId: "lc-bridge-storytelling-knowledge",
    title: "Storytelling Knowledge (related)",
    description: "Light and frame choices express narrative tone and focus.",
    relationshipEvidence: "Mood and attention are storytelling tools via light and composition.",
  },
  {
    domainId: "product-knowledge",
    knowledgeId: "lc-bridge-product-knowledge",
    title: "Product Photography / Product Knowledge (related)",
    description: "Product presentation depends on specialty lighting and composition.",
    relationshipEvidence: "Product lighting and subject placement prove product value.",
  },
  {
    domainId: "rendering-knowledge",
    knowledgeId: "lc-bridge-rendering-knowledge",
    title: "Rendering Knowledge (related)",
    description: "Capture lighting/color and composition affect finishing and delivery.",
    relationshipEvidence: "Grade and delivery preserve lighting intent and framed hierarchy.",
  },
  {
    domainId: "marketing-knowledge",
    knowledgeId: "lc-bridge-marketing-knowledge",
    title: "Marketing Knowledge (related)",
    description: "Lighting mood and composition hierarchy support marketing messages and CTAs.",
    relationshipEvidence: "Persuasive visuals inherit marketing goals for attention and clarity.",
  },
];

export const REQUIRED_LIGHTING_TOPIC_IDS: LightingTopicId[] = PROFESSIONAL_LIGHTING_TOPICS.map(
  (t) => t.topicId as LightingTopicId
);
export const REQUIRED_COMPOSITION_TOPIC_IDS: CompositionTopicId[] = PROFESSIONAL_COMPOSITION_TOPICS.map(
  (t) => t.topicId as CompositionTopicId
);

export const REQUIRED_LIGHTING_TERMINOLOGY = [
  ...REQUIRED_LIGHTING_TOPIC_IDS,
  "three-point",
  "key light",
  "fill light",
  "color temperature",
  "soft light",
  "hard light",
];

export const REQUIRED_COMPOSITION_TERMINOLOGY = [
  ...REQUIRED_COMPOSITION_TOPIC_IDS,
  "rule of thirds",
  "negative space",
  "visual hierarchy",
  "leading lines",
  "look room",
];

export function getLightingTopic(id: string): ProfessionalLightingCompositionTopic | null {
  return PROFESSIONAL_LIGHTING_TOPICS.find((t) => t.topicId === id || t.knowledgeId === id || t.name.toLowerCase() === id.toLowerCase()) ?? null;
}

export function getCompositionTopic(id: string): ProfessionalLightingCompositionTopic | null {
  return (
    PROFESSIONAL_COMPOSITION_TOPICS.find(
      (t) => t.topicId === id || t.knowledgeId === id || t.name.toLowerCase() === id.toLowerCase()
    ) ?? null
  );
}

export function getLightingCompositionTopic(id: string): ProfessionalLightingCompositionTopic | null {
  return getLightingTopic(id) ?? getCompositionTopic(id);
}

export function findLightingTopics(query: string): ProfessionalLightingCompositionTopic[] {
  return rankTopics(query, PROFESSIONAL_LIGHTING_TOPICS, (t) => identityHay(t), (t) => [t.topicId, t.name, t.title]);
}

export function findCompositionTopics(query: string): ProfessionalLightingCompositionTopic[] {
  return rankTopics(query, PROFESSIONAL_COMPOSITION_TOPICS, (t) => identityHay(t), (t) => [t.topicId, t.name, t.title]);
}

function identityHay(t: ProfessionalLightingCompositionTopic): string[] {
  return [
    t.topicId,
    t.name,
    t.title,
    t.description,
    t.purpose,
    ...t.keywords,
    ...t.whenToUse,
    ...t.bestPractices,
    ...t.relatedCameraTechniques,
    ...t.relatedStorytellingTechniques,
  ];
}

function rankTopics<T>(
  query: string,
  items: T[],
  haystackOf: (item: T) => string[],
  identityOf: (item: T) => string[]
): T[] {
  const lower = query.trim().toLowerCase();
  if (!lower) return [...items];
  const stop = new Set([
    "what", "is", "are", "how", "should", "i", "the", "a", "an", "do", "does", "can", "to", "for",
    "of", "in", "on", "and", "or", "about", "explain", "recommend", "compare", "best", "lighting",
    "composition", "technique", "techniques", "setup", "use", "when", "why", "difference", "between",
  ]);
  const tokens = lower
    .replace(/[^\w\s-]/g, " ")
    .split(/\s+/)
    .filter((t) => t.length > 2 && !stop.has(t));

  const exact = items.filter((item) => {
    const ids = identityOf(item).map((v) => v.toLowerCase());
    return ids.some((id) => id === lower || id.replace(/-/g, " ") === lower || lower.includes(id) || id.includes(lower));
  });
  if (exact.length) {
    return exact.sort((a, b) => {
      const aIds = identityOf(a).map((v) => v.toLowerCase());
      const bIds = identityOf(b).map((v) => v.toLowerCase());
      const score = (ids: string[]) => (ids.some((id) => id === lower || id.replace(/-/g, " ") === lower) ? 1 : 0);
      return score(bIds) - score(aIds);
    });
  }

  const direct = items.filter((item) => {
    const hay = haystackOf(item).join(" ").toLowerCase();
    if (hay.includes(lower)) return true;
    return tokens.length > 0 && tokens.every((token) => hay.includes(token));
  });
  if (direct.length) return direct;

  return items
    .map((item) => {
      const parts = haystackOf(item).map((p) => p.toLowerCase());
      const hay = parts.join(" ");
      let score = 0;
      for (const token of tokens) {
        if (hay.includes(token)) score += 1;
        if (parts[0]?.includes(token)) score += 2;
        if (parts[1]?.includes(token)) score += 2;
      }
      return { item, score };
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((x) => x.item);
}
