import { createHash, randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import type { AiCoreManager } from "../core/ai-core-manager.js";
import type { CreativeWorkspaceManager, CreativeProject } from "../creative-workspace/creative-workspace-manager.js";
import type { DecisionIntelligenceManager } from "../decision-intelligence/decision-intelligence-manager.js";
import type { ImageIntelligenceManager } from "../image-intelligence/image-intelligence-manager.js";
import type { MarketingIntelligenceManager } from "../marketing-intelligence/marketing-intelligence-manager.js";
import type { ProductIntelligenceManager } from "../product-intelligence/product-intelligence-manager.js";
import { LearningCategory, LearningOutcome as FoundationOutcome, LearningSource } from "../learning-memory-engine/types.js";
import { KnowledgeVerificationStatus } from "../knowledge-foundation/types.js";
import { KnowledgeStorageType } from "../knowledge-storage-engine/types.js";
import type { LearningExperience, LearningProfile, LearningStore } from "./types.js";

const EMPTY: LearningStore = { experiences: [], profiles: [], history: [], cache: {}, logs: [] };
/** Captures verified project outcomes and feedback to improve later local recommendations without replacing existing foundation ownership. */
export class AiLearningManager {
  private root = ""; private core: AiCoreManager | null = null; private workspace: CreativeWorkspaceManager | null = null; private products: ProductIntelligenceManager | null = null; private images: ImageIntelligenceManager | null = null; private marketing: MarketingIntelligenceManager | null = null; private decisions: DecisionIntelligenceManager | null = null; private store: LearningStore = structuredClone(EMPTY);
  readonly pipeline = new LearningPipelineEngine(); readonly experiences = new ExperienceCollectionEngine(); readonly feedback = new FeedbackProcessingEngine(); readonly performance = new PerformanceLearningEngine(); readonly decision = new DecisionLearningEngine(); readonly creative = new CreativeLearningEngine(); readonly product = new ProductLearningEngine(); readonly workflow = new WorkflowLearningEngine(); readonly knowledge = new KnowledgeEvolutionEngine(); readonly evolution = new IntelligenceEvolutionManager(); readonly recommendations = new RecommendationLearningEngine(); readonly analytics = new LearningAnalyticsManager(this); readonly history = new LearningHistoryManager(this); readonly validation = new LearningValidationEngine(); readonly optimization = new LearningOptimizationEngine();
  async initialize(storageRoot: string, dependencies: { core: AiCoreManager; workspace: CreativeWorkspaceManager; products: ProductIntelligenceManager; images: ImageIntelligenceManager; marketing: MarketingIntelligenceManager; decisions: DecisionIntelligenceManager }): Promise<void> { this.root = path.join(storageRoot, "learning-intelligence-runtime"); this.core = dependencies.core; this.workspace = dependencies.workspace; this.products = dependencies.products; this.images = dependencies.images; this.marketing = dependencies.marketing; this.decisions = dependencies.decisions; await fs.mkdir(this.root, { recursive: true }); this.store = await this.readStore(); this.registerFoundations(); this.log("info", "AI learning runtime restored."); await this.persist(); }
  isInitialized(): boolean { return Boolean(this.root); }
  async learnFromProject(projectId: string, outcome: LearningExperience["outcome"], detail?: string): Promise<LearningProfile> { this.ensureReady(); const project = await this.workspace!.getProject(projectId); if (!project) throw new Error("Project not found"); const validation = this.validation.validate(project); if (!validation.valid) throw new Error(validation.issues.join(" ")); const key = this.key(project, outcome, detail); const cached = this.store.cache[key] ? this.store.profiles.find((item) => item.id === this.store.cache[key]) : undefined; if (cached) return { ...cached, cached: true }; const [product, imageProfiles, marketing, decision] = await Promise.all([this.products!.analyze(projectId), this.images!.analyzeProject(projectId), this.marketing!.analyze(projectId), this.decisions!.decide(projectId)]); const experience = this.experiences.collect(project, outcome, detail, product.quality.score, imageProfiles, marketing.score, decision.confidence); this.store.experiences.unshift(experience); const recommendations = this.recommendations.create(experience, decision, marketing); const profile: LearningProfile = { id: randomUUID(), projectId, progress: this.pipeline.progress(outcome, product.quality.score, marketing.score), knowledgeGrowth: this.knowledge.growth(experience), improvements: this.optimization.improvements(experience, decision), recommendationHistory: recommendations, userPreferences: this.feedback.preferences(detail), evolution: this.evolution.timeline(experience), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), cached: false }; this.store.profiles = this.store.profiles.filter((item) => item.projectId !== projectId); this.store.profiles.unshift(profile); this.store.cache[key] = profile.id; await this.updateFoundations(project, experience, profile); this.history.record(projectId, outcome, experience.lesson); this.log(outcome === "failure" ? "warning" : "info", `Learning profile recorded for ${project.name}: ${outcome}.`); await this.persist(); return { ...profile }; }
  async recordFeedback(projectId: string, feedback: string): Promise<LearningProfile> { if (!feedback.trim()) throw new Error("Feedback is required"); return this.learnFromProject(projectId, "feedback", feedback.trim()); }
  async getDashboard(projectId?: string): Promise<{ profiles: LearningProfile[]; experiences: LearningExperience[]; history: LearningStore["history"]; logs: LearningStore["logs"]; analytics: Record<string, number>; integrations: Record<string, boolean> }> { return { profiles: structuredClone(this.store.profiles.filter((item) => !projectId || item.projectId === projectId)), experiences: structuredClone(this.store.experiences.filter((item) => !projectId || item.projectId === projectId)), history: this.store.history.filter((item) => !projectId || item.projectId === projectId), logs: [...this.store.logs], analytics: this.analytics.summary(), integrations: { aiCore: Boolean(this.core), creativePipeline: Boolean(this.core?.workflowEngine), generationLayer: Boolean(this.core?.imageGenerationFoundation || this.core?.videoGenerationFoundation), decisionIntelligence: Boolean(this.decisions), productIntelligence: Boolean(this.products), imageIntelligence: Boolean(this.images), marketingIntelligence: Boolean(this.marketing), workflowEngine: Boolean(this.core?.workflowEngine), automationEngine: Boolean(this.core?.workflowEngine), taskScheduler: Boolean(this.core?.taskManager), memoryFoundation: Boolean(this.core?.memoryFoundation?.learningMemoryEngine), knowledgeFoundation: Boolean(this.core?.knowledgeFoundation?.getStorageEngine()) } }; }
  async persist(): Promise<void> { await fs.writeFile(path.join(this.root, "learning.json"), `${JSON.stringify(this.store, null, 2)}\n`, "utf8"); }
  log(level: "info" | "warning" | "error", message: string): void { this.store.logs.unshift({ at: new Date().toISOString(), level, message }); this.store.logs.splice(100); this.core?.logger?.info("learning-intelligence", message); }
  private registerFoundations(): void {
    // Studio learning writes through existing Memory/Knowledge engines.
    // PREPARED_MEMORY_CATEGORIES / PREPARED_KNOWLEDGE_CATEGORIES are closed catalogs.
    // Registering memoryId/knowledgeId "learning-intelligence-runtime" throws
    // "Unknown memory category" and aborts persistent runtime boot.
    if (this.core?.memoryFoundation?.isStartupComplete()) {
      this.log("info", "Attached to existing learning-memory foundation.");
    }
    if (this.core?.knowledgeFoundation?.isStartupComplete()) {
      this.log("info", "Attached to existing workflow-knowledge foundation.");
    }
  }
  private async updateFoundations(project: CreativeProject, experience: LearningExperience, profile: LearningProfile): Promise<void> { const memory = this.core?.memoryFoundation?.learningMemoryEngine; if (memory?.isStartupComplete()) await memory.learnFromEvent({ source: experience.outcome === "feedback" ? LearningSource.UserFeedback : LearningSource.ProjectHistory, category: LearningCategory.Project, title: experience.title, description: experience.lesson, relatedProject: project.id, outcome: experience.outcome === "success" ? FoundationOutcome.Success : experience.outcome === "failure" ? FoundationOutcome.Failure : FoundationOutcome.Correction, qualityScore: experience.qualityScore, userFeedback: experience.outcome === "feedback" ? experience.lesson : undefined, lessonLearned: experience.lesson, patterns: profile.improvements }); const knowledge = this.core?.knowledgeFoundation; if (knowledge?.isStartupComplete()) await knowledge.getStorageEngine().storeRecord({ knowledgeId: `learning-${experience.id}`, knowledgeType: KnowledgeStorageType.Workflow, category: "learning", title: experience.title, description: experience.lesson, summary: `Project learning: ${experience.outcome}, quality ${experience.qualityScore}`, source: "learning-intelligence-runtime", tags: ["learning", experience.outcome, project.platform], keywords: [project.productInformation.category, project.platform, ...profile.improvements], relatedKnowledge: [], relatedMemory: [], qualityScore: experience.qualityScore, confidenceScore: profile.progress, sourceReliability: 80, verificationStatus: KnowledgeVerificationStatus.Pending, payload: { experience, profile } as unknown as Record<string, unknown> }); }
  private key(project: CreativeProject, outcome: LearningExperience["outcome"], detail?: string): string { return createHash("sha256").update(JSON.stringify({ outcome, detail, product: project.productInformation, campaign: project.campaignInformation, audience: project.targetAudience, platform: project.platform, images: project.productImages.map((item) => item.id) })).digest("hex"); }
  private async readStore(): Promise<LearningStore> { try { const saved = JSON.parse(await fs.readFile(path.join(this.root, "learning.json"), "utf8")) as Partial<LearningStore>; return { ...structuredClone(EMPTY), ...saved, experiences: saved.experiences ?? [], profiles: saved.profiles ?? [], history: saved.history ?? [], cache: saved.cache ?? {}, logs: saved.logs ?? [] }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return structuredClone(EMPTY); throw error; } }
  private ensureReady(): void { if (!this.root || !this.workspace || !this.products || !this.images || !this.marketing || !this.decisions) throw new Error("AI Learning Manager is not initialized"); }
}
export class LearningPipelineEngine { progress(outcome: LearningExperience["outcome"], product: number, marketing: number): number { return Math.max(35, Math.min(98, Math.round(product * .4 + marketing * .35 + (outcome === "success" ? 20 : outcome === "feedback" ? 12 : 4)))); } }
export class ExperienceCollectionEngine { collect(project: CreativeProject, outcome: LearningExperience["outcome"], detail: string | undefined, product: number, images: Array<{ quality: { score: number } }>, marketing: number, decision: number): LearningExperience { const imageQuality = images.length ? Math.round(images.reduce((sum, item) => sum + item.quality.score, 0) / images.length) : 0; const qualityScore = Math.round((product + imageQuality + marketing + decision) / 4); const lesson = detail || (outcome === "success" ? `The approved ${project.platform} workflow aligned product evidence, marketing strategy, and decision guidance.` : "Review missing evidence, campaign clarity, or workflow checkpoints before repeating this project path."); return { id: randomUUID(), projectId: project.id, outcome, title: `${project.name} ${outcome} learning`, lesson, qualityScore, workflowEfficiency: outcome === "success" ? 88 : outcome === "feedback" ? 76 : 45, recommendations: outcome === "success" ? ["Reuse the evidence-first workflow for comparable projects."] : ["Strengthen project inputs and review the selected workflow before retrying."], preferences: detail ? [detail] : [], createdAt: new Date().toISOString() }; } }
export class FeedbackProcessingEngine { preferences(detail?: string): string[] { return detail ? [`User feedback captured: ${detail}`] : []; } }
export class PerformanceLearningEngine { assess(experience: LearningExperience): string { return `${experience.workflowEfficiency}% workflow efficiency from ${experience.outcome} outcome.`; } }
export class DecisionLearningEngine { learn(profile: { selected: { label: string }; confidence: number }): string { return `${profile.selected.label} was evaluated at ${profile.confidence}% decision confidence.`; } }
export class CreativeLearningEngine { learn(experience: LearningExperience): string { return `Creative quality signal: ${experience.qualityScore}/100.`; } }
export class ProductLearningEngine { learn(project: CreativeProject): string { return `Product category learned: ${project.productInformation.category}.`; } }
export class WorkflowLearningEngine { learn(experience: LearningExperience): string { return `Workflow outcome recorded as ${experience.outcome}.`; } }
export class KnowledgeEvolutionEngine { growth(experience: LearningExperience): number { return experience.outcome === "success" ? 12 : experience.outcome === "feedback" ? 9 : 6; } }
export class IntelligenceEvolutionManager { timeline(experience: LearningExperience): string[] { return [`Experience captured: ${experience.outcome}.`, "Memory and knowledge foundations updated through their existing engines.", "Future recommendations will include compatible stored lessons."]; } }
export class RecommendationLearningEngine { create(experience: LearningExperience, decision: { selected: { label: string }; confidence: number }, marketing: { recommendations: string[] }): string[] { return [...experience.recommendations, `Prefer ${decision.selected.label} when evidence remains comparable (${decision.confidence}% decision confidence).`, ...marketing.recommendations.slice(0, 2)]; } }
export class LearningAnalyticsManager { constructor(private readonly manager: AiLearningManager) {} summary(): Record<string, number> { const items = this.manager["store"].experiences; return { experiences: items.length, successfulProjects: items.filter((item) => item.outcome === "success").length, failedProjects: items.filter((item) => item.outcome === "failure").length, feedbackSignals: items.filter((item) => item.outcome === "feedback").length, averageQuality: items.length ? Math.round(items.reduce((sum, item) => sum + item.qualityScore, 0) / items.length) : 0, knowledgeGrowth: this.manager["store"].profiles.reduce((sum, item) => sum + item.knowledgeGrowth, 0) }; } }
export class LearningHistoryManager { constructor(private readonly manager: AiLearningManager) {} record(projectId: string, event: string, detail: string): void { this.manager["store"].history.unshift({ id: randomUUID(), at: new Date().toISOString(), projectId, event, detail }); this.manager["store"].history.splice(100); } }
export class LearningValidationEngine { validate(project: CreativeProject): { valid: boolean; issues: string[] } { const issues = [!project.productInformation.name.trim() ? "Product name is required for learning." : "", !project.campaignInformation.objective.trim() ? "Campaign objective is required for learning." : ""].filter(Boolean); return { valid: !issues.length, issues }; } }
export class LearningOptimizationEngine { improvements(experience: LearningExperience, decision: { selected: { label: string } }): string[] { return experience.outcome === "success" ? [`Retain ${decision.selected.label} for similar evidence-rich projects.`, "Preserve the product-to-marketing analysis order."] : ["Collect stronger evidence before execution.", "Use decision rationale and review signals to refine the next workflow."]; } }