import { createHash, randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import type { AiCoreManager } from "../core/ai-core-manager.js";
import type { CreativeWorkspaceManager, CreativeProject } from "../creative-workspace/creative-workspace-manager.js";
import type { ImageIntelligenceManager } from "../image-intelligence/image-intelligence-manager.js";
import type { MarketingIntelligenceManager } from "../marketing-intelligence/marketing-intelligence-manager.js";
import type { AiModelManager } from "../model-management/ai-model-manager.js";
import type { ProductIntelligenceManager } from "../product-intelligence/product-intelligence-manager.js";
import type { DecisionIntelligenceProfile, DecisionIntelligenceStore, DecisionOption, DecisionTaskKind } from "./types.js";

const EMPTY: DecisionIntelligenceStore = { profiles: [], history: [], cache: {}, logs: [] };
/** Persistent project-level reasoning layer. It recommends and records decisions; execution remains owned by existing managers. */
export class DecisionIntelligenceManager {
  private root = ""; private core: AiCoreManager | null = null; private workspace: CreativeWorkspaceManager | null = null; private models: AiModelManager | null = null; private products: ProductIntelligenceManager | null = null; private images: ImageIntelligenceManager | null = null; private marketing: MarketingIntelligenceManager | null = null; private store: DecisionIntelligenceStore = structuredClone(EMPTY);
  readonly analysis = new DecisionAnalysisEngine(); readonly planning = new DecisionPlanningEngine(); readonly comparison = new DecisionComparisonEngine(); readonly scoring = new DecisionScoringEngine(); readonly strategy = new StrategySelectionEngine(); readonly workflow = new WorkflowSelectionEngine(); readonly model = new AiModelSelectionEngine(); readonly resources = new ResourceDecisionEngine(); readonly risk = new RiskEvaluationEngine(); readonly confidence = new ConfidenceScoringEngine(); readonly validation = new DecisionValidationEngine(); readonly explanation = new DecisionExplanationEngine(); readonly memory = new DecisionMemoryManager(this); readonly analytics = new DecisionAnalyticsManager(this); readonly history = new DecisionHistoryManager(this); readonly cache = new DecisionCacheManager();
  async initialize(storageRoot: string, dependencies: { core: AiCoreManager; workspace: CreativeWorkspaceManager; models: AiModelManager; products: ProductIntelligenceManager; images: ImageIntelligenceManager; marketing: MarketingIntelligenceManager }): Promise<void> { this.root = path.join(storageRoot, "decision-intelligence-runtime"); this.core = dependencies.core; this.workspace = dependencies.workspace; this.models = dependencies.models; this.products = dependencies.products; this.images = dependencies.images; this.marketing = dependencies.marketing; await fs.mkdir(this.root, { recursive: true }); this.store = await this.readStore(); this.log("info", "Decision intelligence runtime restored."); await this.persist(); }
  isInitialized(): boolean { return Boolean(this.root); }
  async decide(projectId: string, taskKind: DecisionTaskKind = "pipeline"): Promise<DecisionIntelligenceProfile> { this.ensureReady(); const project = await this.workspace!.getProject(projectId); if (!project) throw new Error("Project not found"); const valid = this.validation.validate(project); if (!valid.valid) throw new Error(valid.issues.join(" ")); const key = this.cache.key(project, taskKind); const cached = this.store.cache[key] ? this.store.profiles.find((profile) => profile.id === this.store.cache[key]) : undefined; if (cached) return { ...cached, cached: true }; const [product, imageProfiles, marketing, resources] = await Promise.all([this.products!.analyze(projectId), this.images!.analyzeProject(projectId), this.marketing!.analyze(projectId), this.resources.analyze(this.models!)]); const options = this.scoring.score(this.planning.options(project, taskKind), product.quality.score, imageProfiles, marketing.score, resources); const selected = this.strategy.select(this.comparison.rank(options)); const model = await this.model.select(this.models!, taskKind); const confidence = this.confidence.score(product.quality.score, marketing.score, imageProfiles.length, selected.risk); const learnedFrom = this.memory.relevant(project, taskKind); const profile: DecisionIntelligenceProfile = { id: randomUUID(), projectId, taskKind, objective: project.campaignInformation.objective, priority: this.analysis.priority(project, taskKind), options, selected, confidence, resourceAnalysis: resources, modelRecommendation: model, explanation: this.explanation.create(selected, model, confidence, learnedFrom), risks: this.risk.evaluate(project, imageProfiles, resources), learnedFrom, createdAt: new Date().toISOString(), cached: false }; this.store.profiles = this.store.profiles.filter((item) => !(item.projectId === projectId && item.taskKind === taskKind)); this.store.profiles.unshift(profile); this.store.cache[key] = profile.id; this.history.record(projectId, "decision", `Selected ${selected.label} at ${confidence}% confidence.`); this.log("info", `Decision profile prepared for ${project.name}: ${selected.label}.`); await this.persist(); return { ...profile }; }
  async getProfile(projectId: string, taskKind: DecisionTaskKind = "pipeline"): Promise<DecisionIntelligenceProfile | null> { return this.store.profiles.find((profile) => profile.projectId === projectId && profile.taskKind === taskKind) ?? null; }
  async getDashboard(projectId?: string): Promise<{ profiles: DecisionIntelligenceProfile[]; history: DecisionIntelligenceStore["history"]; logs: DecisionIntelligenceStore["logs"]; analytics: Record<string, number>; integrations: Record<string, boolean> }> { return { profiles: structuredClone(this.store.profiles.filter((item) => !projectId || item.projectId === projectId)), history: this.store.history.filter((item) => !projectId || item.projectId === projectId), logs: [...this.store.logs], analytics: this.analytics.summary(), integrations: { aiCore: Boolean(this.core), decisionFoundation: Boolean(this.core?.decisionEngine), productIntelligence: Boolean(this.products), imageIntelligence: Boolean(this.images), marketingIntelligence: Boolean(this.marketing), modelManagement: Boolean(this.models), memoryFoundation: Boolean(this.core?.memoryFoundation), knowledgeFoundation: Boolean(this.core?.knowledgeFoundation), workflowEngine: Boolean(this.core?.workflowEngine), taskScheduler: Boolean(this.core?.taskManager), automationEngine: Boolean(this.core?.workflowEngine), stateManager: Boolean(this.core?.stateManager), generationLayer: Boolean(this.core?.imageGenerationFoundation || this.core?.videoGenerationFoundation) } }; }
  async persist(): Promise<void> { await fs.writeFile(path.join(this.root, "decisions.json"), `${JSON.stringify(this.store, null, 2)}\n`, "utf8"); }
  log(level: "info" | "warning" | "error", message: string): void { this.store.logs.unshift({ at: new Date().toISOString(), level, message }); this.store.logs.splice(100); this.core?.logger.info("decision-intelligence", message); }
  private async readStore(): Promise<DecisionIntelligenceStore> { try { const saved = JSON.parse(await fs.readFile(path.join(this.root, "decisions.json"), "utf8")) as Partial<DecisionIntelligenceStore>; return { ...structuredClone(EMPTY), ...saved, profiles: saved.profiles ?? [], history: saved.history ?? [], cache: saved.cache ?? {}, logs: saved.logs ?? [] }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return structuredClone(EMPTY); throw error; } }
  private ensureReady(): void { if (!this.root || !this.workspace || !this.models || !this.products || !this.images || !this.marketing) throw new Error("Decision Intelligence Manager is not initialized"); }
}
export class DecisionAnalysisEngine { priority(project: CreativeProject, task: DecisionTaskKind): DecisionIntelligenceProfile["priority"] { return task === "pipeline" || /launch|urgent|deadline/i.test(project.campaignInformation.objective) ? "high" : "normal"; } }
export class DecisionPlanningEngine { options(project: CreativeProject, task: DecisionTaskKind): DecisionOption[] { const platform = project.platform; return [{ id: "quality-first", label: "Quality-first creative workflow", workflow: "analyze -> plan -> generate -> review", creativeApproach: "product proof with marketing-led narrative", renderingStrategy: "high-quality approved artifact export", score: 0, risk: "low", resourceCost: "medium", reasons: ["Preserves evidence and review checkpoints", `Optimized for ${platform}`] }, { id: "balanced", label: "Balanced delivery workflow", workflow: "analyze -> plan -> generate", creativeApproach: "focused product demonstration", renderingStrategy: "standard local artifact preparation", score: 0, risk: "medium", resourceCost: "low", reasons: ["Reduces resource use", "Keeps creative planning intact"] }, { id: "rapid", label: "Rapid concept workflow", workflow: "plan -> generate", creativeApproach: "single-message social concept", renderingStrategy: "lightweight preview preparation", score: 0, risk: "high", resourceCost: "low", reasons: ["Fastest iteration", "Requires later evidence review"] }]; } }
export class DecisionComparisonEngine { rank(options: DecisionOption[]): DecisionOption[] { return [...options].sort((left, right) => right.score - left.score); } }
export class DecisionScoringEngine { score(options: DecisionOption[], productScore: number, images: Array<{ quality: { score: number } }>, marketingScore: number, resources: DecisionIntelligenceProfile["resourceAnalysis"]): DecisionOption[] { const imageScore = images.length ? Math.round(images.reduce((sum, item) => sum + item.quality.score, 0) / images.length) : 0; return options.map((option, index) => ({ ...option, score: Math.min(98, Math.max(45, Math.round(productScore * .3 + imageScore * .15 + marketingScore * .25 + (resources.gpuAvailable ? 12 : 7) + [15, 9, 2][index])) ) })); } }
export class StrategySelectionEngine { select(options: DecisionOption[]): DecisionOption { return options[0]; } }
export class WorkflowSelectionEngine { select(profile: DecisionIntelligenceProfile): string { return profile.selected.workflow; } }
export class AiModelSelectionEngine { async select(models: AiModelManager, task: DecisionTaskKind): Promise<DecisionIntelligenceProfile["modelRecommendation"]> { const category = task === "video-generation" ? "video" : task === "image-generation" ? "image" : task === "analysis" ? "vision" : "language"; const selected = await models.selectBest(category); return selected ? { id: selected.id, name: selected.name, category: selected.category, reason: "Installed, healthy, and resource-compatible model with the best local selection rank." } : { id: `studio-${category}-base`, name: `Studio ${category} profile`, category, reason: "No installed compatible model is available; use this catalog recommendation after installation and validation." }; } }
export class ResourceDecisionEngine { async analyze(models: AiModelManager): Promise<DecisionIntelligenceProfile["resourceAnalysis"]> { const hardware = await models.detectHardware(); return { availableRamMb: hardware.ram.freeMb, availableStorageMb: hardware.storage.freeMb, gpuAvailable: hardware.gpu.available, recommendation: hardware.gpu.available ? "Use the quality-first workflow with hardware-aware model selection." : "Use balanced local workflow; confirm GPU-intensive models before loading." }; } }
export class RiskEvaluationEngine { evaluate(project: CreativeProject, images: Array<{ quality: { score: number } }>, resources: DecisionIntelligenceProfile["resourceAnalysis"]): string[] { return unique([images.length ? "Image evidence is metadata-derived where visual providers are unavailable." : "No uploaded image evidence is available.", !resources.gpuAvailable ? "No supported GPU detected; resource-heavy model loading may be constrained." : "", !project.campaignInformation.callToAction ? "Campaign CTA is not specified." : ""].filter(Boolean)); } }
export class ConfidenceScoringEngine { score(product: number, marketing: number, imageCount: number, risk: DecisionOption["risk"]): number { return Math.min(96, Math.max(45, Math.round(product * .35 + marketing * .35 + Math.min(15, imageCount * 5) + (risk === "low" ? 11 : risk === "medium" ? 6 : 1)))); } }
export class DecisionValidationEngine { validate(project: CreativeProject): { valid: boolean; issues: string[] } { const issues = [!project.productInformation.name.trim() ? "Product name is required for a decision." : "", !project.campaignInformation.objective.trim() ? "Campaign objective is required for a decision." : "", !project.targetAudience.trim() ? "Target audience is required for a decision." : ""].filter(Boolean); return { valid: !issues.length, issues }; } }
export class DecisionExplanationEngine { create(selected: DecisionOption, model: DecisionIntelligenceProfile["modelRecommendation"], confidence: number, learned: string[]): string { return `${selected.label} was selected because it achieved the highest evidence-weighted score (${selected.score}/100), balances ${selected.resourceCost} resource cost with ${selected.risk} risk, and has ${confidence}% confidence. Model recommendation: ${model.name}. ${learned.length ? `It also considers ${learned.length} compatible prior decision(s).` : "No compatible prior decision is stored yet."}`; } }
export class DecisionMemoryManager { constructor(private readonly manager: DecisionIntelligenceManager) {} relevant(project: CreativeProject, task: DecisionTaskKind): string[] { return this.manager["store"].profiles.filter((item) => item.taskKind === task && item.projectId !== project.id).slice(0, 3).map((item) => `${item.selected.label} (${item.confidence}% confidence)`); } }
export class DecisionAnalyticsManager { constructor(private readonly manager: DecisionIntelligenceManager) {} summary(): Record<string, number> { const profiles = this.manager["store"].profiles; return { decisions: profiles.length, averageConfidence: profiles.length ? Math.round(profiles.reduce((sum, item) => sum + item.confidence, 0) / profiles.length) : 0, qualityFirstSelections: profiles.filter((item) => item.selected.id === "quality-first").length, learnedDecisions: profiles.filter((item) => item.learnedFrom.length > 0).length, cachedDecisions: Object.keys(this.manager["store"].cache).length }; } }
export class DecisionHistoryManager { constructor(private readonly manager: DecisionIntelligenceManager) {} record(projectId: string, event: string, detail: string): void { this.manager["store"].history.unshift({ id: randomUUID(), at: new Date().toISOString(), projectId, event, detail }); this.manager["store"].history.splice(100); } }
export class DecisionCacheManager { key(project: CreativeProject, task: DecisionTaskKind): string { return createHash("sha256").update(JSON.stringify({ task, product: project.productInformation, brand: project.brandInformation, campaign: project.campaignInformation, audience: project.targetAudience, platform: project.platform, images: project.productImages.map((item) => [item.id, item.fileName, item.sizeBytes]) })).digest("hex"); } }
function unique(values: string[]): string[] { return [...new Set(values)]; }