import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import type { AiCoreManager } from "../core/ai-core-manager.js";
import type { AiToolManager } from "../tool-management/tool-manager.js";
import { PLUGIN_CATEGORIES, type PluginExecutionRequest, type PluginExecutionResult, type PluginFactory, type PluginHealth, type PluginManifest, type PluginRuntime, type PluginSandbox, type RegisteredPlugin } from "./types.js";

export const PLATFORM_VERSION = "0.1.0";
const health = (): PluginHealth => ({ available: false, compatible: false, executionCount: 0, failureCount: 0, errorRate: 0, responseTimeMs: 0, cpuUsageMs: 0, ramUsageBytes: 0, stability: "healthy", lastCheckedAt: new Date().toISOString() });

/** Manifest-driven local extension manager. Only trusted, compiled factories are executable. */
export class AiPluginManager {
  private root = "";
  private core: AiCoreManager | null = null;
  private tools: AiToolManager | null = null;
  private initialized = false;
  private readonly plugins = new Map<string, RegisteredPlugin>();
  private readonly factories = new Map<string, PluginFactory>();
  private readonly runtimes = new Map<string, PluginRuntime>();
  private readonly logs: Array<{ at: string; event: string; pluginId?: string; detail: string }> = [];

  async initialize(core: AiCoreManager, tools: AiToolManager, storageRoot: string): Promise<void> { this.core = core; this.tools = tools; this.root = path.join(storageRoot, "plugin-management"); await fs.mkdir(this.root, { recursive: true }); await this.restore(); this.initialized = true; }
  isInitialized(): boolean { return this.initialized; }
  list(): RegisteredPlugin[] { return [...this.plugins.values()].filter((plugin) => plugin.status !== "removed").map((plugin) => structuredClone(plugin)); }
  get(pluginId: string): RegisteredPlugin | null { const plugin = this.plugins.get(pluginId); return plugin && plugin.status !== "removed" ? structuredClone(plugin) : null; }
  getLogs(): ReadonlyArray<{ at: string; event: string; pluginId?: string; detail: string }> { return this.logs; }

  async install(manifest: PluginManifest, factory: PluginFactory): Promise<RegisteredPlugin> {
    this.ensureReady(); this.validateManifest(manifest); if (manifest.external) throw new Error("External plugin code is disabled until a signed sandbox host is available"); if (this.plugins.has(manifest.id) && this.plugins.get(manifest.id)!.status !== "removed") throw new Error(`Plugin already installed: ${manifest.id}`); if (this.factories.has(manifest.id)) throw new Error(`Plugin conflict: ${manifest.id}`);
    const now = new Date().toISOString(); const plugin: RegisteredPlugin = { ...manifest, status: "installed", health: health(), installedAt: now, updatedAt: now };
    this.plugins.set(plugin.id, plugin); this.factories.set(plugin.id, factory); await this.log("installation", plugin.id, `Installed ${plugin.name} v${plugin.version}`); await this.persist(); return structuredClone(plugin);
  }

  async discover(plugins: Array<{ manifest: PluginManifest; factory: PluginFactory }>): Promise<number> { let count = 0; for (const plugin of plugins) { const existing = this.plugins.get(plugin.manifest.id); if (!existing) { await this.install(plugin.manifest, plugin.factory); count++; } else if (existing.status !== "removed") { this.factories.set(plugin.manifest.id, plugin.factory); if (existing.status === "initialized" || existing.status === "loaded" || existing.status === "paused") { existing.status = "installed"; existing.updatedAt = new Date().toISOString(); } } } await this.persist(); return count; }
  async initializePlugin(pluginId: string): Promise<void> { const plugin = this.require(pluginId); this.validatePlugin(plugin); const runtime = this.factories.get(pluginId)?.(); if (!runtime) throw new Error("Trusted plugin factory is unavailable"); await runtime.initialize(this.sandbox(plugin)); this.runtimes.set(pluginId, runtime); plugin.status = "initialized"; plugin.updatedAt = new Date().toISOString(); await this.log("initialization", pluginId, "Plugin initialized"); await this.persist(); }
  async load(pluginId: string): Promise<void> { const plugin = this.require(pluginId); if (plugin.status === "disabled") throw new Error("Plugin is disabled"); if (!this.runtimes.has(pluginId)) await this.initializePlugin(pluginId); plugin.status = "loaded"; plugin.updatedAt = new Date().toISOString(); await this.log("loading", pluginId, "Plugin loaded"); await this.persist(); }
  async unload(pluginId: string): Promise<void> { const plugin = this.require(pluginId); const runtime = this.runtimes.get(pluginId); if (runtime) await runtime.shutdown(); this.runtimes.delete(pluginId); if (plugin.status !== "disabled") plugin.status = "installed"; plugin.updatedAt = new Date().toISOString(); await this.log("unloading", pluginId, "Plugin unloaded"); await this.persist(); }
  async enable(pluginId: string): Promise<void> { const plugin = this.require(pluginId); plugin.status = "installed"; plugin.updatedAt = new Date().toISOString(); await this.persist(); }
  async disable(pluginId: string): Promise<void> { const plugin = this.require(pluginId); await this.unload(pluginId); plugin.status = "disabled"; plugin.updatedAt = new Date().toISOString(); await this.persist(); }
  async shutdown(): Promise<void> { for (const pluginId of [...this.runtimes.keys()]) await this.unload(pluginId); this.initialized = false; }
  async pause(pluginId: string): Promise<void> { const plugin = this.require(pluginId); if (plugin.status !== "loaded") throw new Error("Only loaded plugins can be paused"); plugin.status = "paused"; await this.persist(); }
  async resume(pluginId: string): Promise<void> { const plugin = this.require(pluginId); if (plugin.status !== "paused") throw new Error("Only paused plugins can be resumed"); plugin.status = "loaded"; await this.persist(); }
  async remove(pluginId: string): Promise<void> { const plugin = this.require(pluginId); await this.unload(pluginId); plugin.status = "removed"; this.factories.delete(pluginId); plugin.updatedAt = new Date().toISOString(); await this.persist(); }
  async update(pluginId: string, version: string): Promise<RegisteredPlugin> { const plugin = this.require(pluginId); if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error("Plugin version must be semantic"); plugin.version = version; plugin.updatedAt = new Date().toISOString(); await this.log("update", pluginId, `Plugin updated to ${version}`); await this.persist(); return structuredClone(plugin); }
  async configure(pluginId: string, configuration: Record<string, unknown>): Promise<RegisteredPlugin> { const plugin = this.require(pluginId); plugin.configuration = structuredClone(configuration); plugin.updatedAt = new Date().toISOString(); await this.persist(); return structuredClone(plugin); }

  validate(pluginId: string): { valid: boolean; errors: string[] } { const plugin = this.require(pluginId); try { this.validatePlugin(plugin); return { valid: true, errors: [] }; } catch (error) { return { valid: false, errors: [error instanceof Error ? error.message : String(error)] }; } }
  async execute(request: PluginExecutionRequest): Promise<PluginExecutionResult> { const started = performance.now(); const memoryBefore = process.memoryUsage().heapUsed; const plugin = this.plugins.get(request.pluginId); try { if (!plugin) throw new Error("Plugin not found"); if (plugin.status !== "loaded") throw new Error("Plugin is not loaded"); this.validatePermissions(plugin, request.permissions); const runtime = this.runtimes.get(plugin.id); if (!runtime) throw new Error("Plugin runtime is unavailable"); const output = await runtime.execute(request.action, structuredClone(request.input), this.sandbox(plugin)); this.record(plugin, started, memoryBefore, true); await this.log("execution", plugin.id, `Action ${request.action} completed in ${Math.round(performance.now() - started)}ms`); await this.persist(); return { pluginId: plugin.id, status: "succeeded", output, durationMs: Math.round(performance.now() - started) }; } catch (error) { if (plugin) { plugin.lastError = error instanceof Error ? error.message : String(error); this.record(plugin, started, memoryBefore, false); await this.log("security-or-error", plugin.id, plugin.lastError); await this.persist(); } return { pluginId: request.pluginId, status: "rejected", error: error instanceof Error ? error.message : String(error), durationMs: Math.round(performance.now() - started) }; } }
  async monitor(pluginId?: string): Promise<Record<string, PluginHealth>> { const targets = pluginId ? [this.require(pluginId)] : this.list().map((plugin) => this.require(plugin.id)); for (const plugin of targets) { const runtime = this.runtimes.get(plugin.id); plugin.health.available = Boolean(runtime); plugin.health.compatible = this.isCompatible(plugin) && plugin.dependencies.every((dependency) => dependency === "ai-core" || Boolean(this.core?.registry.getEntry(dependency))); if (runtime?.healthCheck) { const result = await runtime.healthCheck(); plugin.health.stability = result.healthy ? "healthy" : "degraded"; } plugin.health.lastCheckedAt = new Date().toISOString(); } await this.persist(); return Object.fromEntries(targets.map((plugin) => [plugin.id, structuredClone(plugin.health)])); }
  getIntegrationStatus(): Record<string, boolean> { return { aiCore: Boolean(this.core), toolRegistry: Boolean(this.tools), toolManager: Boolean(this.tools), workflowEngine: Boolean(this.core?.workflowEngine), communicationBus: Boolean(this.core?.communicationBus), taskScheduler: Boolean(this.core?.taskManager), automationEngine: Boolean(this.core?.workflowEngine), multiAgentSystem: false }; }

  private sandbox(plugin: RegisteredPlugin): PluginSandbox { return { getConfiguration: () => structuredClone(plugin.configuration), executeTool: async (toolId, input, grantedPermissions = []) => { this.validatePermissions(plugin, grantedPermissions); const result = await this.tools!.execute({ toolId, input, permissions: grantedPermissions }); if (result.status !== "succeeded" || !result.output) throw new Error(result.error ?? "Tool execution failed"); return result.output; } }; }
  private record(plugin: RegisteredPlugin, started: number, memoryBefore: number, success: boolean): void { plugin.health.executionCount++; if (!success) plugin.health.failureCount++; plugin.health.responseTimeMs = Math.round(performance.now() - started); plugin.health.cpuUsageMs += plugin.health.responseTimeMs; plugin.health.ramUsageBytes = Math.max(0, process.memoryUsage().heapUsed - memoryBefore); plugin.health.errorRate = Math.round(plugin.health.failureCount / plugin.health.executionCount * 100); plugin.health.stability = plugin.health.errorRate >= 50 ? "unhealthy" : plugin.health.errorRate > 0 ? "degraded" : "healthy"; plugin.health.lastCheckedAt = new Date().toISOString(); }
  private validatePlugin(plugin: PluginManifest): void { this.validateManifest(plugin); if (!this.isCompatible(plugin)) throw new Error(`Plugin requires platform ${plugin.compatiblePlatformVersion}`); if (!this.factories.has(plugin.id)) throw new Error("Trusted plugin factory is unavailable"); }
  private validateManifest(manifest: PluginManifest): void { if (!/^[a-z0-9][a-z0-9.-]{2,100}$/i.test(manifest.id)) throw new Error("Plugin id is invalid"); if (!manifest.name.trim() || !manifest.description.trim() || !manifest.author.trim()) throw new Error("Plugin name, description, and author are required"); if (!PLUGIN_CATEGORIES.includes(manifest.category)) throw new Error("Plugin category is invalid"); if (!/^\d+\.\d+\.\d+$/.test(manifest.version)) throw new Error("Plugin version must be semantic"); if (!/^>=\d+\.\d+\.\d+$/.test(manifest.compatiblePlatformVersion)) throw new Error("Plugin platform compatibility is invalid"); if (!manifest.entryPoint.startsWith("trusted:")) throw new Error("Plugin entry point must be a trusted factory"); }
  private isCompatible(plugin: PluginManifest): boolean { const minimum = plugin.compatiblePlatformVersion.slice(2).split(".").map(Number); const current = PLATFORM_VERSION.split(".").map(Number); return current[0] > minimum[0] || (current[0] === minimum[0] && (current[1] > minimum[1] || (current[1] === minimum[1] && current[2] >= minimum[2]))); }
  private validatePermissions(plugin: PluginManifest, grantedPermissions: string[] | undefined): void { const granted = new Set(grantedPermissions ?? []); if (plugin.requiredPermissions.some((permission) => !granted.has(permission))) throw new Error("Required plugin permission was not granted"); }
  private require(pluginId: string): RegisteredPlugin { this.ensureReady(); const plugin = this.plugins.get(pluginId); if (!plugin || plugin.status === "removed") throw new Error(`Plugin not found: ${pluginId}`); return plugin; }
  private ensureReady(): void { if (!this.initialized || !this.tools) throw new Error("Plugin Manager is not initialized"); }
  private async log(event: string, pluginId: string | undefined, detail: string): Promise<void> { const entry = { at: new Date().toISOString(), event, pluginId, detail }; this.logs.unshift(entry); this.logs.splice(100); await fs.appendFile(path.join(this.root, "plugin-events.jsonl"), `${JSON.stringify(entry)}\n`, "utf8"); }
  private async restore(): Promise<void> { try { const values = JSON.parse(await fs.readFile(path.join(this.root, "plugins.json"), "utf8")) as RegisteredPlugin[]; for (const plugin of values) this.plugins.set(plugin.id, plugin); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } }
  private async persist(): Promise<void> { const target = path.join(this.root, "plugins.json"); const temporary = `${target}.${randomUUID()}.tmp`; await fs.writeFile(temporary, `${JSON.stringify(this.list(), null, 2)}\n`, "utf8"); await fs.rename(temporary, target); }
}