import { useEffect, useState } from "react";
import { AudioLines, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, FileText, Filter, Flag, Heart, Image, LayoutGrid, List, Megaphone, Search, Send, Target, Users, Video } from "lucide-react";
import { MarketingCampaignManager } from "./marketing-store";
import type { Campaign, CampaignStatus, MarketingAsset, MarketingAssetKind, MarketingTab, MarketingWorkspaceState } from "./types";
import "./marketing-workspace.css";

const manager = new MarketingCampaignManager();
const tabs: Array<{ id: MarketingTab; label: string; icon: typeof Megaphone }> = [{ id: "dashboard", label: "Campaign dashboard", icon: Megaphone }, { id: "campaigns", label: "Campaign workspace", icon: Target }, { id: "calendar", label: "Content calendar", icon: CalendarDays }, { id: "assets", label: "Marketing assets", icon: Image }, { id: "audiences", label: "Audience manager", icon: Users }, { id: "timeline", label: "Campaign timeline", icon: Clock3 }];
const assetIcons = { image: Image, video: Video, audio: AudioLines, banner: Flag, poster: FileText, product: Image, brand: Megaphone, document: FileText } as const;
const statusOrder: CampaignStatus[] = ["active", "draft", "scheduled", "completed", "archived"];
const date = new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });

export function MarketingWorkspace() {
  const [state, setState] = useState<MarketingWorkspaceState>(() => manager.load());
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<CampaignStatus | "all" | "favorites" | "recent">("all");
  const [assetKind, setAssetKind] = useState<MarketingAssetKind | "all" | "favorites">("all");
  const [selectedAsset, setSelectedAsset] = useState<MarketingAsset | null>(null);
  useEffect(() => { manager.save(state); }, [state]);
  const campaign = state.campaigns.find((item) => item.id === state.activeCampaignId) ?? state.campaigns[0];
  const visibleCampaigns = state.campaigns.filter((item) => (status === "all" || status === "favorites" && state.favorites.includes(item.id) || status === "recent" && state.recent.includes(item.id) || item.status === status) && (!query || `${item.name} ${item.category} ${item.objective} ${item.audience}`.toLowerCase().includes(query.toLowerCase())));
  const visibleAssets = state.assets.filter((asset) => (assetKind === "all" || assetKind === "favorites" && state.favorites.includes(asset.id) || asset.kind === assetKind) && (!query || `${asset.name} ${asset.category} ${asset.kind}`.toLowerCase().includes(query.toLowerCase())));
  return <div className="marketing-workspace"><aside className="marketing-sidebar"><div><span>MARKETING WORKSPACE</span><h2>Campaign planning</h2></div><nav>{tabs.map((tab) => { const Icon = tab.icon; return <button key={tab.id} className={state.tab === tab.id ? "active" : ""} onClick={() => setState((current) => ({ ...current, tab: tab.id }))}><Icon size={15} />{tab.label}</button>; })}</nav><div className="marketing-sync"><CheckCircle2 size={15} /><div><b>Workspace synchronized</b><small>Local planning state active</small></div></div></aside><section className="marketing-main"><header className="marketing-heading"><div><span>MARKETING OPERATIONS</span><h1>{tabs.find((tab) => tab.id === state.tab)?.label}</h1><p>{campaign.name} · {campaign.status} · {date.format(new Date(campaign.updatedAt))}</p></div><div className="campaign-chip"><Flag size={15} /><span>{campaign.priority} priority</span></div></header>{state.tab === "dashboard" && <Dashboard campaigns={state.campaigns} onCampaign={(id) => setState((current) => manager.selectCampaign(current, id))} onTab={(tab) => setState((current) => ({ ...current, tab }))} />}{state.tab === "campaigns" && <Campaigns campaigns={visibleCampaigns} campaign={campaign} query={query} status={status} onQuery={setQuery} onStatus={setStatus} onCampaign={(id) => setState((current) => manager.selectCampaign(current, id))} />}{state.tab === "calendar" && <Calendar campaign={campaign} view={state.calendar} onView={(calendar) => setState((current) => ({ ...current, calendar }))} />}{state.tab === "assets" && <Assets assets={visibleAssets} state={state} query={query} kind={assetKind} selected={selectedAsset} onQuery={setQuery} onKind={setAssetKind} onSelect={setSelectedAsset} onFavorite={(id) => setState((current) => manager.toggleFavorite(current, id))} onView={(assetView) => setState((current) => ({ ...current, assetView }))} />}{state.tab === "audiences" && <Audiences campaign={campaign} state={state} />}{state.tab === "timeline" && <Timeline campaign={campaign} index={state.timelineIndex} onMove={(timelineIndex) => setState((current) => ({ ...current, timelineIndex }))} />}</section></div>;
}
function Dashboard({ campaigns, onCampaign, onTab }: { campaigns: Campaign[]; onCampaign: (id: string) => void; onTab: (tab: MarketingTab) => void }) { return <div className="campaign-dashboard"><section className="campaign-hero"><div><span>CAMPAIGN COMMAND CENTER</span><h2>Organize the story before it goes live.</h2><p>Campaigns, content schedules, assets, and audiences are prepared here for future automation.</p><button onClick={() => onTab("campaigns")}>Open campaign workspace <ChevronRight size={14} /></button></div><Megaphone size={42} /></section><div className="campaign-summary">{statusOrder.map((status) => <article key={status}><b>{campaigns.filter((campaign) => campaign.status === status).length}</b><span>{status} campaigns</span></article>)}</div><div className="marketing-panel-grid"><Panel title="Campaign summary"><div className="campaign-list">{campaigns.map((campaign) => <button key={campaign.id} onClick={() => onCampaign(campaign.id)}><i className={campaign.status} /><div><b>{campaign.name}</b><small>{campaign.category} · {campaign.priority} priority</small></div><ChevronRight size={14} /></button>)}</div></Panel><Panel title="Planning surfaces"><div className="planning-links"><button onClick={() => onTab("calendar")}><CalendarDays size={16} /><span><b>Content calendar</b><small>Daily, weekly, and monthly placeholder views</small></span><ChevronRight size={14} /></button><button onClick={() => onTab("assets")}><Image size={16} /><span><b>Marketing asset library</b><small>Organize campaign creative resources</small></span><ChevronRight size={14} /></button><button onClick={() => onTab("timeline")}><Clock3 size={16} /><span><b>Campaign timeline</b><small>Phases, milestones, and creative tasks</small></span><ChevronRight size={14} /></button></div></Panel></div></div>; }
function Campaigns({ campaigns, campaign, query, status, onQuery, onStatus, onCampaign }: { campaigns: Campaign[]; campaign: Campaign; query: string; status: CampaignStatus | "all" | "favorites" | "recent"; onQuery: (value: string) => void; onStatus: (value: CampaignStatus | "all" | "favorites" | "recent") => void; onCampaign: (id: string) => void }) { return <div className="campaign-workspace"><div className="campaign-controls"><label><Search size={15} /><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search campaigns, objectives, audiences..." /></label><select value={status} onChange={(event) => onStatus(event.target.value as typeof status)}><option value="all">All campaigns</option>{statusOrder.map((item) => <option key={item} value={item}>{item}</option>)}<option value="favorites">Favorites</option><option value="recent">Recent</option></select></div><div className="campaign-work-grid"><section className="campaign-results">{campaigns.map((item) => <button className={item.id === campaign.id ? "active" : ""} key={item.id} onClick={() => onCampaign(item.id)}><i className={item.status} /><div><b>{item.name}</b><small>{item.category} · {item.objective}</small></div><span>{item.priority}</span></button>)}{!campaigns.length && <p>No matching campaigns.</p>}</section><section className="campaign-detail"><header><div><span>CAMPAIGN WORKSPACE</span><h2>{campaign.name}</h2></div><span className={campaign.status}>{campaign.status}</span></header><p>{campaign.description}</p><div className="campaign-fields"><Meta label="Category" value={campaign.category} /><Meta label="Objective" value={campaign.objective} /><Meta label="Audience" value={campaign.audience} /><Meta label="Priority" value={campaign.priority} /><Meta label="Creative assets" value={`${campaign.assets.length} assigned placeholders`} /><Meta label="Campaign notes" value={campaign.notes} /></div><section className="publishing"><header><span>PUBLISHING SCHEDULE</span><h3>Channel placeholders</h3></header>{["Website", "Facebook", "Instagram", "TikTok", "YouTube", "LinkedIn"].map((channel) => <div key={channel}><span>{channel}</span><b>Not scheduled</b><small>Publishing is not enabled</small></div>)}</section></section></div></div>; }
function Calendar({ campaign, view, onView }: { campaign: Campaign; view: MarketingWorkspaceState["calendar"]; onView: (view: MarketingWorkspaceState["calendar"]) => void }) { const cells = Array.from({ length: view === "day" ? 8 : view === "week" ? 7 : 30 }, (_, index) => index + 1); return <div className="calendar-workspace"><div className="calendar-top"><div><span>CONTENT CALENDAR</span><h2>{view === "day" ? "Daily planning" : view === "week" ? "Weekly planning" : "Monthly planning"}</h2></div><div>{(["day", "week", "month"] as const).map((item) => <button key={item} className={view === item ? "active" : ""} onClick={() => onView(item)}>{item}</button>)}</div></div><div className={`calendar-grid ${view}`}>{cells.map((cell) => <article key={cell}><b>{view === "week" ? ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][cell - 1] : cell}</b>{(cell === 2 || cell === 4 || cell === 6) && <span>{cell === 2 ? "Planned content" : cell === 4 ? campaign.name : "Creative review"}</span>}</article>)}</div><div className="calendar-legend"><span><i />Planned content</span><span><i />Scheduled post</span><span><i />Campaign event</span><span><i />Creative task</span></div></div>; }
function Assets({ assets, state, query, kind, selected, onQuery, onKind, onSelect, onFavorite, onView }: { assets: MarketingAsset[]; state: MarketingWorkspaceState; query: string; kind: MarketingAssetKind | "all" | "favorites"; selected: MarketingAsset | null; onQuery: (value: string) => void; onKind: (value: MarketingAssetKind | "all" | "favorites") => void; onSelect: (asset: MarketingAsset) => void; onFavorite: (id: string) => void; onView: (view: MarketingWorkspaceState["assetView"]) => void }) { return <div className="marketing-assets"><div className="asset-controls"><label><Search size={15} /><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search marketing assets..." /></label><select value={kind} onChange={(event) => onKind(event.target.value as typeof kind)}><option value="all">All assets</option><option value="image">Images</option><option value="video">Videos</option><option value="audio">Audio</option><option value="banner">Banners</option><option value="poster">Posters</option><option value="product">Product media</option><option value="brand">Brand assets</option><option value="document">Documents</option><option value="favorites">Favorites</option></select><button className={state.assetView === "grid" ? "active" : ""} onClick={() => onView("grid")}><LayoutGrid size={15} /></button><button className={state.assetView === "list" ? "active" : ""} onClick={() => onView("list")}><List size={15} /></button></div><div className={`marketing-asset-grid ${state.assetView}`}>{assets.map((asset) => <AssetCard key={asset.id} asset={asset} selected={selected?.id === asset.id} onSelect={onSelect} onFavorite={onFavorite} />)}{!assets.length && <p className="asset-empty">No matching marketing resources.</p>}</div>{selected && <aside className="marketing-asset-detail"><button onClick={() => onSelect(selected)}>Selected</button><span>ASSET METADATA</span><h3>{selected.name}</h3><Meta label="Type" value={selected.kind} /><Meta label="Category" value={selected.category} /><Meta label="Version" value={selected.version} /><Meta label="Status" value="Prepared" /><p>{selected.detail}</p></aside>}</div>; }
function AssetCard({ asset, selected, onSelect, onFavorite }: { asset: MarketingAsset; selected: boolean; onSelect: (asset: MarketingAsset) => void; onFavorite: (id: string) => void }) { const Icon = assetIcons[asset.kind]; return <article className={selected ? "selected" : ""} onClick={() => onSelect(asset)}><div className={`marketing-asset-art ${asset.kind}`}><Icon size={27} /><button onClick={(event) => { event.stopPropagation(); onFavorite(asset.id); }}><Heart size={14} fill={asset.favorite ? "currentColor" : "none"} /></button></div><b>{asset.name}</b><small>{asset.category} · {asset.version}</small></article>; }
function Audiences({ campaign, state }: { campaign: Campaign; state: MarketingWorkspaceState }) { return <div className="audience-grid">{state.audiences.map((audience) => <section key={audience.id}><header><Users size={16} /><div><span>AUDIENCE PROFILE</span><h3>{audience.name}</h3></div></header><Meta label="Category" value={audience.category} /><Meta label="Market segment" value={audience.segment} /><Meta label="Region" value={audience.region} /><Meta label="Language" value={audience.language} /><Meta label="Campaign link" value={audience.name === campaign.audience ? campaign.name : "Available for planning"} /><p>{audience.notes}</p></section>)}</div>; }
function Timeline({ campaign, index, onMove }: { campaign: Campaign; index: number; onMove: (index: number) => void }) { const phases = ["Campaign brief", "Audience confirmation", "Creative collection", "Content planning", "Review checkpoint", "Publishing schedule"]; return <div className="timeline-workspace"><header><div><span>CAMPAIGN TIMELINE</span><h2>{campaign.name}</h2></div><div><button onClick={() => onMove(Math.max(0, index - 1))}><ChevronLeft size={15} /></button><button onClick={() => onMove(Math.min(phases.length - 1, index + 1))}><ChevronRight size={15} /></button></div></header><div className="timeline-track">{phases.map((phase, phaseIndex) => <article key={phase} className={phaseIndex === index ? "current" : phaseIndex < index ? "complete" : ""}><i /><span>Phase {phaseIndex + 1}</span><b>{phase}</b><p>{phaseIndex === index ? "Current planning checkpoint" : phaseIndex < index ? "Prepared" : "Future workflow placeholder"}</p></article>)}</div></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="marketing-panel"><header><span>MARKETING RESOURCE</span><h3>{title}</h3></header>{children}</section>; }
function Meta({ label, value }: { label: string; value: string }) { return <div className="marketing-meta"><span>{label}</span><b>{value}</b></div>; }