import type { AiCoreManager } from "../core/ai-core-manager.js";
import type { ToolDefinition, ToolHandler } from "./types.js";

export function createBuiltInTools(core: AiCoreManager): Array<{ definition: ToolDefinition; handler: ToolHandler }> {
  return [
    { definition: { id: "system.runtime-status", name: "Runtime Status", description: "Returns local AI Core readiness and lifecycle state.", category: "system", version: "0.1.0", author: "KWIZERA AI", inputSchema: { type: "object" }, outputSchema: { type: "object" }, requiredPermissions: ["system.read"], dependencies: ["ai-core"], supportedModels: [], executionType: "synchronous", locality: "local" }, handler: async () => ({ ready: core.isReady(), lifecycle: String(core.getLifecycleState()) }) },
    { definition: { id: "workflow.status", name: "Workflow Status", description: "Returns workflow engine availability without running a workflow.", category: "utility", version: "0.1.0", author: "KWIZERA AI", inputSchema: { type: "object" }, outputSchema: { type: "object" }, requiredPermissions: ["workflow.read"], dependencies: ["workflow-engine"], supportedModels: [], executionType: "synchronous", locality: "local" }, handler: async () => ({ initialized: core.workflowEngine?.isInitialized() ?? false }) },
    { definition: { id: "tool.registry-summary", name: "Tool Registry Summary", description: "Returns the registered tool count by category.", category: "utility", version: "0.1.0", author: "KWIZERA AI", inputSchema: { type: "object" }, outputSchema: { type: "object" }, requiredPermissions: ["tools.read"], dependencies: ["ai-core"], supportedModels: [], executionType: "synchronous", locality: "local" }, handler: async () => ({ total: core.toolManager?.list().length ?? 0 }) },
    { definition: { id: "connector.registry-summary", name: "Connector Registry Summary", description: "Returns connector count and integration availability without making a remote request.", category: "external", version: "0.1.0", author: "KWIZERA AI", inputSchema: { type: "object" }, outputSchema: { type: "object" }, requiredPermissions: ["connectors.read"], dependencies: ["ai-core"], supportedModels: [], executionType: "synchronous", locality: "local" }, handler: async () => ({ total: core.connectorManager?.list().length ?? 0, initialized: core.connectorManager?.isInitialized() ?? false }) },
    { definition: { id: "desktop.integration-status", name: "Desktop Integration Status", description: "Returns local integration status without accessing project files or system resources.", category: "system", version: "0.1.0", author: "KWIZERA AI", inputSchema: { type: "object" }, outputSchema: { type: "object" }, requiredPermissions: ["system.read"], dependencies: ["ai-core"], supportedModels: [], executionType: "synchronous", locality: "local" }, handler: async () => core.desktopIntegrationManager?.getStatus() ?? { initialized: false } },
  ];
}