import { useEffect, useState } from "react";
import { Blocks, Bot, Braces, CheckCircle2, ChevronRight, Code2, Database, FileCog, Gauge, GitBranch, HardDrive, KeyRound, LayoutDashboard, ListTree, Network, Package, Plug, Puzzle, RefreshCw, Search, ServerCog, Settings2, ShieldCheck, TerminalSquare, Wrench, X } from "lucide-react";
import { extensions, integrations, modules, PlatformConfigurationManager, plugins, services } from "./platform-store";
import type { Integration, LocalService, ModuleRecord, PlatformCore, PlatformItem, PlatformLayout, PlatformStatus, PlatformTab } from "./types";
import "./platform-management.css";

const manager = new PlatformConfigurationManager();
const tabs: Array<{ id: PlatformTab; label: string; icon: typeof Blocks }> = [{ id: "dashboard", label: "Platform dashboard", icon: LayoutDashboard }, { id: "plugins", label: "Plugin manager", icon: Puzzle }, { id: "extensions", label: "Extension manager", icon: Blocks }, { id: "modules", label: "Module registry", icon: ListTree }, { id: "integrations", label: "API integration center", icon: Plug }, { id: "services", label: "Local services", icon: ServerCog }, { id: "developer", label: "Developer workspace", icon: TerminalSquare }, { id: "configuration", label: "Platform configuration", icon: Settings2 }];
const statusLabel = (status: PlatformStatus) => status === "development" ? "development" : status;
async function readStatus(): Promise<PlatformCore | null> { try { const response = await fetch("/api/desktop-workspace/status"); return response.ok ? await response.json() as PlatformCore : null; } catch { return null; } }
function match(query: string, values: string[]) { return !query || values.join(" ").toLowerCase().includes(query.toLowerCase()); }

export function PlatformManagementWorkspace() {
  const [layout, setLayout] = useState<PlatformLayout>(() => manager.load());
  const [core, setCore] = useState<PlatformCore | null>(null);
  const refresh = async () => setCore(await readStatus());
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 15_000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { manager.save(layout); }, [layout]);
  const select = (id: string) => setLayout((current) => manager.select(current, id));
  return <div className="platform-management"><aside className="platform-nav"><div><span>KWIZERA PLATFORM</span><h2>Extension control</h2></div><nav>{tabs.map((tab) => { const Icon = tab.icon; return <button key={tab.id} className={layout.tab === tab.id ? "active" : ""} onClick={() => setLayout((current) => ({ ...current, tab: tab.id }))}><Icon size={15} />{tab.label}</button>; })}</nav><div className="platform-nav-status"><i className={core?.moduleManager ? "ready" : ""} /><span><b>{core?.moduleManager ? "Registry available" : "Registry standby"}</b><small>Read-only runtime sample</small></span></div></aside><section className="platform-main"><header className="platform-heading"><div><span>EXTENSIBILITY FOUNDATION</span><h1>{tabs.find((tab) => tab.id === layout.tab)?.label}</h1><p>{core?.activeProject ?? "No active project"} · local configuration and management only</p></div><div><button onClick={() => void refresh()}><RefreshCw size={15} />Refresh</button><button title="Configuration" onClick={() => setLayout((current) => ({ ...current, tab: "configuration" }))}><Settings2 size={15} /></button></div></header>{layout.tab === "dashboard" && <Dashboard core={core} onTab={(tab) => setLayout((current) => ({ ...current, tab }))} />}{layout.tab === "plugins" && <ItemsWorkspace title="Plugin manager" subtitle="Installed plugins and marketplace-ready package records" items={plugins} layout={layout} onLayout={setLayout} onSelect={select} kind="plugins" />}{layout.tab === "extensions" && <ItemsWorkspace title="Extension manager" subtitle="Installed, available, disabled, and development extension records" items={extensions} layout={layout} onLayout={setLayout} onSelect={select} kind="extensions" />}{layout.tab === "modules" && <Registry layout={layout} onLayout={setLayout} onSelect={select} />}{layout.tab === "integrations" && <IntegrationCenter layout={layout} onSelect={select} />}{layout.tab === "services" && <ServiceCenter layout={layout} onSelect={select} />}{layout.tab === "developer" && <Developer core={core} layout={layout} />}{layout.tab === "configuration" && <Configuration layout={layout} onLayout={setLayout} />}</section></div>;
}
function Dashboard({ core, onTab }: { core: PlatformCore | null; onTab: (tab: PlatformTab) => void }) { const activeModules = [core?.aiCore, core?.workflowEngine, core?.communicationBus, core?.moduleManager, core?.memoryFoundation, core?.knowledgeFoundation, core?.automationEngine].filter(Boolean).length; return <div className="platform-dashboard"><section className="platform-hero"><div><span>PLATFORM CONTROL PLANE</span><h2>Expand the studio without disturbing its core.</h2><p>Local registries, extension contracts, and connector configurations are ready for future approved services. No download, connection, or cloud synchronization runs here.</p><button onClick={() => onTab("plugins")}>Open plugin manager <ChevronRight size={14} /></button></div><Blocks size={47} /></section><div className="platform-stats"><Stat icon={<Puzzle />} value={plugins.filter((item) => item.status === "active").length} label="Installed plugins" /><Stat icon={<Blocks />} value={extensions.filter((item) => item.status === "active").length} label="Installed extensions" /><Stat icon={<ListTree />} value={activeModules} label="Active modules" /><Stat icon={<Plug />} value={integrations.filter((item) => item.status !== "disabled").length} label="Available integrations" /></div><div className="platform-panels"><Panel title="Platform health" icon={<ShieldCheck size={15} />}><Status label="AI Core" ready={core?.aiCore} /><Status label="Workflow Engine" ready={core?.workflowEngine} /><Status label="Communication Bus" ready={core?.communicationBus} /><Status label="Module Manager" ready={core?.moduleManager} /><Status label="Memory Foundation" ready={core?.memoryFoundation} /><Status label="Knowledge Foundation" ready={core?.knowledgeFoundation} /></Panel><Panel title="Extension status" icon={<Gauge size={15} />}>{["active", "available", "disabled", "development"].map((status) => <div className="platform-status" key={status}><span><i className={status} />{status}</span><b>{extensions.filter((item) => item.status === status).length}</b></div>)}</Panel><Panel title="Expansion surfaces" icon={<GitBranch size={15} />}><button className="platform-link" onClick={() => onTab("integrations")}><Plug size={15} /><span><b>API integration center</b><small>Local, internal, REST, GraphQL, and provider contracts</small></span><ChevronRight size={14} /></button><button className="platform-link" onClick={() => onTab("services")}><ServerCog size={15} /><span><b>Local services center</b><small>Models, databases, rendering, files, and background services</small></span><ChevronRight size={14} /></button><button className="platform-link" onClick={() => onTab("developer")}><TerminalSquare size={15} /><span><b>Developer workspace</b><small>Diagnostics, logs, registry, and status tools</small></span><ChevronRight size={14} /></button></Panel></div></div>; }
function ItemsWorkspace({ title, subtitle, items, layout, onLayout, onSelect, kind }: { title: string; subtitle: string; items: PlatformItem[]; layout: PlatformLayout; onLayout: (layout: PlatformLayout) => void; onSelect: (id: string) => void; kind: string }) { const visible = items.filter((item) => (layout.pluginCategory === "all" || item.category === layout.pluginCategory) && (kind !== "extensions" || layout.extensionFilter === "all" || item.status === layout.extensionFilter) && match(layout.query, [item.name, item.category, item.status, item.detail])); const selected = items.find((item) => item.id === layout.selectedId); return <div className="registry-workspace"><div className="registry-controls"><label><Search size={15} /><input value={layout.query} onChange={(event) => onLayout({ ...layout, query: event.target.value })} placeholder={`Search ${kind}, categories, status...`} /></label><select value={layout.pluginCategory} onChange={(event) => onLayout({ ...layout, pluginCategory: event.target.value as PlatformLayout["pluginCategory"] })}><option value="all">All categories</option>{["AI", "Creative", "Business", "Developer", "System"].map((item) => <option key={item}>{item}</option>)}</select>{kind === "extensions" && <select value={layout.extensionFilter} onChange={(event) => onLayout({ ...layout, extensionFilter: event.target.value as PlatformLayout["extensionFilter"] })}><option value="all">All states</option>{["active", "available", "disabled", "development"].map((item) => <option key={item}>{item}</option>)}</select>}</div><div className="registry-heading"><div><span>{kind.toUpperCase()} REGISTRY</span><h2>{title}</h2><p>{subtitle}</p></div><b>{visible.length} records</b></div><div className={`platform-item-grid ${layout.compact ? "compact" : ""}`}>{visible.map((item) => <ItemCard key={item.id} item={item} selected={item.id === layout.selectedId} onSelect={() => onSelect(item.id)} />)}{!visible.length && <p className="platform-empty">No matching {kind} in the local registry.</p>}</div>{selected && <ItemDetail item={selected} onClose={() => onLayout({ ...layout, selectedId: null })} />}</div>; }
function Registry({ layout, onLayout, onSelect }: { layout: PlatformLayout; onLayout: (layout: PlatformLayout) => void; onSelect: (id: string) => void }) { const visible = modules.filter((item) => match(layout.query, [item.name, item.domain, item.status, item.detail])); return <div className="module-registry"><div className="registry-controls"><label><Search size={15} /><input value={layout.query} onChange={(event) => onLayout({ ...layout, query: event.target.value })} placeholder="Search modules, domains, status..." /></label></div><header><div><span>MODULE DISCOVERY ENGINE</span><h2>Registered platform modules</h2><p>Discovery records are presentation-only and do not register or initialize runtime modules.</p></div><b>{visible.length} discovered</b></header>{visible.map((module) => <button key={module.id} onClick={() => onSelect(module.id)}><span className="module-icon"><Package size={16} /></span><span><b>{module.name}</b><small>{module.domain} · {module.detail}</small></span><em className={module.status}>{statusLabel(module.status)}</em><ChevronRight size={14} /></button>)}</div>; }
function IntegrationCenter({ layout, onSelect }: { layout: PlatformLayout; onSelect: (id: string) => void }) { const visible = integrations.filter((item) => match(layout.query, [item.name, item.kind, item.status, item.detail])); return <Center title="API Integration Center" eyebrow="INTEGRATION CONFIGURATION" description="No external API requests or connectors are configured or invoked." records={visible} icon={<Plug size={20} />} onSelect={onSelect} />; }
function ServiceCenter({ layout, onSelect }: { layout: PlatformLayout; onSelect: (id: string) => void }) { const visible = services.filter((item) => match(layout.query, [item.name, item.kind, item.status, item.detail])); return <Center title="Local Services Center" eyebrow="SERVICE MANAGEMENT" description="This is a local service catalog; it starts no service and changes no runtime process." records={visible} icon={<ServerCog size={20} />} onSelect={onSelect} />; }
function Center({ title, eyebrow, description, records, icon, onSelect }: { title: string; eyebrow: string; description: string; records: Array<Integration | LocalService>; icon: React.ReactNode; onSelect: (id: string) => void }) { return <div className="platform-center"><header><span>{icon}</span><div><small>{eyebrow}</small><h2>{title}</h2><p>{description}</p></div></header><div>{records.map((item) => <button key={item.id} onClick={() => onSelect(item.id)}><span><b>{item.name}</b><small>{item.kind} · {item.detail}</small></span><em className={item.status}>{statusLabel(item.status)}</em><ChevronRight size={14} /></button>)}</div></div>; }
function Developer({ core, layout }: { core: PlatformCore | null; layout: PlatformLayout }) { return <div className="developer-workspace"><section className="developer-console"><header><div><Code2 size={16} /><span>DEBUG CONSOLE</span></div><em>Read-only</em></header>{layout.logs.map((line, index) => <p key={`${line}-${index}`}><small>{String(index + 1).padStart(2, "0")}</small>{line}</p>)}</section><div className="developer-grid"><Panel title="System diagnostics" icon={<Wrench size={15} />}><Status label="Module discovery" ready={core?.moduleManager} /><Status label="Integration status" ready={core?.communicationBus} /><Status label="Workflow context" ready={core?.workflowEngine} /><Status label="Automation foundation" ready={core?.automationEngine} /></Panel><Panel title="Development tools" icon={<Braces size={15} />}><Tool icon={<ListTree size={15} />} label="Module registry" detail="Prepared registry records" /><Tool icon={<FileCog size={15} />} label="Extension logs" detail="Local UI log history" /><Tool icon={<Network size={15} />} label="Integration status" detail="Read-only readiness sample" /><Tool icon={<KeyRound size={15} />} label="Permission manager" detail="Declared local permissions" /></Panel></div></div>; }
function Configuration({ layout, onLayout }: { layout: PlatformLayout; onLayout: (layout: PlatformLayout) => void }) { const rows = [["discovery", "Module discovery", "Maintain local discovery records for future registered modules."], ["diagnostics", "Developer diagnostics", "Show read-only runtime readiness in the developer workspace."], ["enterprise", "Enterprise module support", "Reserve enterprise extension slots; licensing is not implemented."], ["cloudSync", "Future cloud synchronization", "Configuration placeholder only. Synchronization remains disabled."], ["marketplace", "Plugin marketplace foundation", "Catalog foundation only. No online marketplace or downloads."]]; return <div className="configuration-workspace"><header><Settings2 size={25} /><div><span>PLATFORM CONFIGURATION MANAGER</span><h2>Extension policies</h2><p>Local preferences persist in this browser and never initiate services or connections.</p></div></header>{rows.map(([id, title, detail]) => <label key={id}><span><b>{title}</b><small>{detail}</small></span><input type="checkbox" checked={Boolean(layout.configurations[id])} onChange={() => onLayout(manager.toggleConfiguration(layout, id))} /></label>)}</div>; }
function Stat({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <article><span>{icon}</span><b>{value}</b><small>{label}</small></article>; }
function Status({ label, ready }: { label: string; ready?: boolean }) { return <div className="platform-status"><span><i className={ready ? "active" : "standby"} />{label}</span><b>{ready ? "Ready" : "Standby"}</b></div>; }
function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="platform-panel"><header>{icon}<div><span>PLATFORM STATUS</span><h3>{title}</h3></div></header>{children}</section>; }
function Tool({ icon, label, detail }: { icon: React.ReactNode; label: string; detail: string }) { return <div className="developer-tool"><span>{icon}</span><div><b>{label}</b><small>{detail}</small></div></div>; }
function ItemCard({ item, selected, onSelect }: { item: PlatformItem; selected: boolean; onSelect: () => void }) { return <article className={selected ? "selected" : ""} onClick={onSelect}><div><span className="package-mark"><Package size={18} /></span><em className={item.status}>{statusLabel(item.status)}</em></div><b>{item.name}</b><small>{item.category} · v{item.version}</small><p>{item.detail}</p></article>; }
function ItemDetail({ item, onClose }: { item: PlatformItem; onClose: () => void }) { return <aside className="platform-detail"><header><div><span>PACKAGE DETAILS</span><h3>{item.name}</h3></div><button onClick={onClose}><X size={15} /></button></header><p>{item.detail}</p><Detail label="Category" value={item.category} /><Detail label="Version" value={item.version} /><Detail label="Status" value={statusLabel(item.status)} /><section><span>DECLARED PERMISSIONS</span>{item.permissions.map((permission) => <b key={permission}>{permission}</b>)}</section><small>Management only. Permission grants are not applied to runtime services.</small></aside>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="platform-detail-row"><span>{label}</span><b>{value}</b></div>; }