import type { Integration, LocalService, ModuleRecord, PlatformItem, PlatformLayout } from "./types";

const KEY = "kwizera.platform-management.v1";
const now = new Date().toISOString();
const item = (id: string, name: string, category: PlatformItem["category"], version: string, status: PlatformItem["status"], detail: string, permissions: string[]): PlatformItem => ({ id, name, category, version, status, detail, permissions, updatedAt: now });
export const plugins = [item("core-bridge", "Core runtime bridge", "System", "1.0.0", "active", "Read-only foundation for future platform adapters.", ["Runtime status", "Module presence"]), item("creative-tools", "Creative workspace tools", "Creative", "0.4.0", "active", "Prepared extension point for editor workspace tools.", ["Project context", "Asset metadata"]), item("insight-panel", "Business insight panel", "Business", "0.2.0", "available", "Marketplace-ready business analytics presentation package.", ["Workspace context"]), item("developer-kit", "Developer diagnostics kit", "Developer", "0.1.0", "development", "Local diagnostics and developer workspace foundation.", ["Diagnostic status"]), item("ai-provider-adapter", "AI provider adapter", "AI", "0.1.0", "disabled", "Reserved adapter contract. No provider connection exists.", ["None granted"])];
export const extensions = [item("brand-surface", "Brand Center surface", "Business", "1.0.0", "active", "Desktop navigation and brand resource integration foundation.", ["Local brand state"]), item("marketing-surface", "Marketing planning surface", "Business", "1.0.0", "active", "Campaign planning workspace integration foundation.", ["Local campaign state"]), item("intelligence-surface", "Business Intelligence surface", "Business", "1.0.0", "active", "Read-only project and runtime presentation surface.", ["Runtime status", "Project context"]), item("enterprise-shell", "Enterprise workspace shell", "System", "0.1.0", "available", "Prepared enterprise module slot without licensing or authentication.", ["None granted"]), item("local-dev-extension", "Local development extension", "Developer", "0.1.0", "development", "Developer extension lifecycle workspace placeholder.", ["Diagnostic status"]), item("connector-workbench", "Connector workbench", "Developer", "0.1.0", "disabled", "External connector management interface foundation.", ["None granted"])];
export const modules: ModuleRecord[] = [
  { id: "desktop", name: "Desktop Workspace Foundation", domain: "Workspace", status: "active", detail: "Global shell, navigation, preferences, and layout persistence." }, { id: "projects", name: "Project Workspace", domain: "Creative operations", status: "active", detail: "Project and asset organization context." }, { id: "ai-studio", name: "AI Studio Workspace", domain: "AI collaboration", status: "active", detail: "Local collaboration session surface." }, { id: "creative-editor", name: "Creative Editing Workspace", domain: "Creative operations", status: "active", detail: "Professional creative editor interface foundation." }, { id: "business-dashboard", name: "Business Dashboard", domain: "Business", status: "active", detail: "Business overview presentation workspace." }, { id: "brand", name: "Brand Center", domain: "Business", status: "active", detail: "Brand identity and asset management surface." }, { id: "marketing", name: "Marketing Campaign Manager", domain: "Business", status: "active", detail: "Campaign planning and content workspace." }, { id: "intelligence", name: "Business Intelligence Center", domain: "Business", status: "active", detail: "Read-only executive analytics presentation." }, { id: "ai-core", name: "AI Core", domain: "Runtime", status: "active", detail: "Runtime readiness is sampled through the existing status endpoint." }, { id: "workflow", name: "Workflow Engine", domain: "Runtime", status: "active", detail: "Workflow readiness is sampled without workflow execution." }, { id: "communication", name: "Communication Bus", domain: "Runtime", status: "active", detail: "Communication readiness is presented read-only." }, { id: "memory", name: "Memory Foundation", domain: "Runtime", status: "active", detail: "Memory foundation readiness is sampled read-only." }, { id: "knowledge", name: "Knowledge Foundation", domain: "Runtime", status: "active", detail: "Knowledge foundation readiness is sampled read-only." }, { id: "automation", name: "Automation Engine", domain: "Runtime", status: "standby", detail: "Runtime capability is represented without automation execution." },
];
export const integrations: Integration[] = [
  { id: "local-api", name: "Local API gateway", kind: "Local API", status: "available", detail: "Reserved local service adapter configuration." }, { id: "internal-api", name: "Internal module API", kind: "Internal API", status: "active", detail: "Foundation for platform module contracts." }, { id: "rest", name: "Future REST API", kind: "REST API", status: "standby", detail: "No external request configuration is active." }, { id: "graphql", name: "Future GraphQL API", kind: "GraphQL API", status: "standby", detail: "Schema and connection configuration are not implemented." }, { id: "provider", name: "Future AI providers", kind: "AI Provider", status: "disabled", detail: "Provider adapters are intentionally not connected." }, { id: "connector", name: "External connector framework", kind: "External Connector", status: "available", detail: "Connector catalog and configuration foundation only." },
];
export const services: LocalService[] = [
  { id: "models", name: "Local AI models", kind: "AI model", status: "available", detail: "Future local model discovery and lifecycle management." }, { id: "database", name: "Local database service", kind: "Database", status: "standby", detail: "Reserved service registration surface." }, { id: "rendering", name: "Local rendering service", kind: "Rendering", status: "standby", detail: "Future renderer handoff and health interface." }, { id: "files", name: "Local file service", kind: "File service", status: "active", detail: "Workspace asset context is locally available." }, { id: "background", name: "Background services", kind: "Background service", status: "available", detail: "Prepared task and service manager surface." },
];
const fallback: PlatformLayout = { tab: "dashboard", query: "", pluginCategory: "all", extensionFilter: "all", selectedId: null, compact: false, configurations: { discovery: true, diagnostics: true, enterprise: false, cloudSync: false, marketplace: false }, logs: ["Platform workspace initialized", "Module discovery registry prepared", "External connectivity disabled by platform policy"] };
export class PlatformConfigurationManager {
  load(): PlatformLayout { try { return { ...fallback, ...JSON.parse(localStorage.getItem(KEY) ?? "{}") }; } catch { return fallback; } }
  save(layout: PlatformLayout): void { localStorage.setItem(KEY, JSON.stringify(layout)); }
  toggleConfiguration(layout: PlatformLayout, id: string): PlatformLayout { return { ...layout, configurations: { ...layout.configurations, [id]: !layout.configurations[id] } }; }
  select(layout: PlatformLayout, id: string): PlatformLayout { return { ...layout, selectedId: id, logs: [`Selected registry item: ${id}`, ...layout.logs].slice(0, 18) }; }
}
export class PluginManager {}
export class ExtensionManager {}
export class ModuleRegistry {}
export class ModuleDiscoveryEngine {}
export class ApiIntegrationManager {}
export class LocalServiceManager {}
export class ExternalConnectorManager {}
export class IntegrationConfigurationManager {}
export class PluginMarketplaceFoundation {}
export class DeveloperToolsWorkspace {}
export class SystemExtensionManager {}
export class IntegrationStatusManager {}
export class PluginAnalyticsManager {}
export class ExtensionPermissionManager {}
export class PlatformWorkspaceSynchronization {}