import { useEffect, useState } from "react";
import { Activity, Bot, BrainCircuit, CheckCircle2, ChevronRight, Cpu, FileBarChart, FolderKanban, Gauge, Heart, Image, Lightbulb, ListFilter, MoreHorizontal, Network, RefreshCw, Search, SlidersHorizontal, Sparkles, Video, X } from "lucide-react";
import { BusinessIntelligenceManager, reports } from "./intelligence-store";
import type { IntelligenceCore, IntelligenceLayout, IntelligenceProject, IntelligenceTab, IntelligenceWidgetId, IntelligenceWorkspace, ReportCategory, ReportRecord } from "./types";
import "./business-intelligence.css";

const manager = new BusinessIntelligenceManager();
const tabs: Array<{ id: IntelligenceTab; label: string; icon: typeof BrainCircuit }> = [{ id: "executive", label: "Executive dashboard", icon: BrainCircuit }, { id: "analytics", label: "Analytics dashboard", icon: Gauge }, { id: "reports", label: "Reports center", icon: FileBarChart }, { id: "recommendations", label: "AI recommendations", icon: Lightbulb }, { id: "timeline", label: "Analytics timeline", icon: Activity }, { id: "resources", label: "Resource dashboard", icon: Cpu }];
const widgets: Array<{ id: IntelligenceWidgetId; label: string }> = [{ id: "business", label: "Business status" }, { id: "ai", label: "AI activity" }, { id: "projects", label: "Project summary" }, { id: "marketing", label: "Marketing summary" }, { id: "productivity", label: "Productivity" }, { id: "system", label: "System overview" }, { id: "kpis", label: "Analytics KPIs" }, { id: "resources", label: "Resources" }];
async function read<T>(path: string): Promise<T | null> { try { const response = await fetch(path); return response.ok ? await response.json() as T : null; } catch { return null; } }
function bytes(value: number) { return value ? `${(value / 1024 / 1024).toFixed(1)} MB` : "--"; }

export function BusinessIntelligenceWorkspace() {
  const [layout, setLayout] = useState<IntelligenceLayout>(() => manager.load());
  const [core, setCore] = useState<IntelligenceCore | null>(null);
  const [workspace, setWorkspace] = useState<IntelligenceWorkspace | null>(null);
  const [query, setQuery] = useState("");
  const [customize, setCustomize] = useState(false);
  const refresh = async () => { const [nextCore, nextWorkspace] = await Promise.all([read<IntelligenceCore>("/api/desktop-workspace/status"), read<IntelligenceWorkspace>("/api/workspace")]); setCore(nextCore); setWorkspace(nextWorkspace); };
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 15_000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { manager.save(layout); }, [layout]);
  const projects = workspace?.projects ?? [];
  const storage = projects.reduce((sum, project) => sum + project.productImages.reduce((total, image) => total + image.sizeBytes, 0), 0);
  const hidden = (id: IntelligenceWidgetId) => layout.hidden.includes(id);
  const compact = (id: IntelligenceWidgetId) => layout.compact.includes(id);
  return <div className="intelligence-workspace"><aside className="intelligence-sidebar"><div><span>BUSINESS INTELLIGENCE</span><h2>Executive insights</h2></div><nav>{tabs.map((tab) => { const Icon = tab.icon; return <button key={tab.id} className={layout.tab === tab.id ? "active" : ""} onClick={() => setLayout((current) => ({ ...current, tab: tab.id }))}><Icon size={15} />{tab.label}</button>; })}</nav><div className="intelligence-sync"><CheckCircle2 size={15} /><div><b>Read-only synchronization</b><small>Project and runtime context sampled</small></div></div></aside><section className="intelligence-main"><header className="intelligence-heading"><div><span>ANALYTICS PLATFORM</span><h1>{tabs.find((tab) => tab.id === layout.tab)?.label}</h1><p>{workspace?.activeProject?.name ?? core?.activeProject ?? "No active project"} · live-ready interface foundation</p></div><div><button onClick={() => void refresh()}><RefreshCw size={15} />Refresh</button><button onClick={() => setCustomize(!customize)} title="Customize dashboard"><SlidersHorizontal size={15} /></button></div></header>{layout.tab === "executive" && <Executive core={core} projects={projects} storage={storage} hidden={hidden} compact={compact} onToggle={(id) => setLayout(manager.toggleDensity(layout, id))} />}{layout.tab === "analytics" && <Analytics projects={projects} storage={storage} core={core} hidden={hidden} compact={compact} onToggle={(id) => setLayout(manager.toggleDensity(layout, id))} />}{layout.tab === "reports" && <Reports layout={layout} query={query} onQuery={setQuery} onLayout={setLayout} />}{layout.tab === "recommendations" && <Recommendations core={core} />}{layout.tab === "timeline" && <Timeline layout={layout} onLayout={setLayout} projects={projects} />}{layout.tab === "resources" && <Resources core={core} storage={storage} />}{customize && <Customize layout={layout} onLayout={setLayout} onClose={() => setCustomize(false)} />}</section></div>;
}
function Executive({ core, projects, storage, hidden, compact, onToggle }: { core: IntelligenceCore | null; projects: IntelligenceProject[]; storage: number; hidden: (id: IntelligenceWidgetId) => boolean; compact: (id: IntelligenceWidgetId) => boolean; onToggle: (id: IntelligenceWidgetId) => void }) { return <div className="executive-dashboard"><section className="executive-hero"><div><span>EXECUTIVE OVERVIEW</span><h2>Clarity for the business behind the studio.</h2><p>Every indicator is ready for future live-data adapters. Values without a valid source are shown as placeholders.</p></div><BrainCircuit size={44} /></section><div className="executive-grid">{!hidden("business") && <Insight id="business" title="Overall business status" compact={compact("business")} onToggle={onToggle}><Status label="Business workspace" value="Prepared" good /><Status label="Project organization" value={`${projects.length} indexed`} good /><Status label="Creative activity" value="Not sampled" /></Insight>}{!hidden("ai") && <Insight id="ai" title="AI activity summary" compact={compact("ai")} onToggle={onToggle}><Status label="AI Core" value={core?.aiCore ? "Ready" : "Offline"} good={core?.aiCore} /><Status label="Workflow engine" value={core?.workflowEngine ? "Connected" : "Standby"} good={core?.workflowEngine} /><Status label="Automation" value={core?.automationEngine ? "Available" : "Not sampled"} good={core?.automationEngine} /></Insight>}{!hidden("projects") && <Insight id="projects" title="Project summary" compact={compact("projects")} onToggle={onToggle}><Metric icon={<FolderKanban />} value={projects.length} label="Active projects" /><Metric icon={<CheckCircle2 />} value="--" label="Completed projects" /><Metric icon={<Image />} value={projects.reduce((sum, project) => sum + project.productImages.length, 0)} label="Source assets" /></Insight>}{!hidden("marketing") && <Insight id="marketing" title="Marketing summary" compact={compact("marketing")} onToggle={onToggle}><Metric icon={<Gauge />} value="--" label="Marketing campaigns" /><Metric icon={<FileBarChart />} value="--" label="Published content" /><Metric icon={<Heart />} value="--" label="Engagement analytics" /></Insight>}{!hidden("productivity") && <Insight id="productivity" title="Productivity summary" compact={compact("productivity")} onToggle={onToggle}><Status label="AI tasks" value="Not sampled" /><Status label="Creative tasks" value="Prepared" good /><Status label="Workflow milestones" value="Future adapter" /></Insight>}{!hidden("system") && <Insight id="system" title="System overview" compact={compact("system")} onToggle={onToggle}><Status label="Memory foundation" value={core?.memoryFoundation ? "Connected" : "Standby"} good={core?.memoryFoundation} /><Status label="Knowledge foundation" value={core?.knowledgeFoundation ? "Connected" : "Standby"} good={core?.knowledgeFoundation} /><Status label="Storage usage" value={bytes(storage)} /></Insight>}</div></div>; }
function Analytics({ projects, storage, core, hidden, compact, onToggle }: { projects: IntelligenceProject[]; storage: number; core: IntelligenceCore | null; hidden: (id: IntelligenceWidgetId) => boolean; compact: (id: IntelligenceWidgetId) => boolean; onToggle: (id: IntelligenceWidgetId) => void }) { const assets = projects.reduce((sum, project) => sum + project.productImages.length, 0); return <div className="analytics-dashboard">{!hidden("kpis") && <Insight id="kpis" title="Analytics widgets" compact={compact("kpis")} onToggle={onToggle}><div className="analytics-kpis"><Metric icon={<FolderKanban />} value={projects.length} label="Active projects" /><Metric icon={<CheckCircle2 />} value="--" label="Completed projects" /><Metric icon={<Image />} value="--" label="Generated images" /><Metric icon={<Video />} value="--" label="Generated videos" /><Metric icon={<Bot />} value="--" label="AI tasks" /><Metric icon={<Gauge />} value="--" label="Marketing campaigns" /><Metric icon={<Sparkles />} value={assets} label="Creative assets" /><Metric icon={<Cpu />} value={bytes(storage)} label="Storage usage" /></div></Insight>}{!hidden("resources") && <Insight id="resources" title="Resource analytics" compact={compact("resources")} onToggle={onToggle}><div className="resource-bars"><Resource label="CPU usage" value="Not sampled" /><Resource label="GPU usage" value="Not sampled" /><Resource label="RAM usage" value="Not sampled" /><Resource label="AI engine" value={core?.aiCore ? "Ready" : "Offline"} ready={core?.aiCore} /><Resource label="Workflow queue" value={core?.workflowEngine ? "Ready" : "Standby"} ready={core?.workflowEngine} /><Resource label="Automation" value={core?.automationEngine ? "Connected" : "Not sampled"} ready={core?.automationEngine} /></div></Insight>}</div>; }
function Reports({ layout, query, onQuery, onLayout }: { layout: IntelligenceLayout; query: string; onQuery: (value: string) => void; onLayout: (layout: IntelligenceLayout) => void }) { const visible = reports.filter((report) => (layout.reportCategory === "all" || report.category === layout.reportCategory) && (!query || `${report.title} ${report.category} ${report.detail}`.toLowerCase().includes(query.toLowerCase()))); return <div className="reports-center"><div className="report-controls"><label><Search size={15} /><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search reports, categories, status..." /></label><select value={layout.reportCategory} onChange={(event) => onLayout({ ...layout, reportCategory: event.target.value as IntelligenceLayout["reportCategory"] })}><option value="all">All report categories</option>{(["project", "marketing", "ai", "productivity", "performance", "resource", "export"] as ReportCategory[]).map((category) => <option key={category} value={category}>{category} reports</option>)}</select></div><div className="report-grid">{visible.map((report) => <Report key={report.id} report={report} favorite={layout.favorites.includes(report.id)} onFavorite={() => onLayout(manager.toggleFavorite(layout, report.id))} onSelect={() => onLayout(manager.selectReport(layout, report.id))} />)}{!visible.length && <p className="intelligence-empty">No reports match this search.</p>}</div><section className="recent-reports"><span>RECENT REPORTS</span>{layout.recent.length ? layout.recent.map((id) => <b key={id}>{reports.find((report) => report.id === id)?.title}</b>) : <p>Select a report to add it to local history.</p>}</section></div>; }
function Recommendations({ core }: { core: IntelligenceCore | null }) { const items = [["Workflow improvements", core?.workflowEngine ? "Workflow readiness is visible; add future task telemetry for operational detail." : "Connect local workflow readiness before surfacing process metrics."], ["Creative improvements", "Attach approved creative-review events to populate performance trends."], ["Marketing improvements", "Connect campaign planning status when publishing automation is intentionally introduced."], ["Performance improvements", "Use future runtime samples for CPU, GPU, and memory trend reporting."], ["Resource optimization", "Resource optimization will be based on live monitoring, not placeholder values."], ["Productivity optimization", "Track completed workspace milestones when task instrumentation becomes available."]]; return <div className="recommendation-grid">{items.map(([title, detail]) => <article key={title}><span><Lightbulb size={17} /></span><div><b>{title}</b><p>{detail}</p></div><ChevronRight size={14} /></article>)}</div>; }
function Timeline({ layout, onLayout, projects }: { layout: IntelligenceLayout; onLayout: (layout: IntelligenceLayout) => void; projects: IntelligenceProject[] }) { const period = layout.timeline === "daily" ? 8 : layout.timeline === "weekly" ? 7 : 12; return <div className="analytics-timeline"><header><div><span>ACTIVITY VISUALIZATION</span><h2>{layout.timeline[0].toUpperCase() + layout.timeline.slice(1)} activity</h2></div><div>{(["daily", "weekly", "monthly"] as const).map((item) => <button key={item} className={layout.timeline === item ? "active" : ""} onClick={() => onLayout({ ...layout, timeline: item })}>{item}</button>)}</div></header><div className="timeline-bars">{Array.from({ length: period }, (_, index) => <article key={index}><i style={{ height: `${20 + ((index * 17 + projects.length * 11) % 62)}%` }} /><span>{layout.timeline === "weekly" ? ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][index] : index + 1}</span></article>)}</div><div className="timeline-events"><Event icon={<FolderKanban />} title="Project milestones" detail={projects.length ? `${projects.length} local project record(s) available for future event mapping.` : "No project milestones available yet."} /><Event icon={<Bot />} title="AI milestones" detail="Runtime readiness can become a future milestone source." /><Event icon={<Gauge />} title="Marketing events" detail="Campaign planning events are prepared by the Marketing Workspace." /></div></div>; }
function Resources({ core, storage }: { core: IntelligenceCore | null; storage: number }) { return <div className="resource-dashboard"><section className="resource-hero"><Cpu size={30} /><div><span>RESOURCE DASHBOARD</span><h2>Operational readiness</h2><p>Live monitoring adapters can replace the unsampled values without changing this layout.</p></div></section><div className="resource-grid"><Resource label="CPU usage" value="Not sampled" /><Resource label="GPU usage" value="Not sampled" /><Resource label="RAM usage" value="Not sampled" /><Resource label="Storage usage" value={bytes(storage)} /><Resource label="AI engine status" value={core?.aiCore ? "Ready" : "Offline"} ready={core?.aiCore} /><Resource label="Rendering queue" value="Not sampled" /><Resource label="Automation status" value={core?.automationEngine ? "Connected" : "Standby"} ready={core?.automationEngine} /><Resource label="Communication bus" value={core?.communicationBus ? "Connected" : "Standby"} ready={core?.communicationBus} /></div></div>; }
function Customize({ layout, onLayout, onClose }: { layout: IntelligenceLayout; onLayout: (layout: IntelligenceLayout) => void; onClose: () => void }) { return <aside className="intelligence-customize"><header><div><span>DASHBOARD CUSTOMIZATION</span><h3>Analytics widgets</h3></div><button onClick={onClose}><X size={15} /></button></header>{widgets.map((widget) => <label key={widget.id}><span>{widget.label}<small>{layout.compact.includes(widget.id) ? "Compact" : "Expanded"}</small></span><div><button onClick={() => onLayout(manager.toggleDensity(layout, widget.id))}><MoreHorizontal size={15} /></button><input type="checkbox" checked={!layout.hidden.includes(widget.id)} onChange={() => onLayout(manager.toggleVisibility(layout, widget.id))} /></div></label>)}</aside>; }
function Insight({ id, title, compact, onToggle, children }: { id: IntelligenceWidgetId; title: string; compact: boolean; onToggle: (id: IntelligenceWidgetId) => void; children: React.ReactNode }) { return <section className={`insight-widget ${compact ? "compact" : ""}`}><header><div><span>ANALYTICS WIDGET</span><h3>{title}</h3></div><button onClick={() => onToggle(id)} title="Toggle widget density"><MoreHorizontal size={15} /></button></header>{children}</section>; }
function Metric({ icon, value, label }: { icon: React.ReactNode; value: string | number; label: string }) { return <article className="intelligence-metric"><span>{icon}</span><b>{value}</b><small>{label}</small></article>; }
function Status({ label, value, good = false }: { label: string; value: string; good?: boolean }) { return <div className="intelligence-status"><span><i className={good ? "good" : ""} />{label}</span><b>{value}</b></div>; }
function Resource({ label, value, ready = false }: { label: string; value: string; ready?: boolean }) { return <div className="resource-row"><span>{label}</span><div><i className={ready ? "ready" : ""} /><b>{value}</b></div></div>; }
function Report({ report, favorite, onFavorite, onSelect }: { report: ReportRecord; favorite: boolean; onFavorite: () => void; onSelect: () => void }) { return <article onClick={onSelect}><div className={`report-symbol ${report.category}`}><FileBarChart size={20} /></div><button onClick={(event) => { event.stopPropagation(); onFavorite(); }}><Heart size={14} fill={favorite ? "currentColor" : "none"} /></button><b>{report.title}</b><small>{report.category} report · {report.status}</small><p>{report.detail}</p></article>; }
function Event({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <article><span>{icon}</span><div><b>{title}</b><p>{detail}</p></div></article>; }