import { createHash, randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import type { AiCoreManager } from "../core/ai-core-manager.js";
import type { CreativePlanningManager } from "../creative-planning/creative-planning-manager.js";
import type { CreativeWorkspaceManager } from "../creative-workspace/creative-workspace-manager.js";
import type { ImageGenerationManager } from "../image-generation/image-generation-manager.js";
import type { AiModelManager } from "../model-management/ai-model-manager.js";
import type { ProductIntelligenceManager } from "../product-intelligence/product-intelligence-manager.js";
import type { ImageIntelligenceManager } from "../image-intelligence/image-intelligence-manager.js";
import type { MarketingIntelligenceManager } from "../marketing-intelligence/marketing-intelligence-manager.js";
import type { DecisionIntelligenceManager } from "../decision-intelligence/decision-intelligence-manager.js";
import type { AiLearningManager } from "../learning-intelligence/learning-intelligence-manager.js";
import type { GeneratedVideoPackage, VideoGenerationRequest, VideoGenerationStore } from "./types.js";
import { LocalVideoEncoder } from "./video-encoder.js";

const EMPTY: VideoGenerationStore = { packages: [], history: [], cache: {}, logs: [] };

/** Produces a durable marketing-video package. The preview encoder can be replaced by an MP4/WebM provider later. */
export class VideoAudioGenerationManager {
  private root = ""; private core: AiCoreManager | null = null; private models: AiModelManager | null = null; private workspace: CreativeWorkspaceManager | null = null; private planning: CreativePlanningManager | null = null; private images: ImageGenerationManager | null = null; private productIntelligence: ProductIntelligenceManager | null = null; private imageIntelligence: ImageIntelligenceManager | null = null; private marketingIntelligence: MarketingIntelligenceManager | null = null; private decisionIntelligence: DecisionIntelligenceManager | null = null; private learningIntelligence: AiLearningManager | null = null; private store: VideoGenerationStore = structuredClone(EMPTY);
  readonly videoGenerator = new AiVideoGenerator(this); readonly videoModelSelector = new VideoModelSelector(this); readonly videoModelExecutor = new VideoModelExecutor(this); readonly imageToVideo = new ImageToVideoEngine(this); readonly textToVideo = new TextToVideoEngine(this); readonly productToVideo = new ProductToVideoEngine(this); readonly sceneAnimation = new SceneAnimationEngine(this); readonly cameraMotion = new CameraMotionEngine(this); readonly transition = new TransitionEngine(this); readonly timeline = new TimelineManager(this); readonly audio = new AudioGenerationManager(this); readonly voice = new AiVoiceGenerator(this); readonly music = new BackgroundMusicManager(this); readonly effects = new SoundEffectsManager(this); readonly subtitles = new SubtitleGenerator(this); readonly synchronization = new AudioSynchronizationManager(this); readonly quality = new VideoQualityManager(this); readonly metadata = new VideoMetadataManager(this); readonly history = new VideoHistoryManager(this);
  readonly encoder = new LocalVideoEncoder();

  async initialize(storageRoot: string, dependencies: { core: AiCoreManager; models: AiModelManager; workspace: CreativeWorkspaceManager; planning: CreativePlanningManager; images: ImageGenerationManager }): Promise<void> { this.root = path.join(storageRoot, "video-audio-generation-runtime"); this.core = dependencies.core; this.models = dependencies.models; this.workspace = dependencies.workspace; this.planning = dependencies.planning; this.images = dependencies.images; await fs.mkdir(path.join(this.root, "assets"), { recursive: true }); this.store = await this.readStore(); this.log("info", "Video and audio generation runtime restored."); await this.persist(); }
  isInitialized(): boolean { return Boolean(this.root); }
  attachProductIntelligence(manager: ProductIntelligenceManager): void { this.productIntelligence = manager; }
  attachImageIntelligence(manager: ImageIntelligenceManager): void { this.imageIntelligence = manager; }
  attachMarketingIntelligence(manager: MarketingIntelligenceManager): void { this.marketingIntelligence = manager; }
  attachDecisionIntelligence(manager: DecisionIntelligenceManager): void { this.decisionIntelligence = manager; }
  attachLearningIntelligence(manager: AiLearningManager): void { this.learningIntelligence = manager; }
  async generate(request: VideoGenerationRequest): Promise<GeneratedVideoPackage> { if (request.projectId) await this.decisionIntelligence?.decide(request.projectId, "video-generation"); this.ensureReady(); this.validate(request); const key = createHash("sha256").update(JSON.stringify(request)).digest("hex"); const existing = this.store.cache[key] ? this.store.packages.find((item) => item.id === this.store.cache[key]) : undefined; if (existing) return { ...existing, cached: true };
    const [videoModel, audioModel] = await Promise.all([this.videoModelSelector.select(request.videoModelId), this.audio.selectModel(request.audioModelId)]); const packageResult = await this.createPackage(request, videoModel.id, audioModel.id); this.store.packages.unshift(packageResult); this.store.cache[key] = packageResult.id; this.history.record("generation", `Generated ${request.mode} encoded video with timeline metadata.`, [packageResult.id]); this.log("info", `Generated ${packageResult.name}.`); await this.persist(); if (request.projectId) await this.learningIntelligence?.learnFromProject(request.projectId, "success", `Video package completed: ${request.mode}, ${packageResult.durationSeconds}s, local quality ${packageResult.quality.score}/100.`).catch((error) => this.log("warning", `Learning collection deferred: ${error instanceof Error ? error.message : String(error)}`)); return { ...packageResult}; }
  async getDashboard(projectId?: string): Promise<{ packages: GeneratedVideoPackage[]; history: VideoGenerationStore["history"]; logs: VideoGenerationStore["logs"]; models: ReturnType<AiModelManager["list"]>; images: Awaited<ReturnType<ImageGenerationManager["getDashboard"]>>["images"]; integrations: Record<string, boolean>; statistics: Record<string, number> }> { this.ensureReady(); const packages = this.store.packages.filter((item) => !projectId || item.projectId === projectId); const imageDashboard = await this.images!.getDashboard(projectId); return { packages: packages.map((item) => ({ ...item })), history: [...this.store.history], logs: [...this.store.logs], models: this.models!.list().filter((model) => (model.category === "video" || model.category === "audio" || model.category === "voice") && model.status !== "removed"), images: imageDashboard.images, integrations: { aiCore: Boolean(this.core), modelManagement: Boolean(this.models), imageGeneration: Boolean(this.images), videoGenerationFoundation: Boolean(this.core?.videoGenerationFoundation), audioGenerationFoundation: Boolean(this.core?.audioGenerationFoundation), videoIntelligence: Boolean(this.core?.videoIntelligenceFoundation), memoryFoundation: Boolean(this.core?.memoryFoundation), knowledgeFoundation: Boolean(this.core?.knowledgeFoundation), productIntelligence: Boolean(this.core?.productIntelligenceFoundation), imageIntelligence: Boolean(this.core?.imageIntelligenceFoundation), stateManager: Boolean(this.core?.stateManager), moduleManager: Boolean(this.core?.moduleManager), creativePipeline: Boolean(this.core?.workflowEngine) }, statistics: { generatedPackages: this.store.packages.length, cachedRequests: Object.keys(this.store.cache).length, averageQuality: this.store.packages.length ? Math.round(this.store.packages.reduce((sum, item) => sum + item.quality.score, 0) / this.store.packages.length) : 0 } }; }
  async defaultRequest(projectId: string): Promise<Partial<VideoGenerationRequest>> { const [project, plan, profile, imageProfiles, marketing, imageDashboard] = await Promise.all([this.workspace!.getProject(projectId), this.planning!.getPlan(projectId), this.productIntelligence?.getProfile(projectId), this.imageIntelligence?.getProfiles(projectId), this.marketingIntelligence?.getProfile(projectId), this.images!.getDashboard(projectId)]); const imageProfile = imageProfiles?.[0]; if (!project) throw new Error("Project not found"); const image = imageDashboard.images[0]; return { projectId, prompt: plan?.prompts.video ?? `${project.productInformation.name} ${profile ? `${profile.category} ${profile.shapes.join(" ")}` : ""}${imageProfile ? `, ${imageProfile.cameraAngle}` : ""}${marketing ? `, ${marketing.strategy}, CTA: ${marketing.ctas[0]}` : ""} marketing video`, mode: image ? "image-to-video" : project.productImages.length ? "product-to-video" : "text-to-video", imageId: image?.id, durationSeconds: 15, resolution: "1080p", frameRate: 30, voice: "narrator", music: "uplifting", soundEffects: true, subtitles: true }; }
  async getAssetPath(packageId: string, kind: "preview" | "audio" | "subtitles"): Promise<string | null> { const item = this.store.packages.find((entry) => entry.id === packageId); const fileName = kind === "preview" ? item?.previewFileName : kind === "audio" ? item?.audioFileName : item?.subtitleFileName; if (!fileName) return null; const target = path.join(this.root, "assets", fileName); try { await fs.access(target); return target; } catch { return null; } }
  private async createPackage(request: VideoGenerationRequest, videoModelId: string, audioModelId: string): Promise<GeneratedVideoPackage> { const project = request.projectId ? await this.workspace!.getProject(request.projectId) : null; const plan = request.projectId ? await this.planning!.getPlan(request.projectId) : null; const image = request.imageId ? (await this.images!.getDashboard(request.projectId)).images.find((item) => item.id === request.imageId) : undefined; if (request.mode === "image-to-video" && !image) throw new Error("image-to-video requires a generated local image asset"); const sourceImageBase64 = image ? await this.readImageAsset(image.id) : undefined; const id = randomUUID(); const timeline = this.timeline.build(plan?.scenes ?? [], request.durationSeconds, project?.productInformation.name ?? "Creative concept", request.prompt); const [width, height] = request.resolution === "1080p" ? [1920, 1080] : [1280, 720]; const prompt = await this.constructPrompt(request, project?.productInformation.name); const rendered = await this.models!.inference.generateVideo({ modelId: videoModelId, prompt, durationSeconds: request.durationSeconds, width, height, frameRate: request.frameRate, sourceImageBase64 }); const sourceExtension = rendered.mimeType === "video/webm" ? "webm" : "mp4"; const outputFormat = request.outputFormat ?? sourceExtension; const previewFileName = `${id}.${outputFormat}`; const previewPath = path.join(this.root, "assets", previewFileName); const sourcePath = outputFormat === sourceExtension && !request.codec ? previewPath : path.join(this.root, "assets", `${id}.provider.${sourceExtension}`); const subtitleFileName = request.subtitles ? `${id}.vtt` : undefined; await fs.writeFile(sourcePath, rendered.bytes); if (sourcePath !== previewPath) { await this.encoder.encode(sourcePath, previewPath, request.codec ?? "h264"); await fs.rm(sourcePath, { force: true }); } if (subtitleFileName) await fs.writeFile(path.join(this.root, "assets", subtitleFileName), this.subtitles.create(timeline), "utf8"); return { id, projectId: request.projectId, name: `${project?.name ?? "Creative"} video package`, mode: request.mode, prompt, createdAt: new Date().toISOString(), durationSeconds: request.durationSeconds, resolution: request.resolution, frameRate: request.frameRate, videoModelId, audioModelId, previewFileName, subtitleFileName, imageId: image?.id, timeline, quality: this.quality.score(request, Boolean(image), rendered.bytes.byteLength), metadata: { ...this.metadata.create(request, timeline.length, rendered.providerId, rendered.backend, rendered.durationMs), outputFormat, codec: request.codec ?? "provider" }, cached: false }; }
  log(level: "info" | "warning" | "error", message: string): void { this.store.logs.unshift({ at: new Date().toISOString(), level, message }); this.store.logs.splice(100); this.core?.logger.info("generation", message); }
  async persist(): Promise<void> { await fs.writeFile(path.join(this.root, "generation.json"), `${JSON.stringify(this.store, null, 2)}\n`, "utf8"); }
  private validate(request: VideoGenerationRequest): void { if (request.prompt.trim().length < 8) throw new Error("Provide a descriptive video prompt of at least 8 characters"); if (!Number.isInteger(request.durationSeconds) || request.durationSeconds < 3 || request.durationSeconds > 60) throw new Error("Video duration must be between 3 and 60 seconds"); }
  private async readStore(): Promise<VideoGenerationStore> { try { const value = JSON.parse(await fs.readFile(path.join(this.root, "generation.json"), "utf8")) as Partial<VideoGenerationStore>; return { ...structuredClone(EMPTY), ...value, packages: value.packages ?? [], history: value.history ?? [], cache: value.cache ?? {}, logs: value.logs ?? [] }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return structuredClone(EMPTY); throw error; } }
  private async readImageAsset(imageId: string): Promise<string> { const sourcePath = await this.images!.getAssetPath(imageId); if (!sourcePath) throw new Error("Selected image asset is unavailable for local video inference"); const bytes = await fs.readFile(sourcePath); if (!bytes.length || bytes.length > 50 * 1024 * 1024) throw new Error("Selected image asset is invalid for local video inference"); return bytes.toString("base64"); }
  private async constructPrompt(request: VideoGenerationRequest, productName?: string): Promise<string> { const projectId = request.projectId; const [product, imageProfiles, marketing] = await Promise.all([projectId ? this.productIntelligence?.analyze(projectId) : undefined, projectId ? this.imageIntelligence?.analyzeProject(projectId) : undefined, projectId ? this.marketingIntelligence?.analyze(projectId) : undefined]); return [...new Set([productName, product?.category, product?.materials.join(", "), imageProfiles?.[0]?.composition, marketing?.valueProposition, marketing?.strategy, request.scene?.replace(/-/g, " "), request.camera?.replace(/-/g, " "), request.animation?.replace(/-/g, " "), request.transition?.replace(/-/g, " "), "cinematic professional product commercial", request.prompt].filter((value): value is string => Boolean(value && !value.includes("requires visual-provider verification"))).map((value) => value.replace(/\s+/g, " ").trim()))].join(", "); }
  private ensureReady(): void { if (!this.root || !this.models || !this.workspace || !this.planning || !this.images) throw new Error("Video and Audio Generation Manager is not initialized"); }
}

export class VideoModelSelector { constructor(private readonly manager: VideoAudioGenerationManager) {} async select(requested?: string) { let model = requested ? this.manager["models"]!.getMutable(requested) : await this.manager["models"]!.selectBest("video"); if (!model) { await this.manager["models"]!.installer.install("studio-video-base"); model = this.manager["models"]!.getMutable("studio-video-base"); } if (model.category !== "video") throw new Error("Selected model does not support video generation"); return model; } }
export class VideoModelExecutor { constructor(private readonly manager: VideoAudioGenerationManager) {} async load(id: string): Promise<void> { await this.manager["models"]!.preparePreview(id); } }
export class AiVideoGenerator { constructor(private readonly manager: VideoAudioGenerationManager) {} compose(input: { request: VideoGenerationRequest; timeline: GeneratedVideoPackage["timeline"]; brand: string; imageUrl?: string }): string { const w = input.request.resolution === "1080p" ? 1920 : 1280; const h = w * 9 / 16; const scenes = input.timeline.map((scene, index) => `<g opacity="0"><set attributeName="opacity" to="1" begin="${scene.start}s" dur="${Math.max(1, scene.end - scene.start)}s"/><rect width="${w}" height="${h}" fill="${index % 2 ? "#16233a" : "#0c1422"}"/>${input.imageUrl ? `<image href="${input.imageUrl}" x="${w * .54}" y="${h * .12}" width="${w * .38}" height="${h * .76}" preserveAspectRatio="xMidYMid meet"><animate attributeName="x" from="${w * .57}" to="${w * .51}" dur="${Math.max(2, scene.end - scene.start)}s" fill="freeze"/></image>` : `<circle cx="${w * .7}" cy="${h * .5}" r="${w * .13}" fill="#e6a74a"><animate attributeName="r" values="${w * .11};${w * .15};${w * .11}" dur="2s" repeatCount="indefinite"/></circle>`}<text x="${w * .1}" y="${h * .2}" fill="#f7e7ce" font-family="Arial" font-size="${w * .035}" font-weight="700">${xml(input.brand).toUpperCase()}</text><text x="${w * .1}" y="${h * .46}" fill="#fff" font-family="Arial" font-size="${w * .055}" font-weight="700">${xml(scene.visual).slice(0, 55)}</text><text x="${w * .1}" y="${h * .58}" fill="#d6dde8" font-family="Arial" font-size="${w * .025}">${xml(scene.narration).slice(0, 95)}</text></g>`).join(""); return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${scenes}</svg>`; } }
export class ImageToVideoEngine { constructor(private readonly manager: VideoAudioGenerationManager) {} }
export class TextToVideoEngine { constructor(private readonly manager: VideoAudioGenerationManager) {} }
export class ProductToVideoEngine { constructor(private readonly manager: VideoAudioGenerationManager) {} }
export class SceneAnimationEngine { constructor(private readonly manager: VideoAudioGenerationManager) {} }
export class CameraMotionEngine { constructor(private readonly manager: VideoAudioGenerationManager) {} }
export class TransitionEngine { constructor(private readonly manager: VideoAudioGenerationManager) {} }
export class TimelineManager { constructor(private readonly manager: VideoAudioGenerationManager) {} build(scenes: Array<{ durationSeconds: number; narration: string; visual: string }>, duration: number, fallbackName: string, prompt: string): GeneratedVideoPackage["timeline"] { const source = scenes.length ? scenes : [{ durationSeconds: duration, narration: prompt, visual: fallbackName }]; const total = source.reduce((sum, scene) => sum + scene.durationSeconds, 0); let cursor = 0; return source.map((scene, index) => { const allocated = index === source.length - 1 ? duration - cursor : Math.max(1, Math.round(duration * scene.durationSeconds / total)); const entry = { scene: index + 1, start: cursor, end: cursor + allocated, narration: scene.narration, visual: scene.visual }; cursor += allocated; return entry; }); } }
export class AudioGenerationManager { constructor(private readonly manager: VideoAudioGenerationManager) {} async selectModel(requested?: string) { let model = requested ? this.manager["models"]!.getMutable(requested) : await this.manager["models"]!.selectBest("audio"); if (!model) { await this.manager["models"]!.installer.install("studio-audio-base"); model = this.manager["models"]!.getMutable("studio-audio-base"); } if (model.category !== "audio") throw new Error("Selected model does not support audio generation"); return model; } async load(id: string): Promise<void> { await this.manager["models"]!.preparePreview(id); } synthesize(request: VideoGenerationRequest, timeline: GeneratedVideoPackage["timeline"]): Buffer { const sampleRate = 8000; const samples = sampleRate * request.durationSeconds; const output = Buffer.alloc(44 + samples * 2); writeWavHeader(output, samples, sampleRate); for (let index = 0; index < samples; index++) { const time = index / sampleRate; const voice = request.voice === "energetic" ? Math.sin(time * 2 * Math.PI * 220) : Math.sin(time * 2 * Math.PI * 150); const music = request.music === "none" ? 0 : Math.sin(time * 2 * Math.PI * (request.music === "bold" ? 92 : 70)); const effect = request.soundEffects && timeline.some((scene) => Math.abs(time - scene.start) < .04) ? .5 : 0; output.writeInt16LE(Math.max(-1, Math.min(1, voice * .18 + music * .1 + effect)) * 32767, 44 + index * 2); } return output; } }
export class AiVoiceGenerator { constructor(private readonly manager: VideoAudioGenerationManager) {} }
export class BackgroundMusicManager { constructor(private readonly manager: VideoAudioGenerationManager) {} }
export class SoundEffectsManager { constructor(private readonly manager: VideoAudioGenerationManager) {} }
export class SubtitleGenerator { constructor(private readonly manager: VideoAudioGenerationManager) {} create(timeline: GeneratedVideoPackage["timeline"]): string { return `WEBVTT\n\n${timeline.map((scene, index) => `${index + 1}\n${time(scene.start)} --> ${time(scene.end)}\n${scene.narration}\n`).join("\n")}`; } }
export class AudioSynchronizationManager { constructor(private readonly manager: VideoAudioGenerationManager) {} }
export class VideoQualityManager { constructor(private readonly manager: VideoAudioGenerationManager) {} score(request: VideoGenerationRequest, hasImage: boolean, sizeBytes: number) { if (!sizeBytes) throw new Error("Local video provider returned an empty encoded asset"); return { score: Math.min(98, 72 + (hasImage ? 10 : 0) + (request.subtitles ? 5 : 0) + (sizeBytes > 10_000 ? 6 : 0)), notes: [hasImage ? "Local source image was conditioned into the video model workflow." : "Text-to-video inference completed by a local video model.", "Encoded video bytes and timeline metadata were validated."] }; } }
export class VideoMetadataManager { constructor(private readonly manager: VideoAudioGenerationManager) {} create(request: VideoGenerationRequest, sceneCount: number, provider: string, backend: string, durationMs: number): Record<string, string | number> { return { provider, backend, durationMs, sceneCount, subtitleEnabled: String(request.subtitles), audioSync: "timeline-aligned", audioStatus: "Separate audio inference is not configured", generatedAt: new Date().toISOString() }; } }
export class VideoHistoryManager { constructor(private readonly manager: VideoAudioGenerationManager) {} record(event: string, detail: string, packageIds: string[]): void { this.manager["store"].history.unshift({ id: randomUUID(), at: new Date().toISOString(), event, detail, packageIds }); } }
function writeWavHeader(output: Buffer, samples: number, sampleRate: number): void { output.write("RIFF", 0); output.writeUInt32LE(36 + samples * 2, 4); output.write("WAVEfmt ", 8); output.writeUInt32LE(16, 16); output.writeUInt16LE(1, 20); output.writeUInt16LE(1, 22); output.writeUInt32LE(sampleRate, 24); output.writeUInt32LE(sampleRate * 2, 28); output.writeUInt16LE(2, 32); output.writeUInt16LE(16, 34); output.write("data", 36); output.writeUInt32LE(samples * 2, 40); }
function time(value: number): string { const minutes = Math.floor(value / 60); const seconds = Math.floor(value % 60); const milliseconds = Math.round((value % 1) * 1000); return `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}.${String(milliseconds).padStart(3, "0")}`; }
function xml(value: string): string { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;"); }